/-
Copyright (c) 2026 ABC3. All rights reserved.
-/
import ABC3.Meta.Claim
import Mathlib.Data.Real.Basic
import Mathlib.Data.Set.Finite.Basic

/-!
# HeightTheory —— `[GenEll] Definition 1.1` の分

☆もとの 1 枚を**条なしの項目ごと**に割ったものである（第 1458、案 a）。
★「1 ファイル = 1 ノード」を回復するための分割で、中身は動かしていない。
-/

namespace ABC3.Interface.GenEll

open ABC3.Meta

/-- **[GenEll] §1 の語彙**を受ける `Interface`。

★フィールドはすべて**原文 §1 に実際に現れる語**と 1 対 1 に対応する。
現れない語は入れていない(仮説の強化を避けるため——G5)。

★**述語 `Ample` / `SomePowerGlobGen` は「性質」であって「公理」ではない**。
これらが何を満たすかは一切 posit していないので、
`Proposition 1.4, (ii)(iv)` は本当に未証明のまま残る。 -/
structure HeightTheoryData where
  /-- `X(ℚ̄)` —— `X` の `ℚ̄` 値点。 -/
  Point : Type
  /-- `APic(X)` の代表 —— `X` 上の算術直線束 `L̄ = (L, |−|_L)`。 -/
  ABundle : Type
  /-- `X` 上の**有効 Cartier 因子** `D`。 -/
  Divisor : Type
  /-- `X_ℚ` 上の直線束 `L_ℚ` の同型類。★`Proposition 1.4, (iii)` はここに落ちる。 -/
  GenericClass : Type
  /-- 原文「There is an evident notion of tensor product of arithmetic line bundles on X」。 -/
  tensor : ABundle → ABundle → ABundle
  /-- 原文 `ht_M̄ : X(ℚ̄) → ℝ`(`Definition 1.2, (i)`)。 -/
  ht : ABundle → Point → ℝ
  /-- `L̄ ↦ L_ℚ`(`Proposition 1.4` の `L_ℚ ≝ L|_{X_ℚ}`)。 -/
  generic : ABundle → GenericClass
  /-- 原文「the line bundle `L_ℚ` is **ample**」。 -/
  Ample : GenericClass → Prop
  /-- 原文「some positive tensor power of the line bundle `L_ℚ` on `X_ℚ` is
  **generated by global sections**」。 -/
  SomePowerGlobGen : GenericClass → Prop
  /-- 原文 `X(ℚ̄)^{≤d}`(`Example 1.3, (i)`)。 -/
  degLe : ℕ → Set Point
  /-- `D ↦ O_X(D)`(`Proposition 1.6` の `L = O_X(D)`)。 -/
  bundleOf : Divisor → ABundle
  /-- `D ↦ U(ℚ̄)` ただし `U ≝ X\D`(`Definition 1.5, (iv)` / `Proposition 1.6`)。 -/
  compl : Divisor → Set Point
  /-- 原文 `log-diff_X : X(ℚ̄) → ℝ`(`Definition 1.5, (iii)`)。 -/
  logDiff : Point → ℝ
  /-- 原文 `log-cond_D : U_X(ℚ̄) → ℝ`(`Definition 1.5, (iv)`)。 -/
  logCond : Divisor → Point → ℝ
  /-- 原文「a nonempty `ι_X`-stable **compact domain**」から作られる
  **compactly bounded subset**(`Example 1.3, (ii)`)。
  ★これは `X^arc` を要求するので posit するほかない。 -/
  CompactlyBounded : Set Point → Prop

/-- ★**Track B は何を作らねばならないか。**

★`waiting` を書く(非空虚 witness ではなく)。本構造体は公理を 1 つも持たないので
「無矛盾です」と言っても情報がない——**言うべきなのは「まだ作っていない」の中身**である。 -/
def HeightTheoryData.waiting : WaitingFor :=
  { what := "算術直線束 APic(X) とエルミート計量、複素解析空間 X^arc(= X(ℂ) と複素共役 ι_X)、および高さ関数 ht_L̄ の構成。★着手時点(2026-08-16)では mathlib に Arakelov / arithmetic line bundle / LineBundle / Scheme…Picard / analytification / GAGA / complex analytic space はいずれも 0 件だった"
    trackB := "★★★★2026-08-27 に更新 —— **律速だった X^arc は建った**。Found/Arakelov(317 ファイル・約 3.1 万行、Arc* が X^arc の層 C・評価・連続性・ι_X 対合・1 の分割)と Found/GaloisRep(314 ファイル・約 5.3 万行)がそれで、.src は 874 件すべて GenEll タグ、Found/ は sorry 0。★Definition 1.1 には条つき .src が 384 個ある。★★したがって残るのは (a) ではなく **条なし .src への組み上げ**である。★旧記述『律速は X^arc の複素解析側であり、着手の形跡も無い』は 2026-08-16 の実測であって、いまは当たらない" }

/-! ## ★出典の紐付け(`.src`) -/

def HeightTheoryData.src : Source :=
  { paper := "GenEll", pdfPage := 3, item := "Definition 1.1",
    sectionId := "genell-def-1-1" }

end ABC3.Interface.GenEll
