import ABC3.Meta.Claim
import ABC3.Found.ResidueFieldFinite
import ABC3.Found.PGC.LocalFieldNorm
import ABC3.Found.PGC.QpResidueField
import ABC3.Found.PGC.ResidueCardinality
import ABC3.Found.FrdI.MonoidVocabulary
import ABC3.Found.FrdI.MonoidPrime
import ABC3.Found.FrdI.CategoryAnchor
import ABC3.Found.FrdI.Def31
import ABC3.Found.FrdI.Prop33
import ABC3.Found.FrdI.Prop311
import ABC3.Found.FrdI.Prop33v
import ABC3.Found.FrdI.UnTr
import ABC3.Found.FrdI.Example310
import ABC3.Found.FrdI.Remark311
import ABC3.Found.FrdI.Remark312
import ABC3.Found.FrdI.CategoryVocabulary
import ABC3.Found.FrdI.ElementaryFrobenioid
import ABC3.Found.FrdI.MorphismTypes
import ABC3.Found.FrdI.Witness
import ABC3.Found.FrdI.Frobenioid
import ABC3.Found.FrdI.WitnessFrobenioid
import ABC3.Found.FrdI.NegControl
import ABC3.Found.FrdI.Prop14
import ABC3.Found.FrdI.Prop15
import ABC3.Found.FrdI.Prop16
import ABC3.Found.FrdI.Prop17
import ABC3.Found.FrdI.Prop18
import ABC3.Found.FrdI.Prop19
import ABC3.Found.FrdI.Prop110
import ABC3.Found.FrdI.Prop111
import ABC3.Found.FrdI.Prop113
import ABC3.Found.FrdI.Prop114
import ABC3.Found.FrdI.Prop21
import ABC3.Found.FrdI.Prop22
import ABC3.Found.FrdI.Prop22Star
import ABC3.Found.FrdI.Def23
import ABC3.Found.FrdI.Def27
import ABC3.Found.FrdI.Prop25
import ABC3.Found.FrdI.Prop25iii
import ABC3.Found.FrdI.Thm34
import ABC3.Found.FrdI.Rmk341
import ABC3.Found.FrdI.Prop41
import ABC3.Found.FrdI.Def31Pf
import ABC3.Found.FrdI.HomColim
import ABC3.Found.FrdI.Prop32
import ABC3.Found.FrdI.Prop44
import ABC3.Found.FrdI.Prop33UnTr
import ABC3.Found.FrdI.Prop33Classes
import ABC3.Found.FrdI.Prop33i
import ABC3.Found.FrdI.Prop33Coa
import ABC3.Found.FrdI.Thm34Rigid
import ABC3.Found.FrdI.Lemma65
import ABC3.Found.FrdI.Prop44Pre
import ABC3.Found.FrdI.Def45
import ABC3.Found.FrdI.Prop44Gp
import ABC3.Found.FrdI.Prop44Core
import ABC3.Found.IUTchIII.LogShell
import ABC3.Found.IUTchIII.PadicLog
import ABC3.Found.IUTchIII.PowerSeriesLog
import ABC3.Found.IUTchIII.LogVolume
import ABC3.Found.IUTchIII.PadicLogMul
import ABC3.Found.SemiAnbd.TemperedGroup
import ABC3.Found.GenEll.Lemma31
import ABC3.Found.GenEll.BDClass
import ABC3.Found.GenEll.Sl2Adjoint
import ABC3.Found.GenEll.Sl2Congruence
import ABC3.Found.GenEll.Sl2Level
import ABC3.Found.GenEll.Sl2Padic
import ABC3.Found.GenEll.Elementary
import ABC3.Found.GenEll.PrimesOfSize
import ABC3.Found.GenEll.ArithDiv
import ABC3.Found.GenEll.ArithDivHom
import ABC3.Found.GenEll.ProductFormula
import ABC3.Found.GenEll.Conductor
import ABC3.Found.GenEll.LogDiff
import ABC3.Found.GenEll.LogDiffValue
import ABC3.Found.GenEll.NorthcottRat
import ABC3.Found.GenEll.InfinitePlaceRel
import ABC3.Found.GenEll.FinitePlaceRel
import ABC3.Found.GenEll.BaseChange
import ABC3.Found.GenEll.LogDiffTower
import ABC3.Found.GenEll.CartierPullback
import ABC3.Found.GenEll.MinField
import ABC3.Found.GenEll.RadicalPrincipal
import ABC3.Found.GenEll.LogDiffFinite
import ABC3.Found.GenEll.HeightADiv
import ABC3.Found.GenEll.NorthcottNF
import ABC3.Found.GenEll.OrdvIntegral
import ABC3.Found.GenEll.DenominatorBound
import ABC3.Found.GenEll.NorthcottProj
import ABC3.Found.GenEll.HeightExtension
import ABC3.Found.GenEll.NorthcottDegree
import ABC3.Found.GenEll.HeightConjugate
import ABC3.Found.GenEll.PrimeNumberTheorem
import ABC3.Found.GenEll.ProjTopology
import ABC3.Found.GenEll.IdealStalk
import ABC3.Found.GenEll.StalkPullback
import ABC3.Found.GenEll.DegMul
import ABC3.Found.GenEll.ArchPoint
import ABC3.Found.GenEll.HeightConstruction
import ABC3.Found.GenEll.HeightNonneg
import ABC3.Found.GenEll.HeightClass
import ABC3.Found.GenEll.RadicalCartier
import ABC3.Found.GenEll.StalkSupport
import ABC3.Found.GenEll.ConductorHeight
import ABC3.Found.GenEll.ArchBound
import ABC3.Found.GenEll.ProjClosed
import ABC3.Found.GenEll.CompactBound
import ABC3.Found.GenEll.ArcModel
import ABC3.Found.GenEll.ComapLocal
import ABC3.Found.GenEll.ComapStalk
import ABC3.Found.GenEll.ComapAffine
import ABC3.Found.GenEll.ComapMul
import ABC3.Found.GenEll.HeightAdditive
import ABC3.Found.GenEll.PullbackBase
import ABC3.Found.GenEll.ArchConj
import ABC3.Found.GenEll.ArchBaseChange
import ABC3.Found.GenEll.IdealADivBase
import ABC3.Found.GenEll.ArchADivBase
import ABC3.Found.GenEll.HeightBaseChange
import ABC3.Found.GenEll.PullbackNatural
import ABC3.Found.GenEll.ArchCompat
import ABC3.Found.GenEll.HeightInvariant
import ABC3.Found.GenEll.AlgPoint
import ABC3.Found.Arakelov.ArcEval
import ABC3.Found.Arakelov.ArcConjInvol
import ABC3.Found.Arakelov.ArcTopologyAffine
import ABC3.Found.GenEll.UPoint
import ABC3.Found.GenEll.HeightInterface
import ABC3.Found.GenEll.DegSubset
import ABC3.Found.GenEll.Prop16
import ABC3.Found.GenEll.NorthcottClassical
import ABC3.Found.NCBelyi.Separation
import ABC3.Found.NCBelyi.Lemma21
import ABC3.Found.NCBelyi.BelyiComp
import ABC3.Found.NCBelyi.Normalize
/-!
# Found — 実装済みの基礎

Track B。`Interface` の `structure` を本物にする場所。**`sorry` を残さない。**
mathlib へ PR できる品質で書く——IUT の当否に関わらず残る成果になる。
-/
