import ABC3.Meta.Claim
import ABC3.Found.ResidueFieldFinite
import ABC3.Found.AddEquivNNReal
import ABC3.Found.PGC.LocalFieldNorm
import ABC3.Found.PGC.QpResidueField
import ABC3.Found.PGC.ResidueCardinality
import ABC3.Found.FrdI.MonoidVocabulary
import ABC3.Found.FrdI.MonoidPrime
import ABC3.Found.FrdI.CategoryAnchor
import ABC3.Found.FrdI.Def31
import ABC3.Found.FrdI.Prop33
import ABC3.Found.FrdI.Prop311
import ABC3.Found.FrdI.Prop33v
import ABC3.Found.FrdI.UnTr
import ABC3.Found.FrdI.Example310
import ABC3.Found.FrdI.Remark311
import ABC3.Found.FrdI.Remark312
import ABC3.Found.FrdI.Profinite
import ABC3.Found.FrdI.Thm62Slim
import ABC3.Found.FrdI.CategoryVocabulary
import ABC3.Found.FrdI.ElementaryFrobenioid
import ABC3.Found.FrdI.MorphismTypes
import ABC3.Found.FrdI.Witness
import ABC3.Found.FrdI.Frobenioid
import ABC3.Found.FrdI.WitnessFrobenioid
import ABC3.Found.FrdI.NegControl
import ABC3.Found.FrdI.Prop14
import ABC3.Found.FrdI.Prop15
import ABC3.Found.FrdI.Prop16
import ABC3.Found.FrdI.Prop17
import ABC3.Found.FrdI.Prop18
import ABC3.Found.FrdI.Prop19
import ABC3.Found.FrdI.Prop110
import ABC3.Found.FrdI.SubAutInvariants
import ABC3.Found.FrdI.Def28
import ABC3.Found.FrdI.Prop111
import ABC3.Found.FrdI.Prop113
import ABC3.Found.FrdI.Prop114
import ABC3.Found.FrdI.Prop21
import ABC3.Found.FrdI.Prop22
import ABC3.Found.FrdI.Prop22Star
import ABC3.Found.FrdI.Def23
import ABC3.Found.FrdI.Def27
import ABC3.Found.FrdI.Prop25
import ABC3.Found.FrdI.Prop25iii
import ABC3.Found.FrdI.Thm34
import ABC3.Found.FrdI.Rmk341
import ABC3.Found.FrdI.Prop41
import ABC3.Found.FrdI.Def31Pf
import ABC3.Found.FrdI.HomColim
import ABC3.Found.FrdI.HomColimQuot
import ABC3.Found.FrdI.Prop32
import ABC3.Found.FrdI.Prop32Frob
import ABC3.Found.FrdI.Prop32Equiv
import ABC3.Found.FrdI.Prop32Dict
import ABC3.Found.FrdI.Prop32Perfect
import ABC3.Found.FrdI.Prop41Cat
import ABC3.Found.FrdI.Def24Supp
import ABC3.Found.FrdI.Def24SuppElt
import ABC3.Found.FrdI.Def24PfTransport
import ABC3.Found.FrdI.Def24ScTransport
import ABC3.Found.FrdI.Prop44
import ABC3.Found.FrdI.Prop44Univ
import ABC3.Found.FrdI.Prop33UnTr
import ABC3.Found.FrdI.Prop33Classes
import ABC3.Found.FrdI.Prop33i
import ABC3.Found.FrdI.Prop33Coa
import ABC3.Found.FrdI.Thm34Rigid
import ABC3.Found.FrdI.Thm34Pre
import ABC3.Found.FrdI.Lemma65
import ABC3.Found.FrdI.Lemma65ii
import ABC3.Found.FrdI.Thm64Rat
import ABC3.Found.FrdI.Prop44Pre
import ABC3.Found.FrdI.Def45
import ABC3.Found.FrdI.Example43
import ABC3.Found.FrdI.Thm52
import ABC3.Found.FrdI.Thm52Change
import ABC3.Found.FrdI.Thm52Frob
import ABC3.Found.FrdI.Thm52Otimes
import ABC3.Found.FrdI.Thm52Birat
import ABC3.Found.FrdI.Remark491
import ABC3.Found.FrdI.Prop44Gp
import ABC3.Found.FrdI.Prop44Core
import ABC3.Found.FrdI.Prop44Otri
import ABC3.Found.FrdI.Prop44Ore
import ABC3.Found.FrdI.Prop44Ker
import ABC3.Found.FrdI.Prop44Equiv
import ABC3.Found.FrdI.Prop44Gl
import ABC3.Found.FrdI.Prop44Phi
import ABC3.Found.FrdI.Thm34Quasi
import ABC3.Found.FrdI.Thm34EndBs
import ABC3.Found.FrdI.Cor411Untr
import ABC3.Found.FrdI.Cor411Base
import ABC3.Found.FrdI.Cor411Otimes
import ABC3.Found.FrdI.Cor411Rigid
import ABC3.Found.FrdI.Thm51Slice
import ABC3.Found.FrdI.Thm51Span
import ABC3.Found.FrdI.Thm51Cls
import ABC3.Found.FrdI.Thm51Pic
import ABC3.Found.FrdI.Thm51Hom
import ABC3.Found.FrdI.Thm51Sec
import ABC3.Found.FrdI.Thm51FrTr
import ABC3.Found.FrdI.Prop16AutAmple
import ABC3.Found.FrdI.Thm52Path
import ABC3.Found.FrdI.Thm52Ref
import ABC3.Found.FrdI.Thm52Rem272
import ABC3.Found.FrdI.Thm52BiratSec
import ABC3.Found.FrdI.Thm52Model
import ABC3.Found.FrdI.Thm52NatIso
import ABC3.Found.FrdI.Thm52ModelType
import ABC3.Found.FrdI.Prop53Birat
import ABC3.Found.FrdI.Prop56Sec
import ABC3.Found.FrdI.Prop56Exists
import ABC3.Found.FrdI.Cor57Unit
import ABC3.Found.FrdI.Cor57Pair
import ABC3.Found.FrdI.Cor57Base
import ABC3.Found.FrdI.Cor57Model
import ABC3.Found.FrdI.Def24Rlf
import ABC3.Found.FrdI.Def24PfT
import ABC3.Found.FrdI.Def24RlfCone
import ABC3.Found.FrdI.Def24RlfPerf
import ABC3.Found.FrdI.PfGp
import ABC3.Found.FrdI.ModelRigid
import ABC3.Found.FrdI.ModelSquare
import ABC3.Found.FrdI.Cor54Rigid
import ABC3.Found.FrdI.Thm62Psi
import ABC3.Found.FrdI.Thm62Frob
import ABC3.Found.FrdI.Prop56Cos
import ABC3.Found.FrdI.Prop56Mp
import ABC3.Found.FrdI.Prop56MpAbs
import ABC3.Found.FrdI.Prop56Limit
import ABC3.Found.FrdI.Prop53Rlf
import ABC3.Found.FrdI.Cor54
import ABC3.Found.FrdI.Cor54Birat
import ABC3.Found.FrdI.Prop55Rlf
import ABC3.Found.FrdI.Prop55PfKappa
import ABC3.Found.FrdI.Prop55Birat
import ABC3.Found.FrdI.Prop55BiratPf
import ABC3.Found.FrdI.Thm62RatStd
import ABC3.Found.FrdI.Thm64RatStd
import ABC3.Found.FrdI.Prop55Pf
import ABC3.Found.FrdI.Prop55PfUnit
import ABC3.Found.FrdI.Prop55PfDiv
import ABC3.Found.FrdI.Prop55PfSlice
import ABC3.Found.FrdI.Prop53UntrPf
import ABC3.Found.FrdI.Prop55Untr
import ABC3.Found.FrdI.Prop55UntrIdx
import ABC3.Found.FrdI.Prop55UntrCat
import ABC3.Found.FrdI.Sec6GaloisCat
import ABC3.Found.FrdI.Thm62Fsm
import ABC3.Found.Divisor.HeightOneDVR
import ABC3.Found.Divisor.Hartogs
import ABC3.Found.Divisor.FreeDivisorial
import ABC3.Found.Divisor.CartierMonoid
import ABC3.Found.Divisor.CartierPrime
import ABC3.Found.Divisor.CartierPf
import ABC3.Found.Divisor.CartierMonoprime
import ABC3.Found.Divisor.CartierPerfFactorial
import ABC3.Found.Divisor.CartierFrobenioid
import ABC3.Found.Divisor.ArithDivisor
import ABC3.Found.Divisor.ArithPicR
import ABC3.Found.Divisor.ArithOrd
import ABC3.Found.Divisor.ArithPhiMonoid
import ABC3.Found.Divisor.ArithGp
import ABC3.Found.Divisor.ArithMonoprime
import ABC3.Found.Divisor.ArithPhiPrime
import ABC3.Found.Divisor.ArithPf
import ABC3.Found.Divisor.ArithPerfFactorial
import ABC3.Found.Divisor.ArithSuppSplit
import ABC3.Found.Divisor.ArithPhiPerf
import ABC3.Found.Divisor.ArithFunctor
import ABC3.Found.Divisor.ArithFundamental
import ABC3.Found.Divisor.ArithRlfFlat
import ABC3.Found.Divisor.ArithTower
import ABC3.Found.Divisor.ArithSurj
import ABC3.Found.Divisor.ArithFrobenioid
import ABC3.Found.Divisor.Ex63Datum
import ABC3.Found.Divisor.Ex63Bmon
import ABC3.Found.Divisor.Ex63Model
import ABC3.Found.Divisor.Ex63Morph
import ABC3.Found.Divisor.SchemeWeil
import ABC3.Found.Divisor.SchemeWeilOrd
import ABC3.Found.Divisor.HeightOneBridge
import ABC3.Found.Divisor.SchemeCartier
import ABC3.Found.Divisor.NormFunctor
import ABC3.Found.Divisor.NormDL
import ABC3.Found.Divisor.NormKQC
import ABC3.Found.Divisor.NormB
import ABC3.Found.Divisor.SchemeNormalCriterion
import ABC3.Found.Divisor.NormNormal
import ABC3.Found.Divisor.NormFinite
import ABC3.Found.Divisor.GlobalUnits
import ABC3.Found.Divisor.SchemeHartogs
import ABC3.Found.Divisor.NormalSections
import ABC3.Found.Divisor.NormMapBase
import ABC3.Found.Divisor.Thm62Pull
import ABC3.Found.Divisor.Thm62Hom
import ABC3.Found.Divisor.NormFF
import ABC3.Found.Divisor.SchemeOrdUnit
import ABC3.Found.Divisor.SchemeFFMap
import ABC3.Found.Divisor.NormBFunctor
import ABC3.Found.Divisor.NormCodim
import ABC3.Found.Divisor.SchemeDivFinite
import ABC3.Found.Divisor.SchemeCartierPull
import ABC3.Found.Divisor.NormPhiFunctor
import ABC3.Found.Divisor.Ex61Model
import ABC3.Found.Divisor.Ex61Units
import ABC3.Found.Divisor.Ex61RatStd
import ABC3.Found.Divisor.Ex63Types
import ABC3.Found.Divisor.Ex63Rlf
import ABC3.Found.Divisor.Ex63RatStd
import ABC3.Found.Divisor.Ex63RlfRatStd
import ABC3.Found.Divisor.Ex63RlfPic
import ABC3.Found.Divisor.Ex61Morph
import ABC3.Found.Divisor.CartierRlf
import ABC3.Found.NumberField.SepClosedIn
import ABC3.Found.NumberField.SepClosedFunctor
import ABC3.Found.NumberField.PrimeDivisorsOfValues
import ABC3.Found.NumberField.SplitCount
import ABC3.Found.NumberField.SplitInfinite
import ABC3.Found.NumberField.SplitSeparable
import ABC3.Found.NumberField.SplitExponent
import ABC3.Found.NumberField.MaxDeg
import ABC3.Found.NumberField.GaloisFaithful
import ABC3.Found.NumberField.GaloisFaithfulBase
import ABC3.Found.NumberField.GaloisFaithfulAll
import ABC3.Found.NumberField.DirichletDensity
import ABC3.Found.NumberField.DedekindEuler
import ABC3.Found.NumberField.IdealPowBound
import ABC3.Found.NumberField.LogZeta
import ABC3.Found.NumberField.PrimeDensity
import ABC3.Found.NumberField.IdealCountSplit
import ABC3.Found.NumberField.SplitDensity
import ABC3.Found.NumberField.DecompGroup
import ABC3.Found.NumberField.SplCompositum
import ABC3.Found.FrdI.Prop53Diag
import ABC3.Found.FrdI.Prop53QPhi
import ABC3.Found.FrdI.Prop53Base
import ABC3.Found.FrdI.Cor54Compat
import ABC3.Found.FrdI.Prop55PfRatFn
import ABC3.Found.FrdI.Prop53PfRlf
import ABC3.Found.FrdI.Prop55PfArb
import ABC3.Found.FrdI.Prop55PfArbStd
import ABC3.Found.FrdI.Prop55PfArbFull
import ABC3.Found.FrdI.Prop55PfArbOne
import ABC3.Found.FrdI.Prop55BiratPfFun
import ABC3.Found.FrdI.Prop55ScaleRootInv
import ABC3.Found.FrdI.Prop55CongrIso
import ABC3.Found.FrdI.Prop55ScaleRootCoa
import ABC3.Found.FrdI.Prop55ScaleRootBirat
import ABC3.Found.FrdI.Prop55PfBiratFn
import ABC3.Found.FrdI.Prop55PfRatStd
import ABC3.Found.FrdI.Prop55UnTrRatStd
import ABC3.Found.FrdI.Prop55RlfRatStd
import ABC3.Found.FrdI.Thm64Slim
import ABC3.Found.FrdI.Thm64DivSlim
import ABC3.Found.FrdI.Thm64Bundle
import ABC3.Found.FrdI.Prop55BiratOmega
import ABC3.Found.FrdI.Prop55
import ABC3.Found.FrdI.Prop55RlfNd
import ABC3.Found.FrdI.Prop55RlfRefl
import ABC3.Found.FrdI.Cor54Uniq
import ABC3.Found.FrdI.Cor54UniqIso
import ABC3.Found.FrdI.Cor54Seam
import ABC3.Found.FrdI.Cor54SeamUnTr
import ABC3.Found.FrdI.Cor54SeamCls
import ABC3.Found.FrdI.Cor54SeamSec
import ABC3.Found.FrdI.Cor54UntrSeam
import ABC3.Found.FrdI.Prop53UntrBirat
import ABC3.Found.FrdI.Prop55UntrFun
import ABC3.Found.FrdI.Prop53PfCatRoot
import ABC3.Found.FrdI.Prop53Square
import ABC3.Found.FrdI.Prop53UntrPfModel
import ABC3.Found.FrdI.Cor411Bid
import ABC3.Found.FrdI.Cor411Birat
import ABC3.Found.FrdI.Cor411BaseFn
import ABC3.Found.FrdI.Cor411Phi
import ABC3.Found.FrdI.Def24SuppIntr
import ABC3.Found.FrdI.MonoidTransport
import ABC3.Found.FrdI.Rmk451Ratstd
import ABC3.Found.FrdI.Prop44Pair
import ABC3.Found.FrdI.Thm42
import ABC3.Found.FrdI.Cor410
import ABC3.Found.FrdI.Cor411
import ABC3.Found.FrdI.Thm42Div
import ABC3.Found.FrdI.Thm42Primary
import ABC3.Found.FrdI.Thm42Prime
import ABC3.Found.FrdI.Thm42PrimeCat
import ABC3.Found.FrdI.Thm42Prop41iv
import ABC3.Found.FrdI.Thm42Prop41v
import ABC3.Found.FrdI.Thm42PsiPrime
import ABC3.Found.FrdI.Thm42DivId
import ABC3.Found.FrdI.Thm42DivMap
import ABC3.Found.FrdI.Thm42Order
import ABC3.Found.FrdI.Thm49
import ABC3.Found.FrdI.Cor410Birat
import ABC3.Found.FrdI.Thm34VBase
import ABC3.Found.FrdI.Thm34Slice
import ABC3.Found.FrdI.Thm34IvGen
import ABC3.Found.FrdI.AppA
import ABC3.Found.FrdI.Thm34Pf
import ABC3.Found.FrdI.Prop48Nf
import ABC3.Found.FrdI.Prop48Sec
import ABC3.Found.FrdI.Prop48Cpt
import ABC3.Found.FrdI.Prop48Cond3
import ABC3.Found.FrdI.Prop48Std
import ABC3.Found.FrdI.Prop48Gl
import ABC3.Found.FrdI.Rmk451
import ABC3.Found.FrdI.Rmk451Birat
import ABC3.Found.FrdI.TypeTransport
import ABC3.Found.FrdI.Prop55Std
import ABC3.Found.ProL.FinitePrimary
import ABC3.Found.ProL.Defs
import ABC3.Found.ProL.ProfiniteLimit
import ABC3.Found.ProL.LimitPi
import ABC3.Found.ProL.LPart
import ABC3.Found.ProL.Decomposition
import ABC3.Found.ProL.ZetaPow
import ABC3.Found.ProL.DivByP
import ABC3.Found.ProL.OneSubPow
import ABC3.Found.SixExp.Liouville
import ABC3.Found.SixExp.SchwarzZeros
import ABC3.Found.SixExp.Extrapolation
import ABC3.Found.SixExp.LatticeHouse
import ABC3.Found.SixExp.Counting
import ABC3.Found.SixExp.Siegel
import ABC3.Found.SixExp.LatticeGeneral
import ABC3.Found.SixExp.LatticeBox
import ABC3.Found.SixExp.Assembly
import ABC3.Found.SixExp.DenomClear
import ABC3.Found.SixExp.SiegelConst
import ABC3.Found.SixExp.Setup
import ABC3.Found.SixExp.Params
import ABC3.Found.SixExp.SiegelPoly
import ABC3.Found.SixExp.GapCore
import ABC3.Found.SixExp.ParamsGap
import ABC3.Found.SixExp.Main
import ABC3.Found.SixExp.Theorem
import ABC3.Found.SixExp.Algebraic
import ABC3.Found.SixExp.AuxFunction
import ABC3.Found.IUTchIII.LogShell
import ABC3.Found.IUTchIII.PadicLog
import ABC3.Found.IUTchIII.PowerSeriesLog
import ABC3.Found.IUTchIII.LogVolume
import ABC3.Found.IUTchIII.PadicLogMul
import ABC3.Found.SemiAnbd.TemperedGroup
import ABC3.Found.GenEll.Lemma31
import ABC3.Found.GenEll.BDClass
import ABC3.Found.GenEll.Sl2Adjoint
import ABC3.Found.GenEll.Sl2Congruence
import ABC3.Found.GenEll.Sl2Level
import ABC3.Found.GenEll.Sl2Padic
import ABC3.Found.GenEll.Elementary
import ABC3.Found.GenEll.PrimesOfSize
import ABC3.Found.GenEll.ArithDiv
import ABC3.Found.GenEll.ArithDivHom
import ABC3.Found.GenEll.ProductFormula
import ABC3.Found.GenEll.Conductor
import ABC3.Found.GenEll.LogDiff
import ABC3.Found.GenEll.LogDiffValue
import ABC3.Found.GenEll.NorthcottRat
import ABC3.Found.GenEll.InfinitePlaceRel
import ABC3.Found.GenEll.FinitePlaceRel
import ABC3.Found.GenEll.BaseChange
import ABC3.Found.GenEll.LogDiffTower
import ABC3.Found.GenEll.CartierPullback
import ABC3.Found.GenEll.MinField
import ABC3.Found.GenEll.RadicalPrincipal
import ABC3.Found.GenEll.LogDiffFinite
import ABC3.Found.GenEll.HeightADiv
import ABC3.Found.GenEll.NorthcottNF
import ABC3.Found.GenEll.OrdvIntegral
import ABC3.Found.GenEll.DenominatorBound
import ABC3.Found.GenEll.NorthcottProj
import ABC3.Found.GenEll.HeightExtension
import ABC3.Found.GenEll.NorthcottDegree
import ABC3.Found.GenEll.HeightConjugate
import ABC3.Found.GenEll.PrimeNumberTheorem
import ABC3.Found.GenEll.ProjTopology
import ABC3.Found.GenEll.IdealStalk
import ABC3.Found.GenEll.StalkPullback
import ABC3.Found.GenEll.DegMul
import ABC3.Found.GenEll.ArchPoint
import ABC3.Found.GenEll.HeightConstruction
import ABC3.Found.GenEll.HeightNonneg
import ABC3.Found.GenEll.HeightClass
import ABC3.Found.GenEll.RadicalCartier
import ABC3.Found.GenEll.StalkSupport
import ABC3.Found.GenEll.ConductorHeight
import ABC3.Found.GenEll.ArchBound
import ABC3.Found.GenEll.ProjClosed
import ABC3.Found.GenEll.CompactBound
import ABC3.Found.GenEll.ArcModel
import ABC3.Found.GenEll.ComapLocal
import ABC3.Found.GenEll.ComapStalk
import ABC3.Found.GenEll.ComapAffine
import ABC3.Found.GenEll.ComapMul
import ABC3.Found.GenEll.HeightAdditive
import ABC3.Found.GenEll.PullbackBase
import ABC3.Found.GenEll.ArchConj
import ABC3.Found.GenEll.ArchBaseChange
import ABC3.Found.GenEll.IdealADivBase
import ABC3.Found.GenEll.ArchADivBase
import ABC3.Found.GenEll.HeightBaseChange
import ABC3.Found.GenEll.PullbackNatural
import ABC3.Found.GenEll.ArchCompat
import ABC3.Found.GenEll.HeightInvariant
import ABC3.Found.GenEll.AlgPoint
import ABC3.Found.Arakelov.ArcEval
import ABC3.Found.Arakelov.ArcConjInvol
import ABC3.Found.Arakelov.ArcTopologyAffine
import ABC3.Found.Arakelov.ArcMapToAffine
import ABC3.Found.Arakelov.ArcMapCont
import ABC3.Found.Arakelov.APicWitness
import ABC3.Found.Arakelov.ADegEmb
import ABC3.Found.Arakelov.ADegBase
import ABC3.Found.Arakelov.AHeightWitness
import ABC3.Found.Arakelov.PicSpecWitness
import ABC3.Found.Arakelov.ArcTopology
import ABC3.Found.Arakelov.ArcFunctorial
import ABC3.Found.Arakelov.ArcTopologyAffineEq
import ABC3.Found.Arakelov.ArcOpenImmersion
import ABC3.Found.Arakelov.ArcBasicOpen
import ABC3.Found.Arakelov.ArcLandsIn
import ABC3.Found.Arakelov.ArcLift
import ABC3.Found.Arakelov.ArcLandsInScheme
import ABC3.Found.Arakelov.ArcAwayLift
import ABC3.Found.Arakelov.ArcOpenMap
import ABC3.Found.Arakelov.ArcSpaceInterface
import ABC3.Found.Arakelov.UltraValuation
import ABC3.Found.Arakelov.UltraPoint
import ABC3.Found.Arakelov.ChartHom
import ABC3.Found.Arakelov.UltraTransfer
import ABC3.Found.Arakelov.UltraBasic
import ABC3.Found.Arakelov.UltraCoord
import ABC3.Found.Arakelov.UltraCompact
import ABC3.Found.Arakelov.ProjModelWitness
import ABC3.Found.Arakelov.PicPresheafTensor
import ABC3.Found.Arakelov.PicSheafTensor
import ABC3.Found.Arakelov.PicRestrict
import ABC3.Found.Arakelov.PicRestrictTensor
import ABC3.Found.Arakelov.PicLocalSurj
import ABC3.Found.Arakelov.PicLocalInj
import ABC3.Found.Arakelov.PicLocality
import ABC3.Found.Arakelov.PicLocalBasis
import ABC3.Found.Arakelov.PicWhiskerW
import ABC3.Found.Arakelov.PicAssoc
import ABC3.Found.Arakelov.PicType
import ABC3.Found.Arakelov.PicLocalTrivial
import ABC3.Found.Arakelov.PicRestrictLocal
import ABC3.Found.Arakelov.PicSheafifyTrivial
import ABC3.Found.Arakelov.PicSheafGroup
import ABC3.Found.Arakelov.PicResScalarsLax
import ABC3.Found.Arakelov.PicPushLax
import ABC3.Found.Arakelov.PicPullOplax
import ABC3.Found.Arakelov.PicSchemePullback
import ABC3.Found.Arakelov.PicSchemeDelta
import ABC3.Found.Arakelov.PicDeltaColimit
import ABC3.Found.Arakelov.PicPullFree
import ABC3.Found.Arakelov.PicFreeTensor
import ABC3.Found.Arakelov.PicYonedaInf
import ABC3.Found.Arakelov.PicPullTensorFree
import ABC3.Found.Arakelov.PicColimitLift
import ABC3.Found.Arakelov.PicFreeYonedaLift
import ABC3.Found.Arakelov.PicDeltaLift
import ABC3.Found.Arakelov.PicUnitFree
import ABC3.Found.Arakelov.PicPushMu
import ABC3.Found.Arakelov.PicDeltaCalc
import ABC3.Found.Arakelov.PicUnitCalc
import ABC3.Found.Arakelov.PicGenVal
import ABC3.Found.Arakelov.PicFreeNat
import ABC3.Found.Arakelov.PicInfGen
import ABC3.Found.Arakelov.PicUnitInv
import ABC3.Found.Arakelov.PicTensorMu
import ABC3.Found.Arakelov.PicDeltaIso
import ABC3.Found.Arakelov.PicSheafPullTensor
import ABC3.Found.Arakelov.PicFreeTop
import ABC3.Found.Arakelov.PicRestrictColimit
import ABC3.Found.Arakelov.PicRestrictedPull
import ABC3.Found.Arakelov.PicBCSquare
import ABC3.Found.Arakelov.PicBCMate
import ABC3.Found.Arakelov.PicResFree
import ABC3.Found.Arakelov.PicOnFree
import ABC3.Found.Arakelov.PicResFreeIso
import ABC3.Found.Arakelov.PicUnitGen
import ABC3.Found.Arakelov.PicGenConsistent
import ABC3.Found.Arakelov.PicResGenVal
import ABC3.Found.Arakelov.PicBCMateIso
import ABC3.Found.Arakelov.PicBCIso
import ABC3.Found.Arakelov.PicFreeTerm
import ABC3.Found.Arakelov.PicUnitOn
import ABC3.Found.Arakelov.PicResTrans
import ABC3.Found.Arakelov.PicSieveTransport
import ABC3.Found.Arakelov.PicLTPull
import ABC3.Found.Arakelov.PicPullTensorFinal
import ABC3.Found.Arakelov.PicInvPull
import ABC3.Found.Arakelov.PicPullGroup
import ABC3.Found.Arakelov.PicTildeStock
import ABC3.Found.Arakelov.PicTildeAdj
import ABC3.Found.Arakelov.PicTildeUnit
import ABC3.Found.Arakelov.PicGammaSections
import ABC3.Found.Arakelov.PicGammaSpecIso
import ABC3.Found.Arakelov.PicGammaUnit
import ABC3.Found.Arakelov.PicBaseTensor
import ABC3.Found.Arakelov.PicGammaStruct
import ABC3.Found.Arakelov.PicSectionTrivial
import ABC3.Found.Arakelov.PicInvTrivial
import ABC3.Found.Arakelov.PicInterface
import ABC3.Found.Arakelov.PicGammaTensor
import ABC3.Found.Arakelov.PicTildeTensor
import ABC3.Found.Arakelov.PicAwayFree
import ABC3.Found.Arakelov.PicStalkIso
import ABC3.Found.Arakelov.PicTildeStalk
import ABC3.Found.Arakelov.PicLocTensor
import ABC3.Found.Arakelov.PicTensorFrac
import ABC3.Found.Arakelov.PicTensorSection
import ABC3.Found.Arakelov.PicTildePre
import ABC3.Found.Arakelov.PicTildeDesc
import ABC3.Found.Arakelov.PicAwaySection
import ABC3.Found.Arakelov.PicTensorUniq
import ABC3.Found.Arakelov.PicConstSection
import ABC3.Found.Arakelov.PicBridge
import ABC3.Found.Arakelov.PicAwayIso
import ABC3.Found.Arakelov.PicStalkBasis
import ABC3.Found.Arakelov.PicTildeTensorIso
import ABC3.Found.Arakelov.PicTildeInv
import ABC3.Found.Arakelov.PicUnitHom
import ABC3.Found.Arakelov.PicAwayTrans
import ABC3.Found.Arakelov.PicAwayTower
import ABC3.Found.Arakelov.PicAwayLoc
import ABC3.Found.Arakelov.PicAwayUnit
import ABC3.Found.Arakelov.PicAwayModule
import ABC3.Found.Arakelov.PicAwayFreeProp
import ABC3.Found.Arakelov.PicAwayFreeIso
import ABC3.Found.Arakelov.PicLocalBij
import ABC3.Found.Arakelov.PicCoverIso
import ABC3.Found.Arakelov.PicGenMul
import ABC3.Found.Arakelov.PicUnitApp
import ABC3.Found.Arakelov.PicFreeUnique
import ABC3.Found.Arakelov.PicFreeDescBij
import ABC3.Found.Arakelov.PicUnitBij
import ABC3.Found.Arakelov.PicUnitSecBij
import ABC3.Found.Arakelov.PicModCoverIso
import ABC3.Found.Arakelov.PicTrivialIso
import ABC3.Found.Arakelov.PicTrivialSheaf
import ABC3.Found.Arakelov.PicMapBij
import ABC3.Found.Arakelov.PicGenSection
import ABC3.Found.Arakelov.PicPresieveBij
import ABC3.Found.Arakelov.PicPresieveIso
import ABC3.Found.Arakelov.PicOverCover
import ABC3.Found.Arakelov.PicBasicCover
import ABC3.Found.Arakelov.PicToOpenRes
import ABC3.Found.Arakelov.PicSecUnit
import ABC3.Found.Arakelov.PicResSquare
import ABC3.Found.Arakelov.PicPresheafId
import ABC3.Found.Arakelov.PicOverPresieve
import ABC3.Found.Arakelov.PicLocGen
import ABC3.Found.Arakelov.PicAwayScalar
import ABC3.Found.Arakelov.PicAwayLin
import ABC3.Found.Arakelov.PicAwayTransport
import ABC3.Found.Arakelov.PicSectionEquiv
import ABC3.Found.Arakelov.PicPointwise
import ABC3.Found.Arakelov.PicSecLocMod
import ABC3.Found.Arakelov.PicLiftGen
import ABC3.Found.Arakelov.PicResGen
import ABC3.Found.Arakelov.PicTildeLocTrivial
import ABC3.Found.Arakelov.PicInvOfModule
import ABC3.Found.Arakelov.PicBasicTrivial
import ABC3.Found.Arakelov.PicFiniteCover
import ABC3.Found.Arakelov.PicSpecRes
import ABC3.Found.Arakelov.PicSecRes
import ABC3.Found.Arakelov.PicCoverUnit
import ABC3.Found.Arakelov.PicSmulSurj
import ABC3.Found.Arakelov.PicLocEq
import ABC3.Found.Arakelov.PicSecMap
import ABC3.Found.Arakelov.PicLocSurj
import ABC3.Found.Arakelov.PicQCoh
import ABC3.Found.Arakelov.PicGammaInv
import ABC3.Found.Arakelov.PicEquivRing
import ABC3.Found.Arakelov.PicWitness
import ABC3.Found.Arakelov.PicSpecWitness
import ABC3.Found.Arakelov.PicIdealSec
import ABC3.Found.Arakelov.PicIdealPre
import ABC3.Found.Arakelov.PicIdealLocal
import ABC3.Found.Arakelov.PicIdealSheaf
import ABC3.Found.Arakelov.PicIdealBO
import ABC3.Found.Arakelov.PicIdealLoc
import ABC3.Found.Arakelov.PicIdealFree
import ABC3.Found.Arakelov.PicAffCover
import ABC3.Found.Arakelov.PicIdealAway
import ABC3.Found.Arakelov.PicIdealScal
import ABC3.Found.Arakelov.PicIdealBij
import ABC3.Found.Arakelov.PicIdealRes
import ABC3.Found.Arakelov.PicIdealSq
import ABC3.Found.Arakelov.PicMulCover
import ABC3.Found.Arakelov.PicIdealLT
import ABC3.Found.Arakelov.PicUnitMul
import ABC3.Found.Arakelov.PicUnitEnd
import ABC3.Found.Arakelov.PicUnitSect
import ABC3.Found.Arakelov.PicUnitRing
import ABC3.Found.Arakelov.PicDualSmul
import ABC3.Found.Arakelov.PicUnitRes
import ABC3.Found.Arakelov.PicDualPre
import ABC3.Found.Arakelov.PicTrivialNoSheaf
import ABC3.Found.Arakelov.PicDualTrivial
import ABC3.Found.Arakelov.PicUnitVal
import ABC3.Found.Arakelov.PicFVal
import ABC3.Found.Arakelov.PicEvalBil
import ABC3.Found.Arakelov.PicEvalHom
import ABC3.Found.Arakelov.PicDualGlue
import ABC3.Found.Arakelov.PicDualVal
import ABC3.Found.Arakelov.PicDualHom
import ABC3.Found.Arakelov.PicDualSheaf
import ABC3.Found.Arakelov.PicDualModules
import ABC3.Found.Arakelov.PicEvalBij
import ABC3.Found.Arakelov.PicEvalIso
import ABC3.Found.Arakelov.PicIdealBase
import ABC3.Found.Arakelov.PicIdealFlat
import ABC3.Found.Arakelov.PicIdealMul
import ABC3.Found.Arakelov.PicDivisor
import ABC3.Found.Arakelov.PicDivisorTop
import ABC3.Found.Arakelov.PicIdealMulHom
import ABC3.Found.Arakelov.PicAffineSieve
import ABC3.Found.Arakelov.PicDivisorMul
import ABC3.Found.Arakelov.PicPrincipalRing
import ABC3.Found.Arakelov.PicPrincipalAffine
import ABC3.Found.Arakelov.PicPushoutKer
import ABC3.Found.Arakelov.PicComapAffine
import ABC3.Found.Arakelov.PicIdealLTPt
import ABC3.Found.Arakelov.PicBaseChange
import ABC3.Found.Arakelov.PicLocalGlobal
import ABC3.Found.Arakelov.PicComapIso
import ABC3.Found.Arakelov.PicCartierPt
import ABC3.Found.Arakelov.PicFromSpecTransport
import ABC3.Found.Arakelov.PicCartierComap
import ABC3.Found.Arakelov.PicSubschemeVanish
import ABC3.Found.Arakelov.PicSectionPull
import ABC3.Found.Arakelov.PicPullIdealHom
import ABC3.Found.Arakelov.PicSurjIso
import ABC3.Found.Arakelov.PicPushAdj
import ABC3.Found.Arakelov.PicPullImage
import ABC3.Found.Arakelov.PicComapImage
import ABC3.Found.GaloisRep.OmegaNum
import ABC3.Found.GaloisRep.OmegaMap
import ABC3.Found.Arakelov.PicImgClosure
import ABC3.Found.Arakelov.PicAppLESec
import ABC3.Found.Arakelov.PicAppTopSplit
import ABC3.Found.Arakelov.PicFromSpecApp
import ABC3.Found.Arakelov.PicAppIsoVal
import ABC3.Found.Arakelov.PicPullSurj
import ABC3.Found.Arakelov.PicIdealTransport
import ABC3.Found.Arakelov.PicComapPair
import ABC3.Found.Arakelov.PicSurjPair
import ABC3.Found.Arakelov.PicGammaAppIso
import ABC3.Found.Arakelov.PicResIso
import ABC3.Found.Arakelov.PicAppIsoInv
import ABC3.Found.Arakelov.PicCongrApp
import ABC3.Found.Arakelov.PicSquareLE
import ABC3.Found.Arakelov.PicHcompat
import ABC3.Found.Arakelov.PicSpecMapLE
import ABC3.Found.Arakelov.PicPreCoord
import ABC3.Found.Arakelov.PicHcompatTop
import ABC3.Found.Arakelov.PicAppIsoAsLE
import ABC3.Found.GaloisRep.UniversalCurve
import ABC3.Found.GaloisRep.OmegaBase
import ABC3.Found.GaloisRep.ModTwo
import ABC3.Found.GaloisRep.CharTwo
import ABC3.Found.GaloisRep.PsiCompMul
import ABC3.Found.GaloisRep.OmegaMulPsi
import ABC3.Found.GaloisRep.PsiRec
import ABC3.Found.GaloisRep.OmegaOne
import ABC3.Found.GaloisRep.OmegaIdentity
import ABC3.Found.GaloisRep.BInvChar2
import ABC3.Found.GaloisRep.Psi3Char2
import ABC3.Found.GaloisRep.PreP4Char2
import ABC3.Found.GaloisRep.OmegaTwo
import ABC3.Found.GaloisRep.OmegaCharForm
import ABC3.Found.GaloisRep.PreP4Frob
import ABC3.Found.GaloisRep.OmegaThree
import ABC3.Found.GaloisRep.UniversalF2
import ABC3.Found.GaloisRep.OmegaFour
import ABC3.Found.GaloisRep.OmegaDescent
import ABC3.Found.GaloisRep.EdsTarget
import ABC3.Found.GaloisRep.EdsEvenStep
import ABC3.Found.GaloisRep.EdsOddStep
import ABC3.Found.GaloisRep.EdsAll
import ABC3.Found.GaloisRep.OmegaAll
import ABC3.Found.GaloisRep.OmegaDef
import ABC3.Found.GaloisRep.OmegaCurve
import ABC3.Found.GaloisRep.Psi2Eval
import ABC3.Found.GaloisRep.Doubling
import ABC3.Found.GaloisRep.TwoTorsion
import ABC3.Found.GaloisRep.TwoTorsionCoord
import ABC3.Found.GaloisRep.FiniteTwoTorsion
import ABC3.Found.GaloisRep.FiniteY
import ABC3.Found.GaloisRep.FiniteTorsion
import ABC3.Found.GaloisRep.ThreeTorsion
import ABC3.Found.GaloisRep.CoprimeTorsion
import ABC3.Found.GaloisRep.TorsionMul
import ABC3.Found.GaloisRep.FourTorsion
import ABC3.Found.GaloisRep.CrossIdentity
import ABC3.Found.GaloisRep.PhiCases
import ABC3.Found.GaloisRep.PhiDegenerate
import ABC3.Found.GaloisRep.PhiCaseB
import ABC3.Found.GaloisRep.XDiff
import ABC3.Found.GaloisRep.PsiDouble
import ABC3.Found.GaloisRep.MulFormula
import ABC3.Found.GaloisRep.EdsSomos
import ABC3.Found.GaloisRep.PhiCross
import ABC3.Found.GaloisRep.YSide
import ABC3.Found.GaloisRep.NonDegen
import ABC3.Found.GaloisRep.XYStep
import ABC3.Found.GaloisRep.MulPoint
import ABC3.Found.GaloisRep.MulOrder
import ABC3.Found.GaloisRep.TorsionAll
import ABC3.Found.GaloisRep.Wronskian
import ABC3.Found.GaloisRep.EdsLambda
import ABC3.Found.GaloisRep.EdsIdentity
import ABC3.Found.GaloisRep.EdsWard
import ABC3.Found.GaloisRep.Coprime23
import ABC3.Found.GaloisRep.ZeroSet
import ABC3.Found.GaloisRep.CoprimePhiPSq
import ABC3.Found.GaloisRep.AlgClosedPoint
import ABC3.Found.GaloisRep.SepRoots
import ABC3.Found.GaloisRep.GoodBase
import ABC3.Found.GaloisRep.TorsionCount
import ABC3.Found.GaloisRep.TorsionCard
import ABC3.Found.GaloisRep.TorsionGroup
import ABC3.Found.GaloisRep.PrimePowerStep
import ABC3.Found.GaloisRep.PrimePowerEquiv
import ABC3.Found.GaloisRep.CrtStep
import ABC3.Found.GaloisRep.ZmodSqEquiv
import ABC3.Found.GaloisRep.TorsionStructure
import ABC3.Found.GaloisRep.TowerLift
import ABC3.Found.GaloisRep.IndepTower
import ABC3.Found.GaloisRep.PadicLimit
import ABC3.Found.GaloisRep.TateLimit
import ABC3.Found.GaloisRep.TateWitness
import ABC3.Found.GaloisRep.PadicLinear
import ABC3.Found.GaloisRep.GalRep
import ABC3.Found.GaloisRep.GalRepWitness
import ABC3.Found.GaloisRep.ModLWitness
import ABC3.Found.GaloisRep.TateSeries
import ABC3.Found.GaloisRep.AdicEval
import ABC3.Found.GaloisRep.TateSpecialize
import ABC3.Found.GaloisRep.TateDelta
import ABC3.Found.GaloisRep.TateUnit
import ABC3.Found.GaloisRep.TateJ
import ABC3.Found.GaloisRep.TateInvert
import ABC3.Found.GaloisRep.TateNonDeg
import ABC3.Found.GaloisRep.AdicContraction
import ABC3.Found.GaloisRep.QTorsion
import ABC3.Found.GaloisRep.AdicSeries
import ABC3.Found.GaloisRep.TateXY
import ABC3.Found.GaloisRep.QDomain
import ABC3.Found.GaloisRep.TatePair
import ABC3.Found.GaloisRep.TateExpand
import ABC3.Found.GaloisRep.AdicFubini
import ABC3.Found.GaloisRep.TateQExp
import ABC3.Found.GaloisRep.TateSigma
import ABC3.Found.GaloisRep.AdicMul
import ABC3.Found.GaloisRep.TorsionIdeal
import ABC3.Found.GaloisRep.GenericPoint
import ABC3.Found.GaloisRep.Translate
import ABC3.Found.GaloisRep.Transcendence
import ABC3.Found.GaloisRep.TranslateAut
import ABC3.Found.GaloisRep.PointHom
import ABC3.Found.GaloisRep.FieldHomExt
import ABC3.Found.GaloisRep.TranslateEquiv
import ABC3.Found.GaloisRep.TranslateComp
import ABC3.Found.GaloisRep.TwoTorsionDecomp
import ABC3.Found.GaloisRep.NotTwoTorsionPoint
import ABC3.Found.GaloisRep.TranslateAutAll
import ABC3.Found.GaloisRep.GenericNotTorsion
import ABC3.Found.GaloisRep.TorsionIdealIntegral
import ABC3.Found.GaloisRep.CoordinateDimension
import ABC3.Found.GaloisRep.CoordinateUnits
import ABC3.Found.GaloisRep.SquareCompletion
import ABC3.Found.GaloisRep.TwoTorsionDiscr
import ABC3.Found.GaloisRep.Psi2SqSquarefree
import ABC3.Found.GaloisRep.LocalStructure
import ABC3.Found.GaloisRep.UnramifiedStructure
import ABC3.Found.GaloisRep.PrimeOverX
import ABC3.Found.GaloisRep.PrimeGenerators
import ABC3.Found.GaloisRep.LocalPrincipal
import ABC3.Found.GaloisRep.Dedekind
import ABC3.Found.GaloisRep.PointSpectrum
import ABC3.Found.GaloisRep.RootFromIdeal
import ABC3.Found.GaloisRep.DivisorTools
import ABC3.Found.GaloisRep.PullbackAlg
import ABC3.Found.GaloisRep.CountPow
import ABC3.Found.GaloisRep.ValuationCount
import ABC3.Found.GaloisRep.ValuationInfty
import ABC3.Found.GaloisRep.ValuationEven
import ABC3.Found.GaloisRep.ValuationBasis
import ABC3.Found.GaloisRep.HyperInv
import ABC3.Found.GaloisRep.HyperInvValuation
import ABC3.Found.GaloisRep.DvdCount
import ABC3.Found.GaloisRep.FiberSum
import ABC3.Found.GaloisRep.Support
import ABC3.Found.GaloisRep.Reduction
import ABC3.Found.GaloisRep.RedConst
import ABC3.Found.GaloisRep.RedPoint
import ABC3.Found.GaloisRep.RedFormula
import ABC3.Found.GaloisRep.RedSlope
import ABC3.Found.GaloisRep.SlopeIdent
import ABC3.Found.GaloisRep.RedAdd
import ABC3.Found.GaloisRep.RedZero
import ABC3.Found.GaloisRep.RedHom
import ABC3.Found.GaloisRep.Infinity
import ABC3.Found.GaloisRep.InfinityKer
import ABC3.Found.GaloisRep.RedKernel
import ABC3.Found.GaloisRep.PullbackPoint
import ABC3.Found.GaloisRep.RootUnit
import ABC3.Found.GaloisRep.ClassSum
import ABC3.Found.GaloisRep.CurveHomVal
import ABC3.Found.GaloisRep.AutInvariant
import ABC3.Found.GaloisRep.PlaceTransport
import ABC3.Found.GaloisRep.TranslateCount
import ABC3.Found.GaloisRep.FiberConst
import ABC3.Found.GaloisRep.PointPlace
import ABC3.Found.GaloisRep.SupportSum
import ABC3.Found.GaloisRep.D2Principal
import ABC3.Found.GaloisRep.D2Bridge
import ABC3.Found.GaloisRep.RootOfUnity
import ABC3.Found.GaloisRep.WeilWellDef
import ABC3.Found.GaloisRep.WeilVal
import ABC3.Found.GaloisRep.WeilExist
import ABC3.Found.GaloisRep.MulByNInj
import ABC3.Found.GaloisRep.WeilBilin
import ABC3.Found.GaloisRep.AddRelation
import ABC3.Found.GaloisRep.WeilBilinCore
import ABC3.Found.GaloisRep.WeilMul
import ABC3.Found.GaloisRep.CountFP
import ABC3.Found.GaloisRep.Divisible
import ABC3.Found.GaloisRep.CountInfty
import ABC3.Found.GaloisRep.TranslateProd
import ABC3.Found.GaloisRep.MuComm
import ABC3.Found.GaloisRep.WeilAlt
import ABC3.Found.GaloisRep.WeilCharZero
import ABC3.Found.GaloisRep.SemiLinear
import ABC3.Found.GaloisRep.WeilGalois
import ABC3.Found.GaloisRep.WeilGalPoint
import ABC3.Found.GaloisRep.WeilBilinFull
import ABC3.Found.GaloisRep.TorsionAction
import ABC3.Found.GaloisRep.NondegStep
import ABC3.Found.GaloisRep.PhiDegree
import ABC3.Found.GaloisRep.PhiTwo
import ABC3.Found.GaloisRep.KummerX
import ABC3.Found.GaloisRep.KummerPoint
import ABC3.Found.GaloisRep.LadderThree
import ABC3.Found.GaloisRep.WeilDet
import ABC3.Found.GaloisRep.CyclotomicStep
import ABC3.Found.GaloisRep.TateWiring
import ABC3.Found.GaloisRep.DetWiring
import ABC3.Found.GaloisRep.DetCyclotomic
import ABC3.Found.GaloisRep.TowerSurj
import ABC3.Found.GaloisRep.TateSurj
import ABC3.Found.GaloisRep.BasisFree
import ABC3.Found.GaloisRep.TateAnalytic
import ABC3.Found.GaloisRep.TateEquationMod
import ABC3.Found.GaloisRep.TateClassMap
import ABC3.Found.GaloisRep.LipschitzBridge
import ABC3.Found.GaloisRep.LatticeInvariant
import ABC3.Found.GaloisRep.LipschitzRows
import ABC3.Found.GaloisRep.WeierstrassRows
import ABC3.Found.GaloisRep.WeierstrassQExp
import ABC3.Found.GaloisRep.DerivWeierstrassQExp
import ABC3.Found.GaloisRep.TateEquationAnalytic
import ABC3.Found.GaloisRep.TateFunctorial
import ABC3.Found.GaloisRep.TateTruncate
import ABC3.Found.GaloisRep.TateUniversal
import ABC3.Found.GaloisRep.TateDivisibility
import ABC3.Found.GaloisRep.TateComplexSpec
import ABC3.Found.GaloisRep.TateSplitNat
import ABC3.Found.GaloisRep.TateTailBound
import ABC3.Found.GaloisRep.TateDoubleSum
import ABC3.Found.GaloisRep.TateSigmaComplex
import ABC3.Found.GaloisRep.TateSigmaTail
import ABC3.Found.GaloisRep.TateAnalyticTrunc
import ABC3.Found.GaloisRep.TateUWBridge
import ABC3.Found.GaloisRep.TateCoeffTail
import ABC3.Found.GaloisRep.TateBounds
import ABC3.Found.GaloisRep.TateDefectBound
import ABC3.Found.GaloisRep.PolyVanish
import ABC3.Found.GaloisRep.TateUWFree
import ABC3.Found.GaloisRep.TateCoeffVanish
import ABC3.Found.GaloisRep.TateDescent
import ABC3.Found.GaloisRep.TateEquation
import ABC3.Found.GaloisRep.EllipticLiouville
import ABC3.Found.GaloisRep.EllipticConst
import ABC3.Found.GaloisRep.WeierstrassPole
import ABC3.Found.GaloisRep.WeierstrassPoleForm
import ABC3.Found.GaloisRep.WeierstrassQuotient
import ABC3.Found.GaloisRep.CollinearDet
import ABC3.Found.GaloisRep.RemovableGlue
import ABC3.Found.GaloisRep.WeierstrassAddition
import ABC3.Found.GaloisRep.TateCollinearAnalytic
import ABC3.Found.GaloisRep.TateCollinearTrunc
import ABC3.Found.GaloisRep.CollUniversal
import ABC3.Found.GaloisRep.CollDivisibility
import ABC3.Found.Arakelov.PicUnfoldLE
import ABC3.Found.Arakelov.PicSquareGen
import ABC3.Found.Arakelov.PicPredSieve
import ABC3.Found.Arakelov.PicTrivRestrict
import ABC3.Found.Arakelov.PicBijGood
import ABC3.Found.Arakelov.PicGoodOpen
import ABC3.Found.Arakelov.PicCartierWitness
import ABC3.Found.Arakelov.ArcFiber
import ABC3.Found.Arakelov.ArcMetric
import ABC3.Found.Arakelov.ArcPointScheme
import ABC3.Found.Arakelov.ArcTrivNorm
import ABC3.Found.Arakelov.ArcContCriterion
import ABC3.Found.Arakelov.ArcEvalNat
import ABC3.Found.Arakelov.ArcUnitEval
import ABC3.Found.Arakelov.ArcEvalGlobal
import ABC3.Found.Arakelov.ArcTrivMetric
import ABC3.Found.Arakelov.ArcRestrNorm
import ABC3.Found.Arakelov.ArcOverBridge
import ABC3.Found.Arakelov.ArcEvalOn
import ABC3.Found.Arakelov.ArcGenNorm
import ABC3.Found.Arakelov.ArcSemilinear
import ABC3.Found.Arakelov.ArcLiftOpen
import ABC3.Found.Arakelov.ArcEvalCont
import ABC3.Found.Arakelov.ArcLocalMetric
import ABC3.Found.Arakelov.ArcGlue
import ABC3.Found.Arakelov.ArcGlueZero
import ABC3.Found.Arakelov.ArcGenSection
import ABC3.Found.Arakelov.ArcOverCoef
import ABC3.Found.Arakelov.ArcBridgeSmul
import ABC3.Found.Arakelov.ArcAppIsoNat
import ABC3.Found.Arakelov.ArcBridgeNat
import ABC3.Found.Arakelov.ArcBridgeIso
import ABC3.Found.Arakelov.ArcLocalDirect
import ABC3.Found.Arakelov.ArcXNorm
import ABC3.Found.Arakelov.ArcGlueX
import ABC3.Found.Arakelov.ArcGlueCont
import ABC3.Found.Arakelov.ArcOpenSetOpen
import ABC3.Found.Arakelov.ArcEmbedding
import ABC3.Found.Arakelov.ArcContTransport
import ABC3.Found.Arakelov.ArcXNormVia
import ABC3.Found.Arakelov.ArcUnitComp
import ABC3.Found.Arakelov.ArcGammaEval
import ABC3.Found.Arakelov.ArcRestrUnit
import ABC3.Found.Arakelov.ArcFactorEval
import ABC3.Found.Arakelov.ArcSectionCont
import ABC3.Found.Arakelov.ArcContMetric
import ABC3.Found.Arakelov.ArcCoverPou
import ABC3.Found.Arakelov.ArcMetricExists
import ABC3.Found.Arakelov.ArcScaleNorm
import ABC3.Found.Arakelov.ArcUnitCoord
import ABC3.Found.Arakelov.ArcFiberDim
import ABC3.Found.Arakelov.ArcRatio
import ABC3.Found.Arakelov.ArcLogMetric
import ABC3.Found.Arakelov.ArcPouPull
import ABC3.Found.Arakelov.ArcGreenMetric
import ABC3.Found.Arakelov.ArcGreenConj
import ABC3.Found.Arakelov.ArcTorsorMetric
import ABC3.Found.Arakelov.ArcMetricWitness
import ABC3.Found.Arakelov.PicDivisorPull
import ABC3.Found.Arakelov.PicHcompatImg
import ABC3.Found.Arakelov.PicHcompatPre
import ABC3.Found.Arakelov.PicAppLEApply
import ABC3.Found.Arakelov.PicComapChain
import ABC3.Found.Arakelov.PicUnitSurj
import ABC3.Found.Arakelov.PicPrincipal
import ABC3.Found.GenEll.UPoint
import ABC3.Found.GenEll.HeightInterface
import ABC3.Found.GenEll.DegSubset
import ABC3.Found.GenEll.Prop16
import ABC3.Found.GenEll.NorthcottClassical
import ABC3.Found.NCBelyi.Separation
import ABC3.Found.NCBelyi.Lemma21
import ABC3.Found.NCBelyi.BelyiComp
import ABC3.Found.NCBelyi.Normalize
/-!
# Found — 実装済みの基礎

Track B。`Interface` の `structure` を本物にする場所。**`sorry` を残さない。**
mathlib へ PR できる品質で書く——IUT の当否に関わらず残る成果になる。
-/
