import ABC3.Meta.Claim
import Mathlib.Data.Real.Basic
import Mathlib.Data.Set.Finite.Basic

/-!
# [GenEll] §1 —— 高さの理論の語彙(`Interface`)

原典: S. Mochizuki, *Arithmetic Elliptic Curves in General Position* [GenEll]、
物理 p.3–p.10。**260 dpi 目視確認 2026-08-16**(p.3・p.5・p.6・p.8・p.9・p.10)。

原文 (GenEll p.3):
> There is an evident notion of tensor product of arithmetic line bundles on X. The

## ★★何を posit し、何を posit しないか

★**posit するのは「語彙」だけである**——型と写像、すなわち
`X(ℚ̄)`・`APic(X)`・`ht`・`log-diff`・`log-cond`・ample 性。

★★**`Proposition 1.4` / `1.6` / `1.7` の結論は入れない。**
入れれば `Skeleton` の `sorry` は消えるが、それは `tools/check.mjs` 冒頭 B5 が
名指しする穴——**条件を posit して `sorry` を消しても進捗ではない**——そのものである。
本ファイルは**公理を 1 つも持たない**(データと述語だけ)ので、その穴に落ちようがない。

## ★mathlib 実測(2026-08-16)

| 語 | mathlib |
|---|---|
| `Arakelov` | ★**0 件** |
| `arithmetic line bundle` | ★**0 件** |
| `LineBundle` | ★**0 件** |
| `Scheme…Picard` | ★**0 件** |
| `analytification` / `GAGA` / `complex analytic space` | ★**0 件** |

★したがって `APic(X)` も `X^arc` も**この Interface が受けるほかない**。

## ★★ただし §1 全体が「無い理論」なのではない

★**`ADiv(F)` と正規化次数 `deg`(下線つき)は既に作ってある**——
`Found/GenEll/ArithDiv.lean`(`sorry` 無し、`ADiv` / `deg` / `degNormalized` /
`principalADiv` / `APrc`)。`Definition 1.5, (iii)(iv)` の `log-diff` / `log-cond` は
**その上に直接立つ**。ゆえに §1 の境界は「Arakelov 理論か否か」ではなく、
★**`X^arc`(複素解析空間)を要求するか否か**である。

- 要求する: `Definition 1.1`・`Example 1.3, (ii)`・`Proposition 1.6` のアルキメデス側
- 要求しない: `Example 1.3, (i)`・`Definition 1.5` の算術因子側・`Proposition 1.7` の証明の核
-/

namespace ABC3.Interface.GenEll

open ABC3.Meta

/-- **[GenEll] §1 の語彙**を受ける `Interface`。

★フィールドはすべて**原文 §1 に実際に現れる語**と 1 対 1 に対応する。
現れない語は入れていない(仮説の強化を避けるため——G5)。

★**述語 `Ample` / `SomePowerGlobGen` は「性質」であって「公理」ではない**。
これらが何を満たすかは一切 posit していないので、
`Proposition 1.4, (ii)(iv)` は本当に未証明のまま残る。 -/
structure HeightTheoryData where
  /-- `X(ℚ̄)` —— `X` の `ℚ̄` 値点。 -/
  Point : Type
  /-- `APic(X)` の代表 —— `X` 上の算術直線束 `L̄ = (L, |−|_L)`。 -/
  ABundle : Type
  /-- `X` 上の**有効 Cartier 因子** `D`。 -/
  Divisor : Type
  /-- `X_ℚ` 上の直線束 `L_ℚ` の同型類。★`Proposition 1.4, (iii)` はここに落ちる。 -/
  GenericClass : Type
  /-- 原文「There is an evident notion of tensor product of arithmetic line bundles on X」。 -/
  tensor : ABundle → ABundle → ABundle
  /-- 原文 `ht_M̄ : X(ℚ̄) → ℝ`(`Definition 1.2, (i)`)。 -/
  ht : ABundle → Point → ℝ
  /-- `L̄ ↦ L_ℚ`(`Proposition 1.4` の `L_ℚ ≝ L|_{X_ℚ}`)。 -/
  generic : ABundle → GenericClass
  /-- 原文「the line bundle `L_ℚ` is **ample**」。 -/
  Ample : GenericClass → Prop
  /-- 原文「some positive tensor power of the line bundle `L_ℚ` on `X_ℚ` is
  **generated by global sections**」。 -/
  SomePowerGlobGen : GenericClass → Prop
  /-- 原文 `X(ℚ̄)^{≤d}`(`Example 1.3, (i)`)。 -/
  degLe : ℕ → Set Point
  /-- `D ↦ O_X(D)`(`Proposition 1.6` の `L = O_X(D)`)。 -/
  bundleOf : Divisor → ABundle
  /-- `D ↦ U(ℚ̄)` ただし `U ≝ X\D`(`Definition 1.5, (iv)` / `Proposition 1.6`)。 -/
  compl : Divisor → Set Point
  /-- 原文 `log-diff_X : X(ℚ̄) → ℝ`(`Definition 1.5, (iii)`)。 -/
  logDiff : Point → ℝ
  /-- 原文 `log-cond_D : U_X(ℚ̄) → ℝ`(`Definition 1.5, (iv)`)。 -/
  logCond : Divisor → Point → ℝ
  /-- 原文「a nonempty `ι_X`-stable **compact domain**」から作られる
  **compactly bounded subset**(`Example 1.3, (ii)`)。
  ★これは `X^arc` を要求するので posit するほかない。 -/
  CompactlyBounded : Set Point → Prop

/-- ★**Track B は何を作らねばならないか。**

★`waiting` を書く(非空虚 witness ではなく)。本構造体は公理を 1 つも持たないので
「無矛盾です」と言っても情報がない——**言うべきなのは「まだ作っていない」の中身**である。 -/
def HeightTheoryData.waiting : WaitingFor :=
  { what := "算術直線束 APic(X) とエルミート計量、複素解析空間 X^arc(= X(ℂ) と複素共役 ι_X)、および高さ関数 ht_L̄ の構成。mathlib に Arakelov / arithmetic line bundle / LineBundle / Scheme…Picard / analytification / GAGA / complex analytic space はいずれも 0 件(2026-08-16、ディレクトリ全宣言を確認)"
    trackB := "Found/GenEll — ★実装済み: ADiv(F) と正規化次数 deg(ArithDiv.lean)、および **差積イデアル → ADiv(F)**(LogDiff.lean、2026-08-17。mathlib の IsDedekindDomain.differentIdeal と Associates.finite_factors の上に載った)。★残るのは (a) X^arc の複素解析側、(b) Cartier 因子の Spec(O_F) への引き戻し。★★律速は (a) である——複素解析空間の理論そのものが mathlib に無く、着手の形跡も無い(2026-08-16 実測)" }

/-- **`Proposition 1.7` の被覆の設定**を受ける `Interface`。

原文 (GenEll p.9):
> be a generically finite morphism of normal, Z-proper, Z-flat schemes of dimension two.

★★**なぜ条件 (a)–(d) を 1 つの不透明な `Prop` にするのか。**

原文の条件は「`D_ℚ`, `E_ℚ` が reduced」「`D_ℚ = φ_ℚ^{-1}(E_ℚ)_red`」
「`φ_ℚ` が有限**エタール**」「分岐指数が `e` を割る」——**すべて scheme 論の語彙**であり、
`HeightTheoryData` は点と高さしか持たないので展開できない。

★**ここで条件を落とすことは許されない**——落とせば主張が強くなり、G5(主張の弱化禁止)の
裏返しで**偽の skeleton** になる。ゆえに「展開できないが落とさない」唯一の書き方として、
条件を **1 つの `Prop` フィールドとして持ち、定理の仮定に置く**。
★この手当ては `prop_1_7.needs` に `.implicitStep` として明記してある。 -/
structure CoveringSetup where
  /-- 被覆の側 `Y`。 -/
  DY : HeightTheoryData
  /-- 底の側 `Z`。 -/
  DZ : HeightTheoryData
  /-- `φ : Y → Z` が `ℚ̄` 値点に誘導する写像。 -/
  toPoint : DY.Point → DZ.Point
  /-- `D ⊆ Y`。 -/
  divY : DY.Divisor
  /-- `E ⊆ Z`。 -/
  divZ : DZ.Divisor
  /-- 原文「Let `e` be a positive integer」。 -/
  e : ℕ
  /-- `e` は正。 -/
  e_pos : 0 < e
  /-- 原文の条件 (a)(b)(c)(d) と「生成的有限射・正規・ℤ-固有・ℤ-平坦・次元 2」。
  ★**不透明な 1 つの述語として持つ**(上の docstring を参照)。 -/
  hyp : Prop
  /-- 原文「`φ_ℚ` restricts to a finite étale morphism `(U_Y)_ℚ → (U_Z)_ℚ`」の
  点レベルの帰結——`U_Y(ℚ̄)` は `U_Z(ℚ̄)` へ写る。 -/
  maps_compl : ∀ x ∈ DY.compl divY, toPoint x ∈ DZ.compl divZ

/-- ★Track B は何を作らねばならないか。 -/
def CoveringSetup.waiting : WaitingFor :=
  { what := "次元 2 の正規・ℤ-固有・ℤ-平坦スキームの生成的有限射と、その分岐指数・エタール性・(−)_red。★`hyp` を不透明な Prop のままにしているのは『展開できないが落とさない』ためであり、展開が Track B の仕事である"
    trackB := "Found/GenEll — mathlib は `IsEtale` / `Ideal.ramificationIdx` / `IsDedekindDomain.differentIdeal` を持つので、**scheme の言葉に持ち上げる前に環の言葉で書ける可能性がある**。原文 p.10 の証明の核も局所体の分岐理論と Kummer 理論だけである(2026-08-16 目視)" }

/-! ## ★出典の紐付け(`.src`) -/

def HeightTheoryData.src : Source :=
  { paper := "GenEll", pdfPage := 3, item := "Definition 1.1",
    sectionId := "genell-def-1-1" }

def CoveringSetup.src : Source :=
  { paper := "GenEll", pdfPage := 9, item := "Proposition 1.7",
    sectionId := "genell-prop-1-7" }

end ABC3.Interface.GenEll
