/-
Copyright (c) 2026 ABC3. All rights reserved.
-/
import ABC3.Found.ProL.Decomposition
import ABC3.Found.ProL.ZetaPow

/-!
# `⋂_k M^{p^k}` は `p` 以外の pro-`l` 部分に等しい

原典: S. Mochizuki, *The Geometry of Frobenioids I* [FrdI]、物理 p.52 / p.106。

原文 (FrdI p.106):
> for the closed subgroup topologically generated by the pro-l portions (O×(A))[l]

## ★★何のためか

`Proposition 5.6` の証明は `M_p ⊆ 𝒪^×(A)` を
「`l ≠ p` の pro-`l` 部分が**位相的に**生成する閉部分群」として定める。
★そこで `M_p` が `Aut_𝒞(A)` の共役で閉じることを言うには、
共役(=抽象自己同型)が**連続**でなければならず、
それは **Nikolov–Segal** の定理を要求する(mathlib に在庫なし)。

★★★**本ファイルはその依存を外す** —— `M_p` の**抽象群としての**特徴づけ

  `M_p = { y | ∀ k, ∃ x, x^{p^k} = y }`

を証明する(`forall_pow_pow_iff_pComp_eq_one`)。
★この記述は**冪しか使わない**ので、任意の抽象自己同型で保たれる。

## ★★鍵は 2 本

1. **`eq_one_of_forall_pow_pow`** —— pro-`p` 群では `⋂_k N^{p^k} = 1`。
   ★各有限商 `N/U` は有限 `p` 群なので位数が `p` 冪であり、
   `x^{p^e} = y` を `N/U` へ落とすと `y ≡ 1 (mod U)` になる。
   ★★**位相的有限生成は要らない**(原文が `Definition 2.8` で仮定するものより弱い)。
2. **`pow_bijective_of_proL`**(在庫、`ZetaPow.lean`)—— pro-`l` 群では
   `l` と素な冪写像は全単射。`l ≠ p` なら `p^k` は `l` と素。

★あとは `decompEquiv`(在庫、`Decomposition.lean`)で成分ごとに読むだけである。
-/

namespace ABC3.Found.ProL

universe u

variable {N : Type u} [CommGroup N] [TopologicalSpace N] [IsTopologicalGroup N]
  [CompactSpace N] [TotallyDisconnectedSpace N]

/-- ★★★**pro-`p` 群では `⋂_k N^{p^k} = 1`**。

★各有限商 `N/U` は有限 `p` 群なので `Nat.card (N/U) = p^e`。
`x^{p^e} = y` を落とすと `(mk x)^{p^e} = 1`(Lagrange)なので `mk y = 1`。
★★**位相的有限生成は要らない**。 -/
theorem eq_one_of_forall_pow_pow {p : ℕ} (hp : p.Prime)
    (hpro : ∀ U : OpenNormalSubgroup N, IsPGroup p (N ⧸ U.toSubgroup))
    {y : N} (hy : ∀ k : ℕ, ∃ x : N, x ^ (p ^ k) = y) : y = 1 := by
  haveI : Fact p.Prime := ⟨hp⟩
  refine eq_of_forall_quotient_eq (asProfiniteGrp N) (fun U => ?_)
  show (QuotientGroup.mk y : N ⧸ U.toSubgroup) = QuotientGroup.mk 1
  obtain ⟨e, he⟩ := (IsPGroup.iff_card (p := p) (G := N ⧸ U.toSubgroup)).mp (hpro U)
  obtain ⟨x, hx⟩ := hy e
  have h1 : (QuotientGroup.mk x : N ⧸ U.toSubgroup) ^ (p ^ e) = QuotientGroup.mk y := by
    rw [← QuotientGroup.mk_pow, hx]
  have h2 : (QuotientGroup.mk x : N ⧸ U.toSubgroup) ^ (Nat.card (N ⧸ U.toSubgroup)) = 1 :=
    pow_card_eq_one'
  rw [he] at h2
  rw [← h1, h2]
  exact (QuotientGroup.mk_one _).symm

/-! ## ★★`Proposition 5.6` の `u` の構成で使う 2 本

原文 (FrdI p.107):
> — which [by the total epimorphicity of C] implies that wl

★原文は `w_l ≈ w_l^p` から `w_l ≈ 1` を出し、
`u · φ_p · u⁻¹ ≈ u^{1-p} · φ_p` を解いて `u_p` を作る。
★どちらも「`p-1` は `p` と素」だけで出る。 -/

theorem coprime_pred_self {p : ℕ} (hp : p.Prime) : Nat.Coprime (p - 1) p := by
  have h2 := hp.two_le
  have hs : p = (p - 1) + 1 := by omega
  rw [hs]
  simp [Nat.Coprime]

/-- ★★pro-`p` 群では `w = w^p` なら `w = 1`。 -/
theorem eq_one_of_eq_pow_self {p : ℕ} (hp : p.Prime)
    (hpro : ∀ U : OpenNormalSubgroup N, IsPGroup p (N ⧸ U.toSubgroup))
    {w : N} (hw : w = w ^ p) : w = 1 := by
  have hinj := pow_injective_of_proL hp hpro (coprime_pred_self hp)
  refine hinj ?_
  show w ^ (p - 1) = (1 : N) ^ (p - 1)
  rw [one_pow]
  have h2 : w ^ (p - 1) * w = w ^ p := by
    rw [← pow_succ]
    congr 1
    have := hp.two_le
    omega
  rw [← hw] at h2
  calc w ^ (p - 1) = w ^ (p - 1) * w * w⁻¹ := by group
    _ = w * w⁻¹ := by rw [h2]
    _ = 1 := mul_inv_cancel w

/-- ★★pro-`p` 群では `u ↦ u^{p-1}` は全単射(`p-1` は `p` と素)。 -/
theorem pow_pred_bijective {p : ℕ} (hp : p.Prime)
    (hpro : ∀ U : OpenNormalSubgroup N, IsPGroup p (N ⧸ U.toSubgroup)) :
    Function.Bijective (fun x : N => x ^ (p - 1)) :=
  pow_bijective_of_proL hp hpro (coprime_pred_self hp)

variable {M : Type u} [CommGroup M] [TopologicalSpace M] [IsTopologicalGroup M]
  [CompactSpace M] [TotallyDisconnectedSpace M]

/-- ★`lPart M l` は pro-`l` である(部分群の言葉で)。 -/
theorem lPart_isProL (l : ℕ) :
    ∀ U : OpenNormalSubgroup ↥(lPart M l), IsPGroup l (↥(lPart M l) ⧸ U.toSubgroup) := by
  have h := isProL_lPartGrp (M := M) l
  rw [isProL_iff] at h
  exact h

/-- ★★★★★**`p` のすべての冪で割り切れる ⟺ `p` 成分が自明**。

★★これが原文の `M_p`(`l ≠ p` の pro-`l` 部分が生成する閉部分群)と、
**抽象的な定義 `⋂_k M^{p^k}` との一致**である。
★左辺は冪しか使わないので、**任意の抽象自己同型で保たれる** ——
すなわち `Proposition 5.6` の `M_p` の共役安定性に
**Nikolov–Segal は要らない**。 -/
theorem forall_pow_pow_iff_pComp_eq_one (p : Nat.Primes) (y : M) :
    (∀ k : ℕ, ∃ x : M, x ^ ((p : ℕ) ^ k) = y) ↔ (decompEquiv M y) p = 1 := by
  constructor
  · intro h
    refine eq_one_of_forall_pow_pow p.2 (lPart_isProL (M := M) (p : ℕ)) ?_
    intro k
    obtain ⟨x, hx⟩ := h k
    refine ⟨(decompEquiv M x) p, ?_⟩
    have h2 : (decompEquiv M (x ^ ((p : ℕ) ^ k))) p = (decompEquiv M y) p := by rw [hx]
    rw [map_pow] at h2
    exact h2
  · intro h k
    have hroot : ∀ l : Nat.Primes,
        ∃ z : ↥(lPart M l.1), z ^ ((p : ℕ) ^ k) = (decompEquiv M y) l := by
      intro l
      by_cases hlp : l = p
      · subst hlp
        exact ⟨1, by rw [one_pow, h]⟩
      · have hne : (l : ℕ) ≠ (p : ℕ) := fun hc => hlp (Subtype.ext hc)
        have hcop : Nat.Coprime ((p : ℕ) ^ k) l.1 :=
          Nat.Coprime.pow_left k (Nat.Coprime.symm ((Nat.coprime_primes l.2 p.2).mpr hne))
        obtain ⟨z, hz⟩ :=
          (pow_bijective_of_proL l.2 (lPart_isProL (M := M) l.1) hcop).2 ((decompEquiv M y) l)
        exact ⟨z, hz⟩
    choose z hz using hroot
    refine ⟨(decompEquiv M).symm z, ?_⟩
    refine (decompEquiv M).injective ?_
    rw [map_pow, ContinuousMulEquiv.apply_symm_apply]
    funext l
    exact hz l

/-! ### ★出典の紐付け -/

/-- ★locator —— `Definition 2.8, (ii)` の pro-`l` 分解の帰結。 -/
def eq_one_of_forall_pow_pow.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 52, item := "Definition 2.8, (ii) — pro-p 群では ⋂_k N^{p^k} = 1",
    sectionId := "frdi-def-2-8" }

/-- ★★locator —— `Proposition 5.6` の `M_p` の抽象群としての特徴づけ。 -/
def forall_pow_pow_iff_pComp_eq_one.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 106,
    item := "Proposition 5.6 — M_p の抽象群としての特徴づけ",
    sectionId := "frdi-prop-5-6" }

end ABC3.Found.ProL
