import ABC3.Found.FrdI.MonoidVocabulary
import Mathlib.Data.NNRat.Defs
import Mathlib.Data.NNReal.Basic

/-!
# [FrdI] §0 のモノイド語彙(第 2 部)—— `Bound` / `Primary` / `Prime(M)` / `M_p` / monoprime

原典: S. Mochizuki, *The Geometry of Frobenioids I* [FrdI]、物理 p.10–p.12。

★**`Definition 2.4`(perf-factorial)へ向けた語彙**である。
`MonoidVocabulary.lean` に既にある `MLe`(`≤`)・`MPrec`(`⪯`)・
`IsPrimaryElt`・`Pf`(`M^pf`)の上に積む。

## ★この節で写すもの

| 原文 | ここでの名前 |
|---|---|
| `S` が `b` で bounded | `IsBoundedBy` / `IsBounded` |
| `Bound_S(b)` | `Bound` |
| `Primary(M)` | `PrimarySet` |
| `Primary(M)` 上の `⪯` が同値関係 | `precSetoid` |
| `Prime(M)` | `Prime` |
| `M_p ⊆ M` | `Mp` |
| `Λ-monoprime` / `monoprime` | `IsLambdaMonoprime` / `IsMonoprime` |

原文 (FrdI p.12):
> then we shall say that S is bounded

原文 (FrdI p.12):
> the submonoid generated by the elements contained in the subset p
-/

namespace ABC3.Found.FrdI


variable (M : Type*) [AddCommMonoid M]

/-! ## ★`≤` と `⪯` の基本性質

★**`Prime(M)` を作るのに要る分だけ**を先に取る。
-/

variable {M}

/-- `a ≤ a`。 -/
theorem mle_refl (a : M) : MLe a a := ⟨0, add_zero a⟩

/-- `≤` は推移的。 -/
theorem mle_trans {a b c : M} (h₁ : MLe a b) (h₂ : MLe b c) : MLe a c := by
  obtain ⟨x, hx⟩ := h₁
  obtain ⟨y, hy⟩ := h₂
  exact ⟨x + y, by rw [← add_assoc, hx, hy]⟩

/-- `a ≤ b` なら `n • a ≤ n • b`。 -/
theorem mle_smul {a b : M} (n : ℕ) (h : MLe a b) : MLe (n • a) (n • b) := by
  obtain ⟨c, hc⟩ := h
  exact ⟨n • c, by rw [← smul_add, hc]⟩

/-- `a ⪯ a`。 -/
theorem mprec_refl (a : M) : MPrec a a := ⟨1, one_pos, by rw [one_smul]; exact mle_refl a⟩

/-- ★`⪯` は推移的 —— `a ≤ n•b` と `b ≤ m•c` から `a ≤ (n*m)•c`。 -/
theorem mprec_trans {a b c : M} (h₁ : MPrec a b) (h₂ : MPrec b c) : MPrec a c := by
  obtain ⟨n, hn, hab⟩ := h₁
  obtain ⟨m, hm, hbc⟩ := h₂
  refine ⟨n * m, Nat.mul_pos hn hm, mle_trans hab ?_⟩
  rw [mul_smul]
  exact mle_smul n hbc

/-- `a ≤ b` なら `a ⪯ b`。 -/
theorem mprec_of_mle {a b : M} (h : MLe a b) : MPrec a b := ⟨1, one_pos, by rwa [one_smul]⟩

/-- ★**`x ≤ n • x`**(`n ≥ 1`)。★`n • x = x + (n-1) • x` から。

★**2026-08-17 に `Prop110.lean` からここへ移した** ——
§0 の語彙なのだから、実装場所もこちらであるべきだった。 -/
theorem mle_nsmul_self {n : ℕ} (hn : 0 < n) (x : M) : MLe x (n • x) := by
  obtain ⟨m, rfl⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
  exact ⟨m • x, by rw [succ_nsmul, add_comm]⟩

/-- `n ≥ 1` なら `n • a ⪯ a`。 -/
theorem mprec_nsmul_self (a : M) {n : ℕ} (hn : 0 < n) : MPrec (n • a) a :=
  ⟨n, hn, mle_refl _⟩

/-! ## ★`Bound_S(b)`

原文 (FrdI p.12):
> is the maximal subset of S that is bounded by b]. Observe that if M
-/

variable (M) in
/-- **[FrdI] §0** —— 部分集合 `S` が `b` で **bounded** であること。 -/
def IsBoundedBy (S : Set M) (b : M) : Prop := ∀ a ∈ S, MLe a b

variable (M) in
/-- **[FrdI] §0** —— 部分集合 `S` が **bounded** であること。 -/
def IsBounded (S : Set M) : Prop := ∃ b : M, IsBoundedBy M S b

variable (M) in
/-- **[FrdI] §0** —— `Bound_S(b) = {a ∈ S | a ≤ b}`。

★原文どおり「`S` のうち `b` で bounded な最大の部分集合」である
(`bound_isBoundedBy` / `bound_maximal`)。 -/
def Bound (S : Set M) (b : M) : Set M := {a ∈ S | MLe a b}

theorem bound_isBoundedBy (S : Set M) (b : M) : IsBoundedBy M (Bound M S b) b :=
  fun _ ha => ha.2

/-- ★**`Bound_S(b)` は `S` のうち `b` で bounded な最大の部分集合**。 -/
theorem bound_maximal {S T : Set M} {b : M} (hTS : T ⊆ S) (hT : IsBoundedBy M T b) :
    T ⊆ Bound M S b :=
  fun a ha => ⟨hTS ha, hT a ha⟩

/-! ## ★`Primary(M)` と `Prime(M)`

原文 (FrdI p.12):
> class of elements of Primary(M) will be referred to as a prime of M. [Note that

★★**急所**: 原文は「`a ⪯ b`(`a, b ∈ Primary(M)`)は `Primary(M)` 上の
**同値関係**を定める」と一言で済ませるが、★**対称性が `primary` の定義そのもの**
から来ることを明示する(`mprec_symm_of_primary`)。
-/

variable (M) in
/-- **[FrdI] §0** —— `Primary(M)`、primary な元のなす集合。 -/
def PrimarySet : Set M := {a : M | IsPrimaryElt a}

/-- ★★**`Primary(M)` の上では `⪯` は対称的**。

★**理由は `primary` の定義そのもの**: `a` が primary で `b ≠ 0` かつ `b ⪯ a` なら
`a ⪯ b`。★**片方が primary であればよい**(両方は要らない)。 -/
theorem mprec_symm_of_primary {a b : M} (ha : IsPrimaryElt a) (hb : b ≠ 0)
    (h : MPrec b a) : MPrec a b :=
  ha.2 b hb h

variable (M) in
/-- ★**`Primary(M)` 上の `⪯` が定める同値関係**。

反射律は `mprec_refl`、対称律は `mprec_symm_of_primary`、推移律は `mprec_trans`。 -/
def precSetoid : Setoid {a : M // IsPrimaryElt a} where
  r x y := MPrec x.1 y.1
  iseqv :=
    { refl := fun x => mprec_refl x.1
      symm := fun {x y} h => mprec_symm_of_primary y.2 x.2.1 h
      trans := fun {_ _ _} h₁ h₂ => mprec_trans h₁ h₂ }

variable (M) in
/-- **[FrdI] §0** —— **`Prime(M)`**、`M` の素元の集合。

原文 (FrdI p.12):
> the set of primes of M. If p

★`Primary(M)` を `⪯` で割った商である。 -/
def Prime : Type _ := Quotient (precSetoid M)

variable (M) in
/-- ★primary な元が定める素元。 -/
def toPrime (a : M) (ha : IsPrimaryElt a) : Prime M := Quotient.mk (precSetoid M) ⟨a, ha⟩

theorem toPrime_eq_iff {a b : M} (ha : IsPrimaryElt a) (hb : IsPrimaryElt b) :
    toPrime M a ha = toPrime M b hb ↔ MPrec a b :=
  Quotient.eq (r := precSetoid M)

/-! ## ★`M_p ⊆ M`

原文 (FrdI p.12):
> is closed under multiplication by
-/

variable (M) in
/-- **[FrdI] §0** —— 素元 `p` に属する元の集合。 -/
def primeCarrier (p : Prime M) : Set M := {a : M | ∃ ha : IsPrimaryElt a, toPrime M a ha = p}

variable (M) in
/-- **[FrdI] §0** —— **`M_p ⊆ M`**、`p ⊆ M` の元が生成する部分モノイド。 -/
def Mp (p : Prime M) : AddSubmonoid M := AddSubmonoid.closure (primeCarrier M p)

theorem mem_Mp_of_mem_primeCarrier {p : Prime M} {a : M} (h : a ∈ primeCarrier M p) :
    a ∈ Mp M p := AddSubmonoid.subset_closure h

/-- ★★**「`p ⊆ M` は `ℕ≥1` 倍で閉じている」**(原文の注記)。

★`n • a` が primary であることは、`n • a ⪯ a ⪯ n • a` と `a` の primary 性から出る。
★**`n • a ≠ 0`** には捻れの無さが要る(`IsTorsionFreeNaive`)。 -/
theorem primeCarrier_nsmul_mem (htf : IsTorsionFreeNaive M) {p : Prime M} {a : M}
    (h : a ∈ primeCarrier M p) {n : ℕ} (hn : 0 < n) : n • a ∈ primeCarrier M p := by
  obtain ⟨ha, hp⟩ := h
  have hne : n • a ≠ 0 := fun hz => ha.1 (htf a n hn hz)
  have hna : MPrec (n • a) a := mprec_nsmul_self a hn
  have han : MPrec a (n • a) := mprec_of_mle (mle_nsmul_self hn a)
  have hprim : IsPrimaryElt (n • a) := by
    refine ⟨hne, fun b hb hba => ?_⟩
    exact mprec_trans hna (ha.2 b hb (mprec_trans hba hna))
  refine ⟨hprim, ?_⟩
  rw [← hp]
  exact (toPrime_eq_iff hprim ha).mpr hna

/-- ★**`M_p` も `ℕ≥1` 倍で閉じている**(部分モノイドなので自明)。 -/
theorem Mp_nsmul_mem {p : Prime M} {a : M} (h : a ∈ Mp M p) (n : ℕ) : n • a ∈ Mp M p :=
  AddSubmonoid.nsmul_mem _ h n

/-! ## ★`Λ-monoprime` / `monoprime`

原文 (FrdI p.10):
> monoprime monoid and to a monoid which is a
-/

/-- **[FrdI] §0** —— **monoid type** `Λ ∈ {ℤ, ℚ, ℝ}`。 -/
inductive MonoidType where
  /-- `Λ = ℤ`。 -/
  | int : MonoidType
  /-- `Λ = ℚ`。 -/
  | rat : MonoidType
  /-- `Λ = ℝ`。 -/
  | real : MonoidType
  deriving DecidableEq

namespace MonoidType

/-- **[FrdI] §0** —— `Λ≥0 = Λ ∩ ℝ≥0`。

★`ℤ≥0 = ℕ`、`ℚ≥0 = ℚ≥0`、`ℝ≥0 = ℝ≥0`。 -/
def Nonneg : MonoidType → Type
  | .int => ℕ
  | .rat => NNRat
  | .real => NNReal

instance (Λ : MonoidType) : AddCommMonoid Λ.Nonneg := by
  cases Λ
  · exact (inferInstance : AddCommMonoid ℕ)
  · exact (inferInstance : AddCommMonoid NNRat)
  · exact (inferInstance : AddCommMonoid NNReal)

end MonoidType

variable (M) in
/-- **[FrdI] §0** —— `M` が **`Λ`-monoprime** である
(＝ 加法モノイドとして `Λ≥0` に同型)。 -/
def IsLambdaMonoprime (Λ : MonoidType) : Prop := Nonempty (M ≃+ Λ.Nonneg)

variable (M) in
/-- **[FrdI] §0** —— `M` が **monoprime** である(ある `Λ` について `Λ`-monoprime)。 -/
def IsMonoprime : Prop := ∃ Λ : MonoidType, IsLambdaMonoprime M Λ

/-! ### ★非退化 —— 語彙が空でないことの確認 -/

/-- ★`ℕ` は `ℤ`-monoprime。 -/
theorem isLambdaMonoprime_nat : IsLambdaMonoprime ℕ MonoidType.int :=
  ⟨AddEquiv.refl ℕ⟩

/-- ★`ℕ` は monoprime。 -/
theorem isMonoprime_nat : IsMonoprime ℕ := ⟨MonoidType.int, isLambdaMonoprime_nat⟩

/-- ★`ℕ` では `1` が primary(`MonoidVocabulary` の `isPrimaryElt_one_nat`)なので
`Prime ℕ` は空でない。 -/
theorem nonempty_prime_nat : Nonempty (Prime ℕ) :=
  ⟨toPrime ℕ 1 isPrimaryElt_one_nat⟩

/-- ★`ℕ` は捻れが無い。 -/
theorem isTorsionFreeNaive_nat : IsTorsionFreeNaive ℕ := by
  intro a n hn h
  rw [nsmul_eq_mul, Nat.cast_id] at h
  rcases Nat.mul_eq_zero.mp h with h1 | h1
  · omega
  · exact h1

/-! ## ★★★出典の紐付け(`.src`) -/

variable (M) in
/-- **[FrdI] §0** —— `Bound_S(b)`。 -/
def Bound.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 12, item := "§0 Monoids — Bound_S(b)",
    sectionId := "frdi-s0-bound" }

/-- **[FrdI] §0** —— `Prime(M)`。 -/
def Prime.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 12, item := "§0 Monoids — Prime(M)",
    sectionId := "frdi-s0-prime" }

/-- **[FrdI] §0** —— `M_p`。 -/
def Mp.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 12, item := "§0 Monoids — M_p",
    sectionId := "frdi-s0-mp" }

/-- **[FrdI] §0** —— `Λ-monoprime` / `monoprime`。 -/
def IsMonoprime.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 10, item := "§0 — monoprime",
    sectionId := "frdi-s0-monoprime" }

/-! ## ★★`Prime(M) ≃ Prime(M^pf)` —— 原文 p.12 の 3 本

原文 (FrdI p.12):
> the set of primes of M. If p

★★**原文は `Prime(M)` の定義の直後に 3 本を並べる**(p.12):
`Primary(M^pf)` の記述、`Primary(M)` が `Primary(M^pf)` と `M` の交わりであること、
そして ★**`Prime(M)` から `Prime(M^pf)` への自然な全単射**。

★★★**3 本目が `Definition 2.4, (i), (c)` で要る同一視**である ——
原文はそこで添字を `p ∈ Prime(M)` に取りながら成分を `M^pf_p` と書く。

★★**測定(2026-08-17)**: 原文 p.12 冒頭の standing hypothesis は
「sharp, integral, and saturated」だが、★**この 3 本には torsion-free だけで足りる**
(`isTorsionFreeNaive_of_isSharp` により sharp から出る)。
★以下ではその弱い仮定だけを使う。
-/

/-- ★**加法準同型は `⪯` を保つ**。 -/
theorem mprec_map {N : Type*} [AddCommMonoid N] (f : M →+ N) {a b : M}
    (h : MPrec a b) : MPrec (f a) (f b) := by
  obtain ⟨n, hn, c, hc⟩ := h
  exact ⟨n, hn, f c, by rw [← map_add, hc, map_nsmul]⟩

/-- ★**正の整数倍は `⪯` の左側で効かない**。 -/
theorem mprec_nsmul_left {a b : M} {n : ℕ} (hn : 0 < n) :
    MPrec (n • a) b ↔ MPrec a b := by
  constructor
  · intro h
    exact mprec_trans (mprec_of_mle (mle_nsmul_self hn a)) h
  · rintro ⟨m, hm, hle⟩
    refine ⟨n * m, Nat.mul_pos hn hm, ?_⟩
    have h2 := mle_smul (M := M) n hle
    rwa [smul_smul] at h2

/-- ★**正の整数倍は `⪯` の右側でも効かない**。 -/
theorem mprec_nsmul_right {a b : M} {n : ℕ} (hn : 0 < n) :
    MPrec a (n • b) ↔ MPrec a b := by
  constructor
  · rintro ⟨m, hm, hle⟩
    refine ⟨m * n, Nat.mul_pos hm hn, ?_⟩
    rwa [← smul_smul]
  · intro h
    exact mprec_trans h (mprec_of_mle (mle_nsmul_self hn b))

/-- ★**primary 性は正の整数倍で変わらない**(torsion-free のもとで)。 -/
theorem isPrimaryElt_nsmul_iff (htf : IsTorsionFreeNaive M) {a : M} {n : ℕ}
    (hn : 0 < n) : IsPrimaryElt (n • a) ↔ IsPrimaryElt a := by
  constructor
  · rintro ⟨hne, h⟩
    refine ⟨fun h0 => hne (by rw [h0, smul_zero]), fun b hb hp => ?_⟩
    exact (mprec_nsmul_left hn).mp (h b hb ((mprec_nsmul_right hn).mpr hp))
  · rintro ⟨hne, h⟩
    refine ⟨fun h0 => hne (htf a n hn h0), fun b hb hp => ?_⟩
    exact (mprec_nsmul_left hn).mpr (h b hb ((mprec_nsmul_right hn).mp hp))

/-- ★★**`M^pf` の元は正の整数倍で `M` に入る** —— `k · (m/k) = m`。

★★**これが「`M^pf` の `⪯` は `M` の `⪯` で決まる」ことの土台**である。 -/
theorem Pf.nsmul_mk_self (m : M) (k : ℕ+) :
    ((k : ℕ+) : ℕ) • Pf.mk m k = (Pf.of m : Pf M) := by
  rw [Pf.nsmul_mk, Pf.of_apply]
  exact Pf.sound 1 (by simp [mul_comm, mul_smul])

/-- ★`M^pf` も torsion-free(`M^pf` は perfect なので `n •` が単射)。 -/
theorem isTorsionFreeNaive_pf : IsTorsionFreeNaive (Pf M) := by
  intro x n hn h
  refine Pf.nsmul_injective (M := M) ⟨n, hn⟩ ?_
  simpa using h

/-- ★`M` が torsion-free なら `M → M^pf` は `0` を反映する。 -/
theorem Pf.of_eq_zero_iff (htf : IsTorsionFreeNaive M) {m : M} :
    (Pf.of m : Pf M) = 0 ↔ m = 0 := by
  rw [Pf.of_apply, Pf.mk_eq_zero_iff]
  constructor
  · rintro ⟨k, hk⟩
    exact htf m ((k : ℕ+) : ℕ) k.pos hk
  · rintro rfl
    exact ⟨1, by simp⟩

/-- ★`M → M^pf` の像の等式は「ある正の整数倍で等しい」ことと同値。 -/
theorem Pf.of_eq_of_iff {a b : M} :
    (Pf.of a : Pf M) = Pf.of b ↔ ∃ j : ℕ+, ((j : ℕ+) : ℕ) • a = ((j : ℕ+) : ℕ) • b := by
  rw [Pf.of_apply, Pf.of_apply]
  constructor
  · intro h
    obtain ⟨j, hj⟩ := Quotient.exact h
    exact ⟨j, by simpa using hj⟩
  · rintro ⟨j, hj⟩
    exact Pf.sound j (by simpa using hj)

/-- ★★**`M^pf` の `⪯` は `M` の `⪯` で決まる**(`M` の元の間では一致する)。

★**分母を払う**のが要点 —— `c = e/l` に `l` を掛けると `l · c = e ∈ M` になる。 -/
theorem mprec_pf_of_iff {a b : M} :
    MPrec (Pf.of a : Pf M) (Pf.of b) ↔ MPrec a b := by
  constructor
  · rintro ⟨n, hn, c, hc⟩
    induction c using Pf.inductionOn with
    | _ e l =>
      have h1 : ((l : ℕ+) : ℕ) • ((Pf.of a : Pf M) + Pf.mk e l)
          = ((l : ℕ+) : ℕ) • (n • (Pf.of b : Pf M)) := by rw [hc]
      rw [smul_add, Pf.nsmul_mk_self, smul_smul, ← map_nsmul, ← map_add,
        ← map_nsmul] at h1
      obtain ⟨j, hj⟩ := Pf.of_eq_of_iff.mp h1
      refine (mprec_nsmul_left (n := ((j : ℕ+) : ℕ) * ((l : ℕ+) : ℕ))
        (Nat.mul_pos j.pos l.pos)).mp ?_
      refine ⟨((j : ℕ+) : ℕ) * (((l : ℕ+) : ℕ) * n), by positivity,
        ((j : ℕ+) : ℕ) • e, ?_⟩
      simpa [smul_add, smul_smul] using hj
  · intro h
    exact mprec_map (Pf.of : M →+ Pf M) h

/-- ★★**`Primary(M) = Primary(M^pf) ∩ M`**(原文 p.12 の 2 本目)。 -/
theorem isPrimaryElt_pf_of_iff (htf : IsTorsionFreeNaive M) {m : M} :
    IsPrimaryElt (Pf.of m : Pf M) ↔ IsPrimaryElt m := by
  constructor
  · rintro ⟨hne, h⟩
    refine ⟨fun h0 => hne (by rw [h0, map_zero]), fun b hb hp => ?_⟩
    exact mprec_pf_of_iff.mp
      (h (Pf.of b) (fun h0 => hb ((Pf.of_eq_zero_iff htf).mp h0)) (mprec_pf_of_iff.mpr hp))
  · rintro ⟨hne, h⟩
    refine ⟨fun h0 => hne ((Pf.of_eq_zero_iff htf).mp h0), fun x hx hp => ?_⟩
    induction x using Pf.inductionOn with
    | _ d k =>
      have hkx : ((k : ℕ+) : ℕ) • Pf.mk d k = (Pf.of d : Pf M) := Pf.nsmul_mk_self d k
      have hd0 : d ≠ 0 := by
        intro h0
        refine hx ?_
        have : ((k : ℕ+) : ℕ) • Pf.mk d k = 0 := by rw [hkx, h0, map_zero]
        exact isTorsionFreeNaive_pf (M := M) _ _ k.pos this
      have hpd : MPrec d m := by
        refine mprec_pf_of_iff.mp ?_
        rw [← hkx]
        exact (mprec_nsmul_left k.pos).mpr hp
      have := mprec_pf_of_iff.mpr (h d hd0 hpd)
      rw [← hkx] at this
      exact (mprec_nsmul_right k.pos).mp this

/-- ★★**`Primary(M^pf)` の特徴づけ**(原文 p.12 の 1 本目)——
`M^pf` の元が primary であるのは、正の整数倍が `M` の primary 元になるとき。 -/
theorem isPrimaryElt_pf_iff (htf : IsTorsionFreeNaive M) (x : Pf M) :
    IsPrimaryElt x ↔ ∃ (n : ℕ+) (b : M), IsPrimaryElt b
      ∧ ((n : ℕ+) : ℕ) • x = (Pf.of b : Pf M) := by
  constructor
  · intro hx
    induction x using Pf.inductionOn with
    | _ d k =>
      refine ⟨k, d, ?_, Pf.nsmul_mk_self d k⟩
      refine (isPrimaryElt_pf_of_iff htf).mp ?_
      rw [← Pf.nsmul_mk_self d k]
      exact (isPrimaryElt_nsmul_iff (isTorsionFreeNaive_pf (M := M)) k.pos).mpr hx
  · rintro ⟨n, b, hb, hn⟩
    refine (isPrimaryElt_nsmul_iff (isTorsionFreeNaive_pf (M := M)) n.pos).mp ?_
    rw [hn]
    exact (isPrimaryElt_pf_of_iff htf).mpr hb

/-- ★★**`Prime(M) → Prime(M^pf)`**(原文 p.12 の 3 本目の写像)。 -/
def primeToPf (htf : IsTorsionFreeNaive M) : Prime M → Prime (Pf M) :=
  Quotient.map (fun x => ⟨Pf.of x.1, (isPrimaryElt_pf_of_iff htf).mpr x.2⟩)
    (fun _ _ h => mprec_pf_of_iff.mpr h)

@[simp] theorem primeToPf_mk (htf : IsTorsionFreeNaive M) {a : M} (ha : IsPrimaryElt a) :
    primeToPf htf (toPrime M a ha)
      = toPrime (Pf M) (Pf.of a) ((isPrimaryElt_pf_of_iff htf).mpr ha) := rfl

/-- ★★★**原文 p.12 の 3 本目** —— `Prime(M) → Prime(M^pf)` は**全単射**。 -/
theorem primeToPf_bijective (htf : IsTorsionFreeNaive M) :
    Function.Bijective (primeToPf htf) := by
  constructor
  · refine Quotient.ind fun a => Quotient.ind fun b => ?_
    intro h
    exact Quotient.sound (mprec_pf_of_iff.mp (Quotient.exact h))
  · refine Quotient.ind fun x => ?_
    obtain ⟨n, b, hb, hn⟩ := (isPrimaryElt_pf_iff htf x.1).mp x.2
    refine ⟨toPrime M b hb, ?_⟩
    refine Quotient.sound ?_
    show MPrec (Pf.of b) x.1
    rw [← hn]
    exact (mprec_nsmul_left n.pos).mpr (mprec_refl x.1)

/-- ★★★**原文 p.12 の 3 本目**(全単射としての形)。

★★**`Definition 2.4, (i), (c)` が `p ∈ Prime(M)` を添字にしながら
成分を `M^pf_p` と書けるのは、この同一視による。** -/
noncomputable def primeEquivPf (htf : IsTorsionFreeNaive M) : Prime M ≃ Prime (Pf M) :=
  Equiv.ofBijective _ (primeToPf_bijective htf)

/-- ★primary 元の素点は正の整数倍で変わらない。 -/
theorem toPrime_nsmul {N : Type*} [AddCommMonoid N] (htf : IsTorsionFreeNaive N)
    {x : N} (hx : IsPrimaryElt x) {n : ℕ} (hn : 0 < n) :
    toPrime N (n • x) ((isPrimaryElt_nsmul_iff htf hn).mpr hx) = toPrime N x hx :=
  (toPrime_eq_iff _ _).mpr ((mprec_nsmul_left hn).mpr (mprec_refl x))

/-- ★★**`(M^pf)_{p'}` の生成元は正の整数倍で `M_p` に入る**。 -/
theorem exists_nsmul_of_mem_primeCarrier_pf (htf : IsTorsionFreeNaive M) (p : Prime M)
    {x : Pf M} (hx : x ∈ primeCarrier (Pf M) (primeToPf htf p)) :
    ∃ (n : ℕ+) (b : M), b ∈ primeCarrier M p ∧ ((n : ℕ+) : ℕ) • x = Pf.of b := by
  obtain ⟨hxp, hxe⟩ := hx
  obtain ⟨n, b, hb, hn⟩ := (isPrimaryElt_pf_iff htf x).mp hxp
  refine ⟨n, b, ⟨hb, ?_⟩, hn⟩
  refine (primeToPf_bijective htf).1 ?_
  rw [primeToPf_mk]
  have h1 : toPrime (Pf M) (Pf.of b) ((isPrimaryElt_pf_of_iff htf).mpr hb)
      = toPrime (Pf M) x hxp := by
    refine (toPrime_eq_iff _ _).mpr ?_
    rw [← hn]
    exact (mprec_nsmul_left n.pos).mpr (mprec_refl x)
  rw [h1]
  exact hxe

/-- ★★★**`(M_p)^pf ≃ (M^pf)_{p'}` の実質** ——
`(M^pf)_{p'}` の元は**正の整数倍で `M_p` に入る**。

★★**閉包の元は有限和**なので、★**各項の分母を掛け合わせて揃える**のが要点である
(原文はこの一歩を一言も書いていない)。 -/
theorem exists_nsmul_mem_Mp_of_mem_Mp_pf (htf : IsTorsionFreeNaive M) (p : Prime M)
    {x : Pf M} (hx : x ∈ Mp (Pf M) (primeToPf htf p)) :
    ∃ (n : ℕ+) (b : M), b ∈ Mp M p ∧ ((n : ℕ+) : ℕ) • x = Pf.of b := by
  induction hx using AddSubmonoid.closure_induction with
  | mem y hy =>
    obtain ⟨n, b, hb, hn⟩ := exists_nsmul_of_mem_primeCarrier_pf htf p hy
    exact ⟨n, b, mem_Mp_of_mem_primeCarrier hb, hn⟩
  | zero => exact ⟨1, 0, (Mp M p).zero_mem, by simp⟩
  | add y z _ _ hy hz =>
    obtain ⟨n, b, hb, hn⟩ := hy
    obtain ⟨m, c, hc, hm⟩ := hz
    refine ⟨n * m, ((m : ℕ+) : ℕ) • b + ((n : ℕ+) : ℕ) • c,
      (Mp M p).add_mem ((Mp M p).nsmul_mem hb _) ((Mp M p).nsmul_mem hc _), ?_⟩
    rw [map_add, map_nsmul, map_nsmul, ← hn, ← hm, smul_smul, smul_smul,
      mul_comm ((m : ℕ+) : ℕ) ((n : ℕ+) : ℕ), smul_add, PNat.mul_coe]

/-! ### ★出典 -/

def exists_nsmul_mem_Mp_of_mem_Mp_pf.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 12, item := "§0 Monoids — M_p and M^pf",
    sectionId := "frdi-s0-prime" }

def isPrimaryElt_pf_iff.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 12, item := "§0 Monoids — Primary(M^pf)",
    sectionId := "frdi-s0-prime" }

def isPrimaryElt_pf_of_iff.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 12, item := "§0 Monoids — Primary(M) = Primary(M^pf) cap M",
    sectionId := "frdi-s0-prime" }

def primeEquivPf.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 12, item := "§0 Monoids — Prime(M) = Prime(M^pf)",
    sectionId := "frdi-s0-prime" }

end ABC3.Found.FrdI
