import ABC3.Found.FrdI.MonoidVocabulary
import Mathlib.Data.NNRat.Defs
import Mathlib.Data.NNReal.Basic

/-!
# [FrdI] §0 のモノイド語彙(第 2 部)—— `Bound` / `Primary` / `Prime(M)` / `M_p` / monoprime

原典: S. Mochizuki, *The Geometry of Frobenioids I* [FrdI]、物理 p.10–p.12。

★**`Definition 2.4`(perf-factorial)へ向けた語彙**である。
`MonoidVocabulary.lean` に既にある `MLe`(`≤`)・`MPrec`(`⪯`)・
`IsPrimaryElt`・`Pf`(`M^pf`)の上に積む。

## ★この節で写すもの

| 原文 | ここでの名前 |
|---|---|
| `S` が `b` で bounded | `IsBoundedBy` / `IsBounded` |
| `Bound_S(b)` | `Bound` |
| `Primary(M)` | `PrimarySet` |
| `Primary(M)` 上の `⪯` が同値関係 | `precSetoid` |
| `Prime(M)` | `Prime` |
| `M_p ⊆ M` | `Mp` |
| `Λ-monoprime` / `monoprime` | `IsLambdaMonoprime` / `IsMonoprime` |

原文 (FrdI p.12):
> then we shall say that S is bounded

原文 (FrdI p.12):
> the submonoid generated by the elements contained in the subset p
-/

namespace ABC3.Found.FrdI


variable (M : Type*) [AddCommMonoid M]

/-! ## ★`≤` と `⪯` の基本性質

★**`Prime(M)` を作るのに要る分だけ**を先に取る。
-/

variable {M}

/-- `a ≤ a`。 -/
theorem mle_refl (a : M) : MLe a a := ⟨0, add_zero a⟩

/-- `≤` は推移的。 -/
theorem mle_trans {a b c : M} (h₁ : MLe a b) (h₂ : MLe b c) : MLe a c := by
  obtain ⟨x, hx⟩ := h₁
  obtain ⟨y, hy⟩ := h₂
  exact ⟨x + y, by rw [← add_assoc, hx, hy]⟩

/-- `a ≤ b` なら `n • a ≤ n • b`。 -/
theorem mle_smul {a b : M} (n : ℕ) (h : MLe a b) : MLe (n • a) (n • b) := by
  obtain ⟨c, hc⟩ := h
  exact ⟨n • c, by rw [← smul_add, hc]⟩

/-- `a ⪯ a`。 -/
theorem mprec_refl (a : M) : MPrec a a := ⟨1, one_pos, by rw [one_smul]; exact mle_refl a⟩

/-- ★`⪯` は推移的 —— `a ≤ n•b` と `b ≤ m•c` から `a ≤ (n*m)•c`。 -/
theorem mprec_trans {a b c : M} (h₁ : MPrec a b) (h₂ : MPrec b c) : MPrec a c := by
  obtain ⟨n, hn, hab⟩ := h₁
  obtain ⟨m, hm, hbc⟩ := h₂
  refine ⟨n * m, Nat.mul_pos hn hm, mle_trans hab ?_⟩
  rw [mul_smul]
  exact mle_smul n hbc

/-- `a ≤ b` なら `a ⪯ b`。 -/
theorem mprec_of_mle {a b : M} (h : MLe a b) : MPrec a b := ⟨1, one_pos, by rwa [one_smul]⟩

/-- ★**`x ≤ n • x`**(`n ≥ 1`)。★`n • x = x + (n-1) • x` から。

★**2026-08-17 に `Prop110.lean` からここへ移した** ——
§0 の語彙なのだから、実装場所もこちらであるべきだった。 -/
theorem mle_nsmul_self {n : ℕ} (hn : 0 < n) (x : M) : MLe x (n • x) := by
  obtain ⟨m, rfl⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
  exact ⟨m • x, by rw [succ_nsmul, add_comm]⟩

/-- `n ≥ 1` なら `n • a ⪯ a`。 -/
theorem mprec_nsmul_self (a : M) {n : ℕ} (hn : 0 < n) : MPrec (n • a) a :=
  ⟨n, hn, mle_refl _⟩

/-! ## ★`Bound_S(b)`

原文 (FrdI p.12):
> is the maximal subset of S that is bounded by b]. Observe that if M
-/

variable (M) in
/-- **[FrdI] §0** —— 部分集合 `S` が `b` で **bounded** であること。 -/
def IsBoundedBy (S : Set M) (b : M) : Prop := ∀ a ∈ S, MLe a b

variable (M) in
/-- **[FrdI] §0** —— 部分集合 `S` が **bounded** であること。 -/
def IsBounded (S : Set M) : Prop := ∃ b : M, IsBoundedBy M S b

variable (M) in
/-- **[FrdI] §0** —— `Bound_S(b) = {a ∈ S | a ≤ b}`。

★原文どおり「`S` のうち `b` で bounded な最大の部分集合」である
(`bound_isBoundedBy` / `bound_maximal`)。 -/
def Bound (S : Set M) (b : M) : Set M := {a ∈ S | MLe a b}

theorem bound_isBoundedBy (S : Set M) (b : M) : IsBoundedBy M (Bound M S b) b :=
  fun _ ha => ha.2

/-- ★**`Bound_S(b)` は `S` のうち `b` で bounded な最大の部分集合**。 -/
theorem bound_maximal {S T : Set M} {b : M} (hTS : T ⊆ S) (hT : IsBoundedBy M T b) :
    T ⊆ Bound M S b :=
  fun a ha => ⟨hTS ha, hT a ha⟩

/-! ## ★`Primary(M)` と `Prime(M)`

原文 (FrdI p.12):
> class of elements of Primary(M) will be referred to as a prime of M. [Note that

★★**急所**: 原文は「`a ⪯ b`(`a, b ∈ Primary(M)`)は `Primary(M)` 上の
**同値関係**を定める」と一言で済ませるが、★**対称性が `primary` の定義そのもの**
から来ることを明示する(`mprec_symm_of_primary`)。
-/

variable (M) in
/-- **[FrdI] §0** —— `Primary(M)`、primary な元のなす集合。 -/
def PrimarySet : Set M := {a : M | IsPrimaryElt a}

/-- ★★**`Primary(M)` の上では `⪯` は対称的**。

★**理由は `primary` の定義そのもの**: `a` が primary で `b ≠ 0` かつ `b ⪯ a` なら
`a ⪯ b`。★**片方が primary であればよい**(両方は要らない)。 -/
theorem mprec_symm_of_primary {a b : M} (ha : IsPrimaryElt a) (hb : b ≠ 0)
    (h : MPrec b a) : MPrec a b :=
  ha.2 b hb h

variable (M) in
/-- ★**`Primary(M)` 上の `⪯` が定める同値関係**。

反射律は `mprec_refl`、対称律は `mprec_symm_of_primary`、推移律は `mprec_trans`。 -/
def precSetoid : Setoid {a : M // IsPrimaryElt a} where
  r x y := MPrec x.1 y.1
  iseqv :=
    { refl := fun x => mprec_refl x.1
      symm := fun {x y} h => mprec_symm_of_primary y.2 x.2.1 h
      trans := fun {_ _ _} h₁ h₂ => mprec_trans h₁ h₂ }

variable (M) in
/-- **[FrdI] §0** —— **`Prime(M)`**、`M` の素元の集合。

原文 (FrdI p.12):
> the set of primes of M. If p

★`Primary(M)` を `⪯` で割った商である。 -/
def Prime : Type _ := Quotient (precSetoid M)

variable (M) in
/-- ★primary な元が定める素元。 -/
def toPrime (a : M) (ha : IsPrimaryElt a) : Prime M := Quotient.mk (precSetoid M) ⟨a, ha⟩

theorem toPrime_eq_iff {a b : M} (ha : IsPrimaryElt a) (hb : IsPrimaryElt b) :
    toPrime M a ha = toPrime M b hb ↔ MPrec a b :=
  Quotient.eq (r := precSetoid M)

/-! ## ★`M_p ⊆ M`

原文 (FrdI p.12):
> is closed under multiplication by
-/

variable (M) in
/-- **[FrdI] §0** —— 素元 `p` に属する元の集合。 -/
def primeCarrier (p : Prime M) : Set M := {a : M | ∃ ha : IsPrimaryElt a, toPrime M a ha = p}

variable (M) in
/-- **[FrdI] §0** —— **`M_p ⊆ M`**、`p ⊆ M` の元が生成する部分モノイド。 -/
def Mp (p : Prime M) : AddSubmonoid M := AddSubmonoid.closure (primeCarrier M p)

theorem mem_Mp_of_mem_primeCarrier {p : Prime M} {a : M} (h : a ∈ primeCarrier M p) :
    a ∈ Mp M p := AddSubmonoid.subset_closure h

/-- ★★**「`p ⊆ M` は `ℕ≥1` 倍で閉じている」**(原文の注記)。

★`n • a` が primary であることは、`n • a ⪯ a ⪯ n • a` と `a` の primary 性から出る。
★**`n • a ≠ 0`** には捻れの無さが要る(`IsTorsionFreeNaive`)。 -/
theorem primeCarrier_nsmul_mem (htf : IsTorsionFreeNaive M) {p : Prime M} {a : M}
    (h : a ∈ primeCarrier M p) {n : ℕ} (hn : 0 < n) : n • a ∈ primeCarrier M p := by
  obtain ⟨ha, hp⟩ := h
  have hne : n • a ≠ 0 := fun hz => ha.1 (htf a n hn hz)
  have hna : MPrec (n • a) a := mprec_nsmul_self a hn
  have han : MPrec a (n • a) := mprec_of_mle (mle_nsmul_self hn a)
  have hprim : IsPrimaryElt (n • a) := by
    refine ⟨hne, fun b hb hba => ?_⟩
    exact mprec_trans hna (ha.2 b hb (mprec_trans hba hna))
  refine ⟨hprim, ?_⟩
  rw [← hp]
  exact (toPrime_eq_iff hprim ha).mpr hna

/-- ★**`M_p` も `ℕ≥1` 倍で閉じている**(部分モノイドなので自明)。 -/
theorem Mp_nsmul_mem {p : Prime M} {a : M} (h : a ∈ Mp M p) (n : ℕ) : n • a ∈ Mp M p :=
  AddSubmonoid.nsmul_mem _ h n

/-! ## ★`Λ-monoprime` / `monoprime`

原文 (FrdI p.10):
> monoprime monoid and to a monoid which is a
-/

/-- **[FrdI] §0** —— **monoid type** `Λ ∈ {ℤ, ℚ, ℝ}`。 -/
inductive MonoidType where
  /-- `Λ = ℤ`。 -/
  | int : MonoidType
  /-- `Λ = ℚ`。 -/
  | rat : MonoidType
  /-- `Λ = ℝ`。 -/
  | real : MonoidType
  deriving DecidableEq

namespace MonoidType

/-- **[FrdI] §0** —— `Λ≥0 = Λ ∩ ℝ≥0`。

★`ℤ≥0 = ℕ`、`ℚ≥0 = ℚ≥0`、`ℝ≥0 = ℝ≥0`。 -/
def Nonneg : MonoidType → Type
  | .int => ℕ
  | .rat => NNRat
  | .real => NNReal

instance (Λ : MonoidType) : AddCommMonoid Λ.Nonneg := by
  cases Λ
  · exact (inferInstance : AddCommMonoid ℕ)
  · exact (inferInstance : AddCommMonoid NNRat)
  · exact (inferInstance : AddCommMonoid NNReal)

end MonoidType

variable (M) in
/-- **[FrdI] §0** —— `M` が **`Λ`-monoprime** である
(＝ 加法モノイドとして `Λ≥0` に同型)。 -/
def IsLambdaMonoprime (Λ : MonoidType) : Prop := Nonempty (M ≃+ Λ.Nonneg)

variable (M) in
/-- **[FrdI] §0** —— `M` が **monoprime** である(ある `Λ` について `Λ`-monoprime)。 -/
def IsMonoprime : Prop := ∃ Λ : MonoidType, IsLambdaMonoprime M Λ

/-! ### ★非退化 —— 語彙が空でないことの確認 -/

/-- ★`ℕ` は `ℤ`-monoprime。 -/
theorem isLambdaMonoprime_nat : IsLambdaMonoprime ℕ MonoidType.int :=
  ⟨AddEquiv.refl ℕ⟩

/-- ★`ℕ` は monoprime。 -/
theorem isMonoprime_nat : IsMonoprime ℕ := ⟨MonoidType.int, isLambdaMonoprime_nat⟩

/-- ★`ℕ` では `1` が primary(`MonoidVocabulary` の `isPrimaryElt_one_nat`)なので
`Prime ℕ` は空でない。 -/
theorem nonempty_prime_nat : Nonempty (Prime ℕ) :=
  ⟨toPrime ℕ 1 isPrimaryElt_one_nat⟩

/-- ★`ℕ` は捻れが無い。 -/
theorem isTorsionFreeNaive_nat : IsTorsionFreeNaive ℕ := by
  intro a n hn h
  rw [nsmul_eq_mul, Nat.cast_id] at h
  rcases Nat.mul_eq_zero.mp h with h1 | h1
  · omega
  · exact h1

/-! ## ★★★出典の紐付け(`.src`) -/

variable (M) in
/-- **[FrdI] §0** —— `Bound_S(b)`。 -/
def Bound.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 12, item := "§0 Monoids — Bound_S(b)",
    sectionId := "frdi-s0-bound" }

/-- **[FrdI] §0** —— `Prime(M)`。 -/
def Prime.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 12, item := "§0 Monoids — Prime(M)",
    sectionId := "frdi-s0-prime" }

/-- **[FrdI] §0** —— `M_p`。 -/
def Mp.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 12, item := "§0 Monoids — M_p",
    sectionId := "frdi-s0-mp" }

/-- **[FrdI] §0** —— `Λ-monoprime` / `monoprime`。 -/
def IsMonoprime.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 10, item := "§0 — monoprime",
    sectionId := "frdi-s0-monoprime" }

end ABC3.Found.FrdI
