/-
Copyright (c) 2026 ABC3. All rights reserved.
-/
import ABC3.Found.FrdI.Def24Rlf
import ABC3.Found.FrdI.Prop53Birat
import ABC3.Found.FrdI.Thm52Change

/-!
# [FrdI] Proposition 5.3 —— 実化 `𝒞^rlf` と完全化 `(𝒞^un-tr)^pf` の**行き先**

原文 (FrdI p.103):
> the Frobenioid C the model Frobenioid [cf. Theorem 5.2, (ii)] associated to

★★原文の第 1 文は **定義**である —— `𝒞^rlf` を
「因子の単系 `Φ^rlf`、有理関数の単系 `ℝ·Φ^birat ⊆ (Φ^rlf)^gp` の model Frobenioid」
と定める。第 2 文の後半も同じ形で、`(𝒞^un-tr)^pf` の行き先は
「`Φ^pf`、`ℚ·Φ^birat`」である。

★★**両者は係数 `S` が `ℝ≥0` か `ℚ≥0` かの違いしかない**ので、
本ファイルは `S` を引数に取る形で 1 度だけ作る。

* `Φ ⊗_S` —— `Def24Rlf.lean` の `phiScOn`(関手的模型 `S ⊗_ℕ M`)
* `S·Φ^birat` —— **本ファイル**。`Φ^birat`(`Prop53Birat.lean`)の像が
  `(Φ ⊗_S)^gp` の中で生成する `S`-安定な部分群

## ★`ℝ`-部分空間の書き方

`(Φ ⊗_S)^gp(d) = Gp(S ⊗_ℕ Φ(d))` は群であり、`S` の作用が
`sSmulGp`(スカラー倍の群化)で入る。★原文の「the `ℝ`-vector subspace generated by
`Φ^birat(A_𝒟)`」は、**その作用で閉じた部分群**として書ける
—— 生成集合が `sSmulGp` で閉じているので、生成した部分群も閉じる。

## ★★逸脱(記録)

本ファイルの結果は次の 2 つを**仮定として受け取る**:

1. `hcharInj` —— `Φ ⊗_S` が `MonoidOn` の条件 (a) を満たすこと
   (テンソルの平坦性。鎖 `rlf` の節点 `rlf-flat`)。
2. `hfsmD` —— `𝒟` が of FSM-type であること
   (`Φ^birat` のときと同じ。`index.html` に開示済み)。

★★また、原文は `ℚ·Φ^birat = Φ^birat ⊗_ℤ ℚ = (Φ^birat)^pf` と 3 通りに書くが、
我々は 1 つめの形(スカラー倍で生成した部分群)だけを採り、
**3 つが一致することは証明していない**。
★★そして `(𝒞^un-tr)^pf` が**実際に**この model Frobenioid と同値であることも未証明である
(鎖 `prop55` の `p55iii-pf` / `p55iv-pf`)—— 本ファイルが与えるのは**行き先**だけ。
-/

namespace ABC3.Found.FrdI

open CategoryTheory
open scoped TensorProduct

universe v u w u2 v2

/-! ## ★1. スカラーの作用と `Gp` -/

variable {S : Type} [CommSemiring S]

@[simp] theorem scMap_smul {M N : Type w} [AddCommMonoid M] [AddCommMonoid N]
    (f : M →+ N) (r : S) (x : ScT S M) :
    scMap f (r • x) = r • scMap f x := by
  induction x using TensorProduct.induction_on with
  | zero => simp
  | tmul a m => rw [TensorProduct.smul_tmul']; simp [scMap_tmul, TensorProduct.smul_tmul']
  | add x y hx hy => simp [smul_add, map_add, hx, hy]

/-- ★スカラー倍を群化 `Gp` へ持ち上げたもの。 -/
noncomputable def sSmulGp {N : Type w} [AddCommMonoid N] [Module S N] (r : S) :
    Gp N →+ Gp N := gpMap _ (DistribSMul.toAddMonoidHom N r)

theorem sSmulGp_apply {N : Type w} [AddCommMonoid N] [Module S N] (r : S)
    (x : Gp N) : sSmulGp r x = gpMap _ (DistribSMul.toAddMonoidHom N r) x := rfl

theorem sSmulGp_mul {N : Type w} [AddCommMonoid N] [Module S N] (r s : S)
    (x : Gp N) : sSmulGp r (sSmulGp s x) = sSmulGp (r * s) x := by
  have hc : (DistribSMul.toAddMonoidHom N r).comp (DistribSMul.toAddMonoidHom N s)
      = DistribSMul.toAddMonoidHom N (r * s) := by
    ext y
    show r • (s • y) = (r * s) • y
    rw [smul_smul]
  rw [sSmulGp_apply, sSmulGp_apply, sSmulGp_apply, ← AddMonoidHom.comp_apply, ← gpMap_comp, hc]

@[simp] theorem sSmulGp_one {N : Type w} [AddCommMonoid N] [Module S N] (x : Gp N) :
    sSmulGp (1 : S) x = x := by
  have hc : DistribSMul.toAddMonoidHom N (1 : S) = AddMonoidHom.id N := by
    ext y; exact one_smul _ y
  rw [sSmulGp_apply, hc, gpMap_id]; rfl

/-- ★`scMap` はスカラー倍と可換(群化のあとでも)。 -/
theorem gpMap_scMap_sSmulGp {M N : Type w} [AddCommMonoid M] [AddCommMonoid N]
    (f : M →+ N) (r : S) (x : Gp (ScT S M)) :
    gpMap _ (scMap f) (sSmulGp r x) = sSmulGp r (gpMap _ (scMap f) x) := by
  have hc : (scMap (S := S) f).comp (DistribSMul.toAddMonoidHom (ScT S M) r)
      = (DistribSMul.toAddMonoidHom (ScT S N) r).comp (scMap f) := by
    ext y
    exact scMap_smul f r y
  rw [sSmulGp_apply, sSmulGp_apply, ← AddMonoidHom.comp_apply, ← gpMap_comp,
    ← AddMonoidHom.comp_apply, ← gpMap_comp, hc]

/-- ★`Gp M → Gp (M ⊗_S)`。 -/
noncomputable def toScGp {M : Type w} [AddCommMonoid M] : Gp M →+ Gp (ScT S M) :=
  gpMap _ toSc

/-- ★`toScGp` の自然性。 -/
theorem gpMap_scMap_toScGp {M N : Type w} [AddCommMonoid M] [AddCommMonoid N] (f : M →+ N)
    (x : Gp M) : gpMap _ (scMap f) (toScGp (S := S) x) = toScGp (gpMap _ f x) := by
  have hc : (scMap (S := S) f).comp (toSc : M →+ ScT S M) = (toSc : N →+ ScT S N).comp f := by
    ext y; exact scMap_toSc f y
  show gpMap _ _ (gpMap _ _ x) = gpMap _ _ (gpMap _ _ x)
  rw [← AddMonoidHom.comp_apply, ← gpMap_comp, ← AddMonoidHom.comp_apply, ← gpMap_comp, hc]

/-- ★`scMap` の逆(同型に沿って)。 -/
theorem gpMap_scMap_inv {M N : Type w} [AddCommMonoid M] [AddCommMonoid N]
    (f : M →+ N) (g : N →+ M) (h : g.comp f = AddMonoidHom.id M) (x : Gp (ScT S M)) :
    gpMap _ (scMap g) (gpMap _ (scMap f) x) = x := by
  rw [← AddMonoidHom.comp_apply, ← gpMap_comp, ← scMap_comp, h, scMap_id, gpMap_id]
  rfl

/-! ## ★2. `S·Φ^birat` -/

variable {D : Type u} [Category.{v} D] {C : Type u2} [Category.{v2} C]
  {Φ : MonoidOn.{v, u, w} D} {P : PreFrobenioid C Φ}

variable (S) in
/-- ★★★**`S·Φ^birat(d) ⊆ (Φ ⊗_S)^gp(d)`** ——
`Φ^birat(d)` の像が生成する `S`-安定な部分群。 -/
noncomputable def sPhiBiratOn (G : Frobenioid P) (d : D) :
    AddSubgroup (Gp (ScT S (Φ.val d))) :=
  AddSubgroup.closure
    {x | ∃ (r : S) (y : Gp (Φ.val d)), y ∈ phiBiratOn G d ∧ x = sSmulGp r (toScGp y)}

theorem mem_sPhiBiratOn_gen (G : Frobenioid P) {d : D} (r : S)
    {y : Gp (Φ.val d)} (hy : y ∈ phiBiratOn G d) :
    sSmulGp r (toScGp y) ∈ sPhiBiratOn S G d :=
  AddSubgroup.subset_closure ⟨r, y, hy, rfl⟩

theorem mem_sPhiBiratOn_of_phiBiratOn (G : Frobenioid P) {d : D}
    {y : Gp (Φ.val d)} (hy : y ∈ phiBiratOn G d) :
    toScGp (S := S) y ∈ sPhiBiratOn S G d := by
  have := mem_sPhiBiratOn_gen (S := S) G 1 hy
  rwa [sSmulGp_one] at this

/-- ★★★**`S·Φ^birat` は本当に `S`-部分空間** —— スカラー倍で閉じている。

★原文の「the `ℝ`-vector subspace generated by `Φ^birat(A_𝒟)`」の**中身**である。
生成集合が `sSmulGp` で閉じている(`sSmulGp_mul`)ので、生成した部分群も閉じる。 -/
theorem sPhiBiratOn_smul_mem (G : Frobenioid P) {d : D} (r : S)
    {x : Gp (ScT S (Φ.val d))} (hx : x ∈ sPhiBiratOn S G d) :
    sSmulGp r x ∈ sPhiBiratOn S G d := by
  have hle : sPhiBiratOn S G d ≤ AddSubgroup.comap (sSmulGp r) (sPhiBiratOn S G d) := by
    refine AddSubgroup.closure_le _ |>.mpr ?_
    rintro _ ⟨s, y, hy, rfl⟩
    show sSmulGp r (sSmulGp s (toScGp y)) ∈ sPhiBiratOn S G d
    rw [sSmulGp_mul]
    exact mem_sPhiBiratOn_gen G (r * s) hy
  exact hle hx

/-- ★★★★**`S·Φ^birat` は `𝒟` 上の部分関手**。 -/
theorem sPhiBiratOn_map (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X)
    {d d' : D} (f : d ⟶ d') {x : Gp (ScT S (Φ.val d'))} (hx : x ∈ sPhiBiratOn S G d') :
    gpMap _ (scMap (Φ.map f)) x ∈ sPhiBiratOn S G d := by
  have hle : sPhiBiratOn S G d' ≤
      AddSubgroup.comap (gpMap _ (scMap (Φ.map f))) (sPhiBiratOn S G d) := by
    refine AddSubgroup.closure_le _ |>.mpr ?_
    rintro _ ⟨r, y, hy, rfl⟩
    show gpMap _ (scMap (Φ.map f)) (sSmulGp r (toScGp y)) ∈ sPhiBiratOn S G d
    rw [gpMap_scMap_sSmulGp, gpMap_scMap_toScGp]
    exact mem_sPhiBiratOn_gen G r (phiBiratOn_map G hiso hfn f hy)
  exact hle hx

/-- ★同型に沿っては両向き。 -/
theorem mem_sPhiBiratOn_iso (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X)
    {d d' : D} (f : d ⟶ d') [IsIso f] (x : Gp (ScT S (Φ.val d'))) :
    gpMap _ (scMap (Φ.map f)) x ∈ sPhiBiratOn S G d ↔ x ∈ sPhiBiratOn S G d' := by
  refine ⟨fun h => ?_, fun h => sPhiBiratOn_map G hiso hfn f h⟩
  have hcomp : (Φ.map (inv f)).comp (Φ.map f) = AddMonoidHom.id (Φ.val d') := by
    ext y
    show Φ.map (inv f) (Φ.map f y) = y
    rw [← Φ.map_comp, IsIso.inv_hom_id, Φ.map_id]
  have := sPhiBiratOn_map G hiso hfn (inv f) h
  rwa [gpMap_scMap_inv _ _ hcomp] at this

/-- ★`S·Φ^birat` の誘導射。 -/
noncomputable def sPhiBiratMap (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X)
    {d d' : D} (f : d ⟶ d') :
    ↥(sPhiBiratOn S G d') →+ ↥(sPhiBiratOn S G d) :=
  AddMonoidHom.codRestrict
    ((gpMap _ (scMap (Φ.map f))).comp (sPhiBiratOn S G d').subtype) _
    (fun x => sPhiBiratOn_map G hiso hfn f x.2)

variable (S) in
/-- ★★`S·Φ^birat` の反変関手。 -/
noncomputable def sPhiBiratFunctor (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X) :
    Dᵒᵖ ⥤ AddCommMonCat.{w} where
  obj X := AddCommMonCat.of ↥(sPhiBiratOn S G X.unop)
  map f := AddCommMonCat.ofHom (sPhiBiratMap G hiso hfn f.unop)
  map_id X := by
    refine AddCommMonCat.ext (fun x => ?_)
    refine Subtype.ext ?_
    show gpMap _ (scMap (Φ.map (𝟙 X.unop))) (x : Gp (ScT S (Φ.val X.unop))) = _
    have h : Φ.map (𝟙 X.unop) = AddMonoidHom.id _ := by ext a; exact Φ.map_id _ a
    rw [h, scMap_id, gpMap_id]
    rfl
  map_comp {X Y Z} f g := by
    refine AddCommMonCat.ext (fun x => ?_)
    refine Subtype.ext ?_
    show gpMap _ (scMap (Φ.map (g.unop ≫ f.unop))) (x : Gp (ScT S (Φ.val X.unop))) = _
    have h : Φ.map (g.unop ≫ f.unop) = (Φ.map g.unop).comp (Φ.map f.unop) := by
      ext a; exact Φ.map_comp _ _ a
    rw [h, scMap_comp, gpMap_comp]
    rfl

variable (S) in
/-- ★★★★**`S·Φ^birat` は `𝒟` 上の group-like な単系**。

★条件 (a) は群なので第 2 成分が無料、第 1 成分は `Φ ⊗_S` の単射性から。
★条件 (b) は `𝒟` が of FSM-type であることから(`Φ^birat` と同じ逸脱)。 -/
noncomputable def sPhiBiratMonoidOn (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X)
    (hinj : ∀ {A B : D} (α : B ⟶ A), Function.Injective (scMap (S := S) (Φ.map α)))
    (hint : ∀ A : D, IsIntegralMonoid (ScT S (Φ.val A)))
    (hfsmD : IsOfFSMType D) : MonoidOn.{v, u, w} D where
  functor := sPhiBiratFunctor S G hiso hfn
  charInj {A B} α := by
    letI := isCancelAdd_of_isIntegralMonoid (ScT S (Φ.val A)) (hint A)
    letI := isCancelAdd_of_isIntegralMonoid (ScT S (Φ.val B)) (hint B)
    show IsCharacteristicallyInjective (sPhiBiratMap G hiso hfn α)
    exact ⟨fun x y h => Subtype.ext (gpMap_injective _ (hinj α) (congrArg Subtype.val h)),
      charMap_injective_of_addGroup _⟩
  fsmIso {A B} α hα := by
    letI := isCancelAdd_of_isIntegralMonoid (ScT S (Φ.val A)) (hint A)
    letI := isCancelAdd_of_isIntegralMonoid (ScT S (Φ.val B)) (hint B)
    haveI : IsIso α := hfsmD _ _ α hα
    show Function.Bijective (sPhiBiratMap G hiso hfn α)
    refine ⟨fun x y h => Subtype.ext (gpMap_injective _ (hinj α) (congrArg Subtype.val h)),
      fun y => ?_⟩
    have hcomp : (Φ.map α).comp (Φ.map (inv α)) = AddMonoidHom.id (Φ.val B) := by
      ext z
      show Φ.map α (Φ.map (inv α) z) = z
      rw [← Φ.map_comp, IsIso.hom_inv_id, Φ.map_id]
    refine ⟨⟨gpMap _ (scMap (Φ.map (inv α))) (y : Gp (ScT S (Φ.val B))),
      sPhiBiratOn_map G hiso hfn (inv α) y.2⟩, Subtype.ext ?_⟩
    exact gpMap_scMap_inv _ _ hcomp (y : Gp (ScT S (Φ.val B)))

/-! ## ★3. 行き先の model Frobenioid -/

variable (S) in
/-- ★★★★★★**`(Φ ⊗_S, S·Φ^birat)` の model data**。

★`S = ℝ≥0` なら `Proposition 5.3` の第 1 文の **`𝒞^rlf`**、
`S = ℚ≥0` なら第 2 文の **`(𝒞^un-tr)^pf` の行き先**である。 -/
noncomputable def scModel (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X)
    (hcharInj : ∀ {A B : D} (α : B ⟶ A),
      IsCharacteristicallyInjective (scMap (S := S) (Φ.map α)))
    (hint : ∀ A : D, IsIntegralMonoid (ScT S (Φ.val A)))
    (hfsmD : IsOfFSMType D) : ModelData.{v, u, w} D where
  phi := phiScOn S Φ hcharInj
  bmon := sPhiBiratMonoidOn S G hiso hfn (fun α => (hcharInj α).1) hint hfsmD
  divB := fun A => (sPhiBiratOn S G A).subtype
  divB_nat := fun _ _ => rfl

variable (S) in
/-- ★★★★★**`(Φ ⊗_S, S·Φ^birat)` の model Frobenioid**。 -/
noncomputable abbrev ScModelObj (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X)
    (hcharInj : ∀ {A B : D} (α : B ⟶ A),
      IsCharacteristicallyInjective (scMap (S := S) (Φ.map α)))
    (hint : ∀ A : D, IsIntegralMonoid (ScT S (Φ.val A)))
    (hfsmD : IsOfFSMType D) : Type _ :=
  ModelData.Obj (scModel S G hiso hfn hcharInj hint hfsmD)

/-! ## ★4. `Proposition 5.3` の 1-可換図式の縦の矢印 -/

variable [IsConnected D]

variable (S) in
/-- ★★`𝒞^un-tr` の model data から `(Φ ⊗_S, S·Φ^birat)` への射
(`Φ → Φ ⊗_S` と `Φ^birat → S·Φ^birat`)。 -/
noncomputable def untrToScHom (Fc : FrobenioidCore P) (G : Frobenioid P)
    (hint : ∀ A : D, IsIntegralMonoid (Φ.val A))
    (hcharInj : ∀ {A B : D} (α : B ⟶ A),
      IsCharacteristicallyInjective (scMap (S := S) (Φ.map α)))
    (hintS : ∀ A : D, IsIntegralMonoid (ScT S (Φ.val A)))
    (hfsmD : IsOfFSMType D) :
    ModelDataHom (unTr_ratFnData Fc G hint hfsmD).model
      (scModel S (unTr_frobenioid P Fc G) (unTr_isotropic P Fc)
        (fun Z => (unTr_isOfModelType Fc G).2 Z) hcharInj hintS hfsmD) where
  phiHom _ := toSc
  phiNat f x := (scMap_toSc (Φ.map f) x).symm
  bmonHom d :=
    AddMonoidHom.codRestrict
      ((toScGp : Gp (Φ.val d) →+ Gp (ScT S (Φ.val d))).comp
        (phiBiratOn (unTr_frobenioid P Fc G) d).subtype) _
      (fun x => mem_sPhiBiratOn_of_phiBiratOn (unTr_frobenioid P Fc G) x.2)
  bmonNat := by
    intro A B f x
    refine Subtype.ext ?_
    exact (gpMap_scMap_toScGp (Φ.map f) _).symm
  divCompat _ _ := rfl

variable (S) in
/-- ★★★★★**`Proposition 5.3` の 1-可換図式の縦の矢印** `𝒞^un-tr ⥤ (Φ ⊗_S, S·Φ^birat)`。

★`S = ℝ≥0` なら `𝒞^un-tr ⥤ 𝒞^rlf`、`S = ℚ≥0` なら `𝒞^un-tr ⥤ (𝒞^un-tr)^pf` の行き先。 -/
noncomputable def untrToSc (Fc : FrobenioidCore P) (G : Frobenioid P)
    (hint : ∀ A : D, IsIntegralMonoid (Φ.val A))
    (hcharInj : ∀ {A B : D} (α : B ⟶ A),
      IsCharacteristicallyInjective (scMap (S := S) (Φ.map α)))
    (hintS : ∀ A : D, IsIntegralMonoid (ScT S (Φ.val A)))
    (hfsmD : IsOfFSMType D) :
    UnTr P ⥤ ScModelObj S (unTr_frobenioid P Fc G) (unTr_isotropic P Fc)
      (fun Z => (unTr_isOfModelType Fc G).2 Z) hcharInj hintS hfsmD :=
  (unTr_modelFrobenioid Fc G hint hfsmD).functor ⋙
    (untrToScHom S Fc G hint hcharInj hintS hfsmD).functor

/-! ## ★5. 2 つの特殊化 -/

/-- ★★★**実化 `𝒞^rlf`**(`Proposition 5.3` の第 1 文)。 -/
noncomputable abbrev Crlf (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X)
    (hcharInj : ∀ {A B : D} (α : B ⟶ A),
      IsCharacteristicallyInjective (scMap (S := NNReal) (Φ.map α)))
    (hint : ∀ A : D, IsIntegralMonoid (RlfT (Φ.val A)))
    (hfsmD : IsOfFSMType D) : Type _ :=
  ScModelObj NNReal G hiso hfn hcharInj hint hfsmD

/-- ★★★**`(𝒞^un-tr)^pf` の行き先** `(Φ^pf, ℚ·Φ^birat)`(`Proposition 5.3` の第 2 文)。 -/
noncomputable abbrev CuntrPf (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X)
    (hcharInj : ∀ {A B : D} (α : B ⟶ A),
      IsCharacteristicallyInjective (scMap (S := NNRat) (Φ.map α)))
    (hint : ∀ A : D, IsIntegralMonoid (PfT (Φ.val A)))
    (hfsmD : IsOfFSMType D) : Type _ :=
  ScModelObj NNRat G hiso hfn hcharInj hint hfsmD

/-! ### ★出典の紐付け -/

/-- ★locator —— `Proposition 5.3` の「行き先」(実化と完全化の model Frobenioid)。
★**条つき**: `Φ ⊗_S` の条件 (a) と `𝒟` の of FSM-type を仮定に置いている。
★★`(𝒞^un-tr)^pf` が**実際に**この model Frobenioid と同値であることは未証明
(鎖 `prop55` の `p55iii-pf` / `p55iv-pf`)。 -/
def scModel.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 103,
    item := "Proposition 5.3 — 実化 𝒞^rlf と (𝒞^un-tr)^pf の行き先(model Frobenioid)",
    sectionId := "frdi-prop-5-3" }

end ABC3.Found.FrdI
