/-
Copyright (c) 2026 ABC3. All rights reserved.
-/
import ABC3.Found.FrdI.Def24Rlf
import ABC3.Found.FrdI.Prop53Birat

/-!
# [FrdI] Proposition 5.3 の第 1 文 —— 実化 `𝒞^rlf` の定義

原文 (FrdI p.103):
> the Frobenioid C the model Frobenioid [cf. Theorem 5.2, (ii)] associated to

★★原文の第 1 文は **定義**である —— `𝒞^rlf` を
「因子の単系 `Φ^rlf`、有理関数の単系 `ℝ·Φ^birat ⊆ (Φ^rlf)^gp` の model Frobenioid」
と定める。したがって証明すべき命題は無く、**2 つの単系を `𝒟` 上で立てられるか**だけが問題である。

* `Φ^rlf` —— `Def24Rlf.lean` の `phiRlfOn`(関手的模型 `ℝ≥0 ⊗_ℕ M`)
* `ℝ·Φ^birat` —— **本ファイル**。`Φ^birat`(`Prop53Birat.lean`)の像が
  `(Φ^rlf)^gp` の中で生成する `ℝ≥0`-安定な部分群

## ★`ℝ`-部分空間の書き方

`(Φ^rlf)^gp(d) = Gp(ℝ≥0 ⊗_ℕ Φ(d))` は群であり、`ℝ≥0` の作用が
`rSmulGp`(スカラー倍の群化)で入る。★原文の「the `ℝ`-vector subspace generated by
`Φ^birat(A_𝒟)`」は、**その作用で閉じた部分群**として書ける
—— 生成集合が `rSmulGp` で閉じているので、生成した部分群も閉じる。

## ★★逸脱(記録)

本ファイルの結果は次の 2 つを**仮定として受け取る**:

1. `hcharInj` —— `Φ^rlf` が `MonoidOn` の条件 (a) を満たすこと
   (テンソルの平坦性。鎖 `rlf` の節点 `rlf-flat`)。
2. `hfsmD` —— `𝒟` が of FSM-type であること
   (`Φ^birat` のときと同じ。`index.html` に開示済み)。

★どちらも `index.html` の逸脱一覧および `frdi-decomposition.json` に記録してある。
-/

namespace ABC3.Found.FrdI

open CategoryTheory
open scoped TensorProduct

universe v u w u2 v2

/-! ## ★1. `ℝ≥0` の作用と `Gp` -/

@[simp] theorem rlfMap_smul {M N : Type w} [AddCommMonoid M] [AddCommMonoid N]
    (f : M →+ N) (r : NNReal) (x : RlfT M) :
    rlfMap f (r • x) = r • rlfMap f x := by
  induction x using TensorProduct.induction_on with
  | zero => simp
  | tmul a m => rw [TensorProduct.smul_tmul']; simp [rlfMap_tmul, TensorProduct.smul_tmul']
  | add x y hx hy => simp [smul_add, map_add, hx, hy]

/-- ★スカラー倍を群化 `Gp` へ持ち上げたもの。 -/
noncomputable def rSmulGp {N : Type w} [AddCommMonoid N] [Module NNReal N] (r : NNReal) :
    Gp N →+ Gp N := gpMap _ (DistribSMul.toAddMonoidHom N r)

theorem rSmulGp_apply {N : Type w} [AddCommMonoid N] [Module NNReal N] (r : NNReal)
    (x : Gp N) : rSmulGp r x = gpMap _ (DistribSMul.toAddMonoidHom N r) x := rfl

theorem rSmulGp_mul {N : Type w} [AddCommMonoid N] [Module NNReal N] (r s : NNReal)
    (x : Gp N) : rSmulGp r (rSmulGp s x) = rSmulGp (r * s) x := by
  have hc : (DistribSMul.toAddMonoidHom N r).comp (DistribSMul.toAddMonoidHom N s)
      = DistribSMul.toAddMonoidHom N (r * s) := by
    ext y
    show r • (s • y) = (r * s) • y
    rw [smul_smul]
  rw [rSmulGp_apply, rSmulGp_apply, rSmulGp_apply, ← AddMonoidHom.comp_apply, ← gpMap_comp, hc]

/-- ★`rlfMap` はスカラー倍と可換(群化のあとでも)。 -/
theorem gpMap_rlfMap_rSmulGp {M N : Type w} [AddCommMonoid M] [AddCommMonoid N]
    (f : M →+ N) (r : NNReal) (x : Gp (RlfT M)) :
    gpMap _ (rlfMap f) (rSmulGp r x) = rSmulGp r (gpMap _ (rlfMap f) x) := by
  have hc : (rlfMap f).comp (DistribSMul.toAddMonoidHom (RlfT M) r)
      = (DistribSMul.toAddMonoidHom (RlfT N) r).comp (rlfMap f) := by
    ext y
    exact rlfMap_smul f r y
  rw [rSmulGp_apply, rSmulGp_apply, ← AddMonoidHom.comp_apply, ← gpMap_comp,
    ← AddMonoidHom.comp_apply, ← gpMap_comp, hc]

/-- ★`Gp M → Gp (M^rlf)`。 -/
noncomputable def toRlfGp {M : Type w} [AddCommMonoid M] : Gp M →+ Gp (RlfT M) :=
  gpMap _ toRlf

/-- ★`toRlfGp` の自然性。 -/
theorem gpMap_rlfMap_toRlfGp {M N : Type w} [AddCommMonoid M] [AddCommMonoid N] (f : M →+ N)
    (x : Gp M) : gpMap _ (rlfMap f) (toRlfGp x) = toRlfGp (gpMap _ f x) := by
  have hc : (rlfMap f).comp (toRlf : M →+ RlfT M) = (toRlf : N →+ RlfT N).comp f := by
    ext y; exact rlfMap_toRlf f y
  show gpMap _ _ (gpMap _ _ x) = gpMap _ _ (gpMap _ _ x)
  rw [← AddMonoidHom.comp_apply, ← gpMap_comp, ← AddMonoidHom.comp_apply, ← gpMap_comp, hc]

/-- ★`rlfMap` の逆(同型に沿って)。 -/
theorem gpMap_rlfMap_inv {M : Type w} [AddCommMonoid M] {N : Type w} [AddCommMonoid N]
    (f : M →+ N) (g : N →+ M) (h : g.comp f = AddMonoidHom.id M) (x : Gp (RlfT M)) :
    gpMap _ (rlfMap g) (gpMap _ (rlfMap f) x) = x := by
  rw [← AddMonoidHom.comp_apply, ← gpMap_comp, ← rlfMap_comp, h, rlfMap_id, gpMap_id]
  rfl

/-! ## ★2. `ℝ·Φ^birat` -/

variable {D : Type u} [Category.{v} D] {C : Type u2} [Category.{v2} C]
  {Φ : MonoidOn.{v, u, w} D} {P : PreFrobenioid C Φ}

/-- ★★★**`ℝ·Φ^birat(d) ⊆ (Φ^rlf)^gp(d)`** ——
`Φ^birat(d)` の像が生成する `ℝ≥0`-安定な部分群。 -/
noncomputable def rPhiBiratOn (G : Frobenioid P) (d : D) :
    AddSubgroup (Gp (RlfT (Φ.val d))) :=
  AddSubgroup.closure
    {x | ∃ (r : NNReal) (y : Gp (Φ.val d)), y ∈ phiBiratOn G d ∧ x = rSmulGp r (toRlfGp y)}

theorem mem_rPhiBiratOn_gen (G : Frobenioid P) {d : D} (r : NNReal)
    {y : Gp (Φ.val d)} (hy : y ∈ phiBiratOn G d) :
    rSmulGp r (toRlfGp y) ∈ rPhiBiratOn G d :=
  AddSubgroup.subset_closure ⟨r, y, hy, rfl⟩

/-- ★★★★**`ℝ·Φ^birat` は `𝒟` 上の部分関手**。 -/
theorem rPhiBiratOn_map (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X)
    {d d' : D} (f : d ⟶ d') {x : Gp (RlfT (Φ.val d'))} (hx : x ∈ rPhiBiratOn G d') :
    gpMap _ (rlfMap (Φ.map f)) x ∈ rPhiBiratOn G d := by
  have hle : rPhiBiratOn G d' ≤
      AddSubgroup.comap (gpMap _ (rlfMap (Φ.map f))) (rPhiBiratOn G d) := by
    refine AddSubgroup.closure_le _ |>.mpr ?_
    rintro _ ⟨r, y, hy, rfl⟩
    show gpMap _ (rlfMap (Φ.map f)) (rSmulGp r (toRlfGp y)) ∈ rPhiBiratOn G d
    rw [gpMap_rlfMap_rSmulGp, gpMap_rlfMap_toRlfGp]
    exact mem_rPhiBiratOn_gen G r (phiBiratOn_map G hiso hfn f hy)
  exact hle hx

/-- ★同型に沿っては両向き。 -/
theorem mem_rPhiBiratOn_iso (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X)
    {d d' : D} (f : d ⟶ d') [IsIso f] (x : Gp (RlfT (Φ.val d'))) :
    gpMap _ (rlfMap (Φ.map f)) x ∈ rPhiBiratOn G d ↔ x ∈ rPhiBiratOn G d' := by
  refine ⟨fun h => ?_, fun h => rPhiBiratOn_map G hiso hfn f h⟩
  have hcomp : (Φ.map (inv f)).comp (Φ.map f) = AddMonoidHom.id (Φ.val d') := by
    ext y
    show Φ.map (inv f) (Φ.map f y) = y
    rw [← Φ.map_comp, IsIso.inv_hom_id, Φ.map_id]
  have := rPhiBiratOn_map G hiso hfn (inv f) h
  rwa [gpMap_rlfMap_inv _ _ hcomp] at this

/-- ★`ℝ·Φ^birat` の誘導射。 -/
noncomputable def rPhiBiratMap (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X)
    {d d' : D} (f : d ⟶ d') :
    ↥(rPhiBiratOn G d') →+ ↥(rPhiBiratOn G d) :=
  AddMonoidHom.codRestrict
    ((gpMap _ (rlfMap (Φ.map f))).comp (rPhiBiratOn G d').subtype) _
    (fun x => rPhiBiratOn_map G hiso hfn f x.2)

/-- ★★`ℝ·Φ^birat` の反変関手。 -/
noncomputable def rPhiBiratFunctor (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X) :
    Dᵒᵖ ⥤ AddCommMonCat.{w} where
  obj X := AddCommMonCat.of ↥(rPhiBiratOn G X.unop)
  map f := AddCommMonCat.ofHom (rPhiBiratMap G hiso hfn f.unop)
  map_id X := by
    refine AddCommMonCat.ext (fun x => ?_)
    refine Subtype.ext ?_
    show gpMap _ (rlfMap (Φ.map (𝟙 X.unop))) (x : Gp (RlfT (Φ.val X.unop))) = _
    have h : Φ.map (𝟙 X.unop) = AddMonoidHom.id _ := by ext a; exact Φ.map_id _ a
    rw [h, rlfMap_id, gpMap_id]
    rfl
  map_comp {X Y Z} f g := by
    refine AddCommMonCat.ext (fun x => ?_)
    refine Subtype.ext ?_
    show gpMap _ (rlfMap (Φ.map (g.unop ≫ f.unop))) (x : Gp (RlfT (Φ.val X.unop))) = _
    have h : Φ.map (g.unop ≫ f.unop) = (Φ.map g.unop).comp (Φ.map f.unop) := by
      ext a; exact Φ.map_comp _ _ a
    rw [h, rlfMap_comp, gpMap_comp]
    rfl

/-- ★★★★**`ℝ·Φ^birat` は `𝒟` 上の group-like な単系**。

★条件 (a) は群なので第 2 成分が無料、第 1 成分は `Φ^rlf` の単射性から。
★条件 (b) は `𝒟` が of FSM-type であることから(`Φ^birat` と同じ逸脱)。 -/
noncomputable def rPhiBiratMonoidOn (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X)
    (hinj : ∀ {A B : D} (α : B ⟶ A), Function.Injective (rlfMap (Φ.map α)))
    (hint : ∀ A : D, IsIntegralMonoid (RlfT (Φ.val A)))
    (hfsmD : IsOfFSMType D) : MonoidOn.{v, u, w} D where
  functor := rPhiBiratFunctor G hiso hfn
  charInj {A B} α := by
    letI := isCancelAdd_of_isIntegralMonoid (RlfT (Φ.val A)) (hint A)
    letI := isCancelAdd_of_isIntegralMonoid (RlfT (Φ.val B)) (hint B)
    show IsCharacteristicallyInjective (rPhiBiratMap G hiso hfn α)
    exact ⟨fun x y h => Subtype.ext (gpMap_injective _ (hinj α) (congrArg Subtype.val h)),
      charMap_injective_of_addGroup _⟩
  fsmIso {A B} α hα := by
    letI := isCancelAdd_of_isIntegralMonoid (RlfT (Φ.val A)) (hint A)
    letI := isCancelAdd_of_isIntegralMonoid (RlfT (Φ.val B)) (hint B)
    haveI : IsIso α := hfsmD _ _ α hα
    show Function.Bijective (rPhiBiratMap G hiso hfn α)
    refine ⟨fun x y h => Subtype.ext (gpMap_injective _ (hinj α) (congrArg Subtype.val h)),
      fun y => ?_⟩
    have hcomp : (Φ.map α).comp (Φ.map (inv α)) = AddMonoidHom.id (Φ.val B) := by
      ext z
      show Φ.map α (Φ.map (inv α) z) = z
      rw [← Φ.map_comp, IsIso.hom_inv_id, Φ.map_id]
    refine ⟨⟨gpMap _ (rlfMap (Φ.map (inv α))) (y : Gp (RlfT (Φ.val B))),
      rPhiBiratOn_map G hiso hfn (inv α) y.2⟩, Subtype.ext ?_⟩
    exact gpMap_rlfMap_inv _ _ hcomp (y : Gp (RlfT (Φ.val B)))

/-! ## ★3. `𝒞^rlf` の定義 -/

/-- ★★★★★★**[FrdI] Proposition 5.3 の第 1 文** —— **実化 `𝒞^rlf`** を定める
`ModelData`(因子の単系 `Φ^rlf`、有理関数の単系 `ℝ·Φ^birat`)。

★`Theorem 5.2, (ii)`(実装済み)により、これから作る圏は
isotropic かつ birationally Frobenius-normalized 型の Frobenioid である。 -/
noncomputable def crlfModel (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X)
    (hcharInj : ∀ {A B : D} (α : B ⟶ A),
      IsCharacteristicallyInjective (rlfMap (Φ.map α)))
    (hint : ∀ A : D, IsIntegralMonoid (RlfT (Φ.val A)))
    (hfsmD : IsOfFSMType D) : ModelData.{v, u, w} D where
  phi := phiRlfOn Φ hcharInj
  bmon := rPhiBiratMonoidOn G hiso hfn (fun α => (hcharInj α).1) hint hfsmD
  divB := fun A => (rPhiBiratOn G A).subtype
  divB_nat := fun _ _ => rfl

/-- ★★★★★**実化 `𝒞^rlf`** —— `Proposition 5.3` の第 1 文が定める圏。 -/
noncomputable abbrev Crlf (G : Frobenioid P) (hiso : ∀ Y : C, IsIsotropic P Y)
    (hfn : ∀ X : BiratCat P G, IsFrobeniusNormalized (biratPre P G) X)
    (hcharInj : ∀ {A B : D} (α : B ⟶ A),
      IsCharacteristicallyInjective (rlfMap (Φ.map α)))
    (hint : ∀ A : D, IsIntegralMonoid (RlfT (Φ.val A)))
    (hfsmD : IsOfFSMType D) : Type _ :=
  ModelData.Obj (crlfModel G hiso hfn hcharInj hint hfsmD)

/-! ### ★出典の紐付け -/

/-- ★locator —— `Proposition 5.3` の第 1 文(実化の定義)。★**条つき**:
`Φ^rlf` の条件 (a) と `𝒟` の of FSM-type を仮定に置いている。 -/
def crlfModel.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 103,
    item := "Proposition 5.3 — 実化 𝒞^rlf の定義(Φ^rlf と ℝ·Φ^birat の model Frobenioid)",
    sectionId := "frdi-prop-5-3" }

end ABC3.Found.FrdI
