/-
Copyright (c) 2026 ABC3. All rights reserved.
-/
import ABC3.Found.FrdI.Prop56Mp
import ABC3.Found.FrdI.Def28

/-!
# [FrdI] Proposition 5.6 —— `M_p` の**抽象群としての**定義

原典: S. Mochizuki, *The Geometry of Frobenioids I* [FrdI]、物理 p.106。

原文 (FrdI p.106):
> for the closed subgroup topologically generated by the pro-l portions (O×(A))[l]

## ★★★Nikolov–Segal を外す

`Gap/FrdI/Section5.lean` の `Gap_5_6_Mp` は、`Prop56Mp.lean` の
`isShiftStable_baseIsoEnd` が要求する入力
「**`M_p` が `Aut_𝒞(A)` による共役で閉じていること**」を穴として記録していた。
★理由: 原文の `M_p` は**位相**(`l ≠ p` の pro-`l` 部分)で定義されるので、
共役が `M_p` を保つには自己同型が**連続**でなければならず、
位相的有限生成な副有限群でそれが言えるのは **Nikolov–Segal** の定理だからである。

★★★**その Gap 記録自身が挙げていた迂回路 (b)** ——
「pro-`l` 部分の**抽象群としての**特徴づけ」—— が実際に存在する:

  `M_p = ⋂_{k ≥ 0} M^{p^k}`   (`p` のすべての冪で割り切れる元)

★根拠: 位相的有限生成なアーベル副有限群 `M ≅ ∏_l M[l]` では
`M^{p^k} = ∏_{l ≠ p} M[l] × M[p]^{p^k}`(`l ≠ p` では `p` が `ℤ_l` で可逆)であり、
`M[p]` は有限生成な `ℤ_p`-加群なので `⋂_k M[p]^{p^k} = 1`。
したがって `⋂_k M^{p^k} = ∏_{l ≠ p} M[l]` となり、これが原文の `M_p` である。

★★**この記述は冪しか使わない**ので、**任意の抽象自己同型で保たれる** ——
連続性が要らない。★したがって `shift` 条件は Nikolov–Segal 抜きで出る。

## ★逸脱(記録)

★本ファイルは `M_p` を **`⋂_k M^{p^k}` として定義する**。
上の同一視(位相で定めた原文の `M_p` と一致すること)は、
`Definition 2.8, (ii)` の分解 `M ≅ ∏_l M[l]` と
「有限生成 `ℤ_p`-加群で `⋂_k p^k M = 0`」を使うが、**まだ証明していない**
(依存グラフの鎖 `prop56` の `p56-limit` がそこを消費する)。
★★ただし `isShiftStable_baseIsoEnd` が要求するのは
「`𝒪^▷` に入る・群である・共役で閉じている」の 3 条だけであり、
それらは**この定義から直接出る**(以下)。
-/

namespace ABC3.Found.FrdI

open CategoryTheory

universe v u w u2 v2

variable {D : Type u} [Category.{v} D] {C : Type u2} [Category.{v2} C]
  {Φ : MonoidOn.{v, u, w} D} {P : PreFrobenioid C Φ}

/-! ## ★1. `𝒪^×(A)` の初等的な性質 -/

/-- ★`𝒪^×(A)` の元の逆元も `𝒪^×(A)` に入る。 -/
theorem oTimes_inv_mem {A : C} {m y : End A} (hm : m ∈ OTimes P A)
    (h1 : m * y = 1) (h2 : y * m = 1) : y ∈ OTimes P A := by
  refine ⟨⟨?_, ?_⟩, ⟨⟨y, m, h2, h1⟩, rfl⟩⟩
  · show P.Base ((y : A ⟶ A)) = P.Base (𝟙 A)
    have hb : P.Base ((y : A ⟶ A)) ≫ P.Base ((m : A ⟶ A)) = P.Base (𝟙 A) := by
      rw [← P.Base_comp]
      exact congrArg P.Base (show ((y : A ⟶ A) ≫ (m : A ⟶ A)) = ((1 : End A) : A ⟶ A) from h1)
    rw [hm.1.1, P.Base_id, Category.comp_id] at hb
    simpa only [P.Base_id] using hb
  · show P.degFr ((y : A ⟶ A)) = 1
    have hd : P.degFr ((m : A ⟶ A)) * P.degFr ((y : A ⟶ A)) = 1 := by
      have h0 : P.degFr ((y : A ⟶ A) ≫ (m : A ⟶ A)) = P.degFr (𝟙 A) :=
        congrArg P.degFr (show ((y : A ⟶ A) ≫ (m : A ⟶ A)) = ((1 : End A) : A ⟶ A) from h1)
      rw [P.degFr_comp] at h0
      simpa using h0
    rw [hm.1.2, one_mul] at hd
    exact hd

/-- ★★`𝒪^×(A)` は `Aut_𝒞(A)` による共役で閉じている。

★底は `Base θi ≫ 𝟙 ≫ Base θ = 𝟙`、次数は `degFr θ · degFr θi = 1`(`ℕ+` なので両方 1)。 -/
theorem oTimes_conj_mem {A : C} {θ θi m : End A} (hθ : θ * θi = 1) (hθ' : θi * θ = 1)
    (hm : m ∈ OTimes P A) : θ * m * θi ∈ OTimes P A := by
  have huθ : IsUnit θ := ⟨⟨θ, θi, hθ, hθ'⟩, rfl⟩
  have huθi : IsUnit θi := ⟨⟨θi, θ, hθ', hθ⟩, rfl⟩
  have hmul : ((θ * m * θi : End A) : A ⟶ A)
      = (θi : A ⟶ A) ≫ ((m : A ⟶ A) ≫ (θ : A ⟶ A)) := rfl
  refine ⟨⟨?_, ?_⟩, ?_⟩
  · show P.Base ((θ * m * θi : End A) : A ⟶ A) = P.Base (𝟙 A)
    have hbm : P.Base ((m : A ⟶ A)) = P.Base (𝟙 A) := hm.1.1
    have hb : P.Base ((θi : A ⟶ A)) ≫ P.Base ((θ : A ⟶ A)) = P.Base (𝟙 A) := by
      rw [← P.Base_comp]
      exact congrArg P.Base (show ((θi : A ⟶ A) ≫ (θ : A ⟶ A)) = ((1 : End A) : A ⟶ A) from hθ)
    rw [hmul, P.Base_comp, P.Base_comp, hbm]
    simp only [P.Base_id, Category.id_comp]
    simpa only [P.Base_id] using hb
  · show P.degFr ((θ * m * θi : End A) : A ⟶ A) = 1
    have hdm : P.degFr ((m : A ⟶ A)) = 1 := hm.1.2
    have hd : P.degFr ((θ : A ⟶ A)) * P.degFr ((θi : A ⟶ A)) = 1 := by
      have h0 : P.degFr ((θi : A ⟶ A) ≫ (θ : A ⟶ A)) = P.degFr (𝟙 A) :=
        congrArg P.degFr (show ((θi : A ⟶ A) ≫ (θ : A ⟶ A)) = ((1 : End A) : A ⟶ A) from hθ)
      rw [P.degFr_comp] at h0
      simpa using h0
    rw [hmul, P.degFr_comp, P.degFr_comp, hdm, mul_one]
    exact hd
  · exact (huθ.mul hm.2).mul huθi

/-- ★共役は冪と可換 —— `θ · xⁿ · θ⁻¹ = (θ · x · θ⁻¹)ⁿ`。 -/
theorem conj_pow {A : C} {θ θi x : End A} (hθ : θ * θi = 1) (hθ' : θi * θ = 1) (n : ℕ) :
    θ * x ^ n * θi = (θ * x * θi) ^ n := by
  induction n with
  | zero =>
      simp only [pow_zero, mul_one]
      exact hθ
  | succ k ih =>
      rw [pow_succ, pow_succ, ← ih]
      calc θ * (x ^ k * x) * θi
          = θ * x ^ k * (θi * θ) * x * θi := by rw [hθ']; group
        _ = θ * x ^ k * θi * (θ * x * θi) := by group

/-- ★unit-profinite 型なら `𝒪^×(A)` は可換(`Definition 2.8, (i)` に含まれている)。 -/
theorem oTimes_comm_of_unitProfinite (hup : IsOfUnitProfiniteType P) (A : C) :
    ∀ a b : End A, a ∈ OTimes P A → b ∈ OTimes P A → a * b = b * a := by
  obtain ⟨t, hc, -⟩ := hup A
  intro a b ha hb
  exact congrArg Subtype.val (hc ⟨a, ha⟩ ⟨b, hb⟩)

/-! ## ★2. `M_p` —— `p` のすべての冪で割り切れる単元 -/

/-- ★★★**原文の `M_p` の抽象群としての定義**。

`M_p = ⋂_{k ≥ 0} (𝒪^×(A))^{p^k}` —— **冪しか使わない**ので抽象自己同型で保たれる。 -/
def MpDiv (P : PreFrobenioid C Φ) (A : C) (p : ℕ)
    (hcomm : ∀ a b : End A, a ∈ OTimes P A → b ∈ OTimes P A → a * b = b * a) :
    Submonoid (End A) where
  carrier := {m | m ∈ OTimes P A ∧ ∀ k : ℕ, ∃ x, x ∈ OTimes P A ∧ x ^ (p ^ k) = m}
  one_mem' := ⟨(OTimes P A).one_mem, fun k => ⟨1, (OTimes P A).one_mem, one_pow _⟩⟩
  mul_mem' {a b} ha hb := by
    refine ⟨(OTimes P A).mul_mem ha.1 hb.1, fun k => ?_⟩
    obtain ⟨x, hx, rfl⟩ := ha.2 k
    obtain ⟨y, hy, rfl⟩ := hb.2 k
    exact ⟨x * y, (OTimes P A).mul_mem hx hy, Commute.mul_pow (hcomm x y hx hy) _⟩

variable {A : C} {p : ℕ}
  {hcomm : ∀ a b : End A, a ∈ OTimes P A → b ∈ OTimes P A → a * b = b * a}

@[simp] theorem mem_MpDiv {m : End A} :
    m ∈ MpDiv P A p hcomm ↔
      m ∈ OTimes P A ∧ ∀ k : ℕ, ∃ x, x ∈ OTimes P A ∧ x ^ (p ^ k) = m := Iff.rfl

/-- ★`M_p ⊆ 𝒪^▷(A)`。 -/
theorem MpDiv_le_OTri : ∀ m ∈ MpDiv P A p hcomm, m ∈ OTri P A :=
  fun _ hm => OTimes_le_OTri P A hm.1

/-- ★★`M_p` は群である。 -/
theorem MpDiv_inv : ∀ x ∈ MpDiv P A p hcomm, ∃ y ∈ MpDiv P A p hcomm, x * y = 1 ∧ y * x = 1 := by
  intro m hm
  obtain ⟨um, hum⟩ := hm.1.2
  have hmu : m * ((um⁻¹ : (End A)ˣ) : End A) = 1 := by rw [← hum]; exact um.mul_inv
  have hum' : ((um⁻¹ : (End A)ˣ) : End A) * m = 1 := by rw [← hum]; exact um.inv_mul
  refine ⟨(um⁻¹ : (End A)ˣ), ⟨oTimes_inv_mem hm.1 hmu hum', ?_⟩, hmu, hum'⟩
  intro k
  obtain ⟨x, hx, hxn⟩ := hm.2 k
  obtain ⟨ux, hux⟩ := hx.2
  have hxu : x * ((ux⁻¹ : (End A)ˣ) : End A) = 1 := by rw [← hux]; exact ux.mul_inv
  have hux' : ((ux⁻¹ : (End A)ˣ) : End A) * x = 1 := by rw [← hux]; exact ux.inv_mul
  have hxinv : ((ux⁻¹ : (End A)ˣ) : End A) ∈ OTimes P A := oTimes_inv_mem hx hxu hux'
  refine ⟨(ux⁻¹ : (End A)ˣ), hxinv, ?_⟩
  have hcm : Commute ((ux⁻¹ : (End A)ˣ) : End A) x := hcomm _ _ hxinv hx
  have hkey : ((ux⁻¹ : (End A)ˣ) : End A) ^ (p ^ k) * m = 1 := by
    rw [← hxn, ← hcm.mul_pow, hux', one_pow]
  calc ((ux⁻¹ : (End A)ˣ) : End A) ^ (p ^ k)
      = ((ux⁻¹ : (End A)ˣ) : End A) ^ (p ^ k) * (m * ((um⁻¹ : (End A)ˣ) : End A)) := by
        rw [hmu, mul_one]
    _ = (((ux⁻¹ : (End A)ˣ) : End A) ^ (p ^ k) * m) * ((um⁻¹ : (End A)ˣ) : End A) := by
        rw [mul_assoc]
    _ = ((um⁻¹ : (End A)ˣ) : End A) := by rw [hkey, one_mul]

/-- ★★★★★**`M_p` は共役で閉じている** —— **Nikolov–Segal を使わない**。

★`m = x^{p^k}` なら `θ m θ⁻¹ = (θ x θ⁻¹)^{p^k}` であり、
`θ x θ⁻¹ ∈ 𝒪^×(A)` は `oTimes_conj_mem` で出る。 -/
theorem MpDiv_conj : ∀ θ θi : End A, θ * θi = 1 → θi * θ = 1 →
    ∀ m ∈ MpDiv P A p hcomm, θ * m * θi ∈ MpDiv P A p hcomm := by
  intro θ θi hθ hθ' m hm
  refine ⟨oTimes_conj_mem hθ hθ' hm.1, fun k => ?_⟩
  obtain ⟨x, hx, rfl⟩ := hm.2 k
  exact ⟨θ * x * θi, oTimes_conj_mem hθ hθ' hx, (conj_pow hθ hθ' _).symm⟩

/-- ★★★★★★**`Proposition 5.6` の `shift` 条件が Nikolov–Segal なしで出る**。

★`Gap_5_6_Mp` が要求していた 3 条(`𝒪^▷` に入る・群・共役で閉じる)は
`MpDiv` から**すべて出る**。 -/
theorem isShiftStable_MpDiv (G : Frobenioid P) (hiso : ∀ X : C, IsIsotropic P X)
    (hA : IsFrobeniusTrivial P A) (hfn : IsFrobeniusNormalized P A) :
    IsShiftStable (baseIsoEnd P A) (MpDiv P A p hcomm) :=
  isShiftStable_baseIsoEnd G hiso hA hfn (MpDiv P A p hcomm)
    MpDiv_le_OTri MpDiv_inv MpDiv_conj

/-! ### ★出典の紐付け -/

/-- ★locator —— `Proposition 5.6` の `M_p`(抽象群としての定義)。
★**逸脱**: 位相で定めた原文の `M_p` との一致は未証明(ファイル冒頭の記録)。 -/
def MpDiv.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 106, item := "Proposition 5.6 — M_p(抽象群としての定義)",
    sectionId := "frdi-prop-5-6" }

/-- ★★locator —— `shift` 条件が Nikolov–Segal 抜きで出ること。 -/
def isShiftStable_MpDiv.src : ABC3.Meta.Source :=
  { paper := "FrdI", pdfPage := 106,
    item := "Proposition 5.6 — M_p の共役安定性(Nikolov–Segal 抜き)",
    sectionId := "frdi-prop-5-6" }

end ABC3.Found.FrdI
