import ABC3.Found.FrdI.Prop56Mp

/-!
# Gap — [FrdI] §5 で残る 1 段(`Proposition 5.6` の `M_p`)

★**`Found/FrdI/Prop56Sec.lean` で `Proposition 5.6` の claim(還元)を証明した。**
★**`Found/FrdI/Prop56Cos.lean` で商単系 `E_M` を作った。**
★**`Found/FrdI/Prop56Mp.lean` で `shift` 条件を「`M` が共役で閉じている」に帰着させた。**

## ★原文

原文 (FrdI p.106):
> for the closed subgroup topologically generated by the pro-l portions (O×(A))[l]

★原文は `M_p ⊆ 𝒪^×(A)` を「`l ≠ p` の pro-`l` 部分 `(𝒪^×(A))[l]` が
**位相的に生成する閉部分群**」と定める。

## ★★測定(2026-08-20)—— **ここで `Definition 2.8` の角括弧を消費する**

`Prop56Mp.lean` の `isShiftStable_baseIsoEnd` により、残る入力は

* `M_p` が群であること、
* ★**`M_p` が `Aut_𝒞(A)` による共役で閉じていること**

の 2 つだけである。★前者は自明。★★**後者が問題**である:

1. `θ ∈ Aut_𝒞(A)` による共役は `𝒪^×(A)` の**抽象群としての**自己同型を与える
   (底が恒等になることは計算で確かめられる)。
2. ところが `M_p` は**位相**で定義されている(`lPart` は `OpenNormalSubgroup` を走る)。
3. したがって共役が `M_p` を保つには、その自己同型が**連続**でなければならない。
4. ★位相的有限生成な副有限群では**すべての抽象自己同型が連続**である
   —— これが **Nikolov–Segal** の定理(同値な形: 有限指数部分群はすべて開)。

★★**そして `Def28.lean` は、`Definition 2.8, (i)` の角括弧
「[uniquely determined]」が Nikolov–Segal に依るので主張しない、と明記していた。**
★つまり `Proposition 5.6` の `M_p` の段は、**その角括弧をそのまま消費している**。

## ★在庫(2026-08-20 に測定)

| 検索語 | mathlib での件数 |
|---|---|
| `Nikolov` | **0** |
| 「有限指数部分群は開」型の定理 | **0**(`ClosedSubgroup.lean` にあるのは閉部分群の一般論) |

★分類は **② `missingMath`** —— 数学は公表された定理であり、原典に瑕疵は無い。
★★**迂回路**: 位相が `Aut_𝒞(A)` で不変であることを**仮定に置く**ことはできる
(その場合は分類 (B) の逸脱になる)。★あるいは pro-`l` 部分の
**抽象群としての**特徴づけ(すべての抽象自己同型で保たれるもの)が見つかれば、
Nikolov–Segal を使わずに閉じる。
-/

namespace ABC3.Gap.FrdI

open CategoryTheory
open ABC3.Found.FrdI

universe v u w u2 v2

/-- ★**`Proposition 5.6` に残る 1 段** —— `M_p` の存在と、その共役安定性。

★★これは `Found/FrdI/Prop56Mp.lean` の `isShiftStable_baseIsoEnd` が要求する入力
そのものである。★共役安定性が **Nikolov–Segal** を消費する(上の測定を見よ)。 -/
structure Gap_5_6_Mp {D : Type u} [Category.{v} D] {C : Type u2} [Category.{v2} C]
    {Φ : MonoidOn.{v, u, w} D} (P : PreFrobenioid C Φ) (A : C) : Prop where
  /-- 不足: 各素数 `p` について、`𝒪^×(A)` の部分群 `M_p` で
  **`Aut_𝒞(A)` による共役で閉じている**ものが取れること。 -/
  existsMp : ∀ p : ℕ, p.Prime → ∃ M : Submonoid (End A),
    (∀ m ∈ M, m ∈ OTri P A) ∧
    (∀ x ∈ M, ∃ y ∈ M, x * y = 1 ∧ y * x = 1) ∧
    (∀ θ θi : End A, θ * θi = 1 → θi * θ = 1 → ∀ m ∈ M, θ * m * θi ∈ M)

def Gap_5_6_Mp.record : ABC3.Meta.GapRecord :=
  { source :=
      { paper := "FrdI", pdfPage := 106,
        item := "Proposition 5.6 — M_p の存在と共役安定性",
        sectionId := "frdi-prop-5-6" },
    classification := ABC3.Meta.GapClass.missingMath,
    falsifier :=
      "★2026-08-20 に穴を 1 点に絞った: `isShiftStable_baseIsoEnd` により、" ++
      "残るのは『`M_p` が `Aut_𝒞(A)` による共役で閉じていること』だけである。" ++
      "★`M_p` は位相(pro-`l` 部分)で定義されるので、共役が連続でなければ保たれない。" ++
      "位相的有限生成な副有限群で抽象自己同型がすべて連続であることは " ++
      "**Nikolov–Segal** の定理であり、mathlib に在庫が無い(`Nikolov` は 0 件)。" ++
      "★★これは `Definition 2.8, (i)` の角括弧『[uniquely determined]』" ++
      "(`Def28.lean` が主張しないと明記したもの)を、そのまま消費している。" ++
      "★この分類が覆るのは (a) Nikolov–Segal が mathlib に入る、" ++
      "(b) pro-`l` 部分の**抽象群としての**特徴づけが見つかる、" ++
      "(c) 位相の `Aut` 不変性を仮定に置く(その場合は分類 (B) の逸脱になる)、のいずれか。" }

end ABC3.Gap.FrdI
