import ABC3.Skeleton.PGC.Section3
import ABC3.Skeleton.PGC.Section4Defs
import ABC3.Found.PGC.OpenSubgroupSpan
import ABC3.Found.PGC.RamificationNaturality
import ABC3.Found.PGC.UnramifiedBaseChangeInvariance
import ABC3.Found.PGC.StageUpperNaturality

/-!
# [pGC] §4 — 命題(主定理)

設定・記号は `ABC3/Skeleton/PGC/Setup.lean`。§2 の `RamificationFiltration`・
`FilteredGroup`(`Skeleton/PGC/Setup.lean`)を継続して使う。

構造化: `ResearchPaper/1_Structured/A Version of the Grothendieck Conjecture for p-adic
Local Fields/section-4.html`(PDF 目視確認 2026-09-03、物理 p.6末尾-7)。

## ★2026-09-08: 定義を `Section4Defs.lean` へ割った

`ABC3.Interface.PGC.RamificationFiltration.filt`(**定義**)とその `.src` は
`ABC3/Skeleton/PGC/Section4Defs.lean` へ移した。本ファイルには**定理だけ**が残る
(`Section1Defs.lean`・`Section2Defs.lean` と同じ作法)。
★完全修飾名は `ABC3.Interface.PGC.RamificationFiltration.filt` のまま変わらない。
理由(`Found/PGC/` の 202 本すべてが本ファイルを import できなかったこと)は
`Section4Defs.lean` の docstring に測定つきで書いた。
-/

namespace ABC3.Skeleton.PGC

open ABC3.Meta ABC3.Interface.PGC ABC3.Found.PGC

variable {p : ℕ} [Fact p.Prime]

/-! ## Lemma 4.1 -/

/-- **[pGC] Lemma 4.1**。`sorry` 無し——実装は `Found/PGC/OpenSubgroupSpan.lean`。

原文 (pGC p.7):
> If I ⊆ U_K is an open subgroup, then the Q_p-vector space generated by I in K is equal
> to K.

★★**この節の中で唯一、著者自身が完全な自己完結証明を与えている項目**——§1〜§3 の
境界外入力(局所 Tate 双対性・局所類体論・高次分岐群・p 進対数・Hodge-Tate 理論)を
一切使わない。mathlib の `Submodule.eq_top_of_nonempty_interior'` に直接帰着する
(詳細は `Found/PGC/OpenSubgroupSpan.lean` の docstring)。 -/
theorem lemma_4_1 (K : PAdicLocalField p)
    {I : Set K.carrier} (hIU : I ⊆ {x : K.carrier | ‖x‖ = 1})
    (hIopen : IsOpen I) (h1 : (1 : K.carrier) ∈ I) :
    Submodule.span ℚ_[p] I = ⊤ :=
  ABC3.Found.PGC.lemma_4_1 p K hIU hIopen h1

def lemma_4_1.src : Source :=
  { paper := "pGC", pdfPage := 7, item := "Lemma 4.1", sectionId := "lemma-4-1" }

/-- ★**空リストは省略ではなく主張である**——原文の証明は「Q_p の位相が非離散」という
一点だけから閉じる(`Found/PGC/OpenSubgroupSpan.lean` 参照)。外部文献も別項目も引かない。 -/
def lemma_4_1.needs : List ProofObligation := []

/-! ## Theorem 4.2(主定理) -/

/-- **[pGC] Theorem 4.2**(主定理)

原文 (pGC p.7):
> Let K and K[prime] be finite extensions of Q_p. Let Isom_Q_p(K, K[prime]) denote the set of
> Q_p-algebra isomorphisms of K with K[prime]. Let Out_Filt(Γ_K, Γ_K[prime]) denote the set of outer
> isomorphisms of filtered groups between the absolute Galois groups of K and K[prime] equipped
> with the filtrations defined by the higher (i.e., with index > 0) ramification groups in
> the upper numbering. Then the natural morphism
> Isom_Q_p(K, K[prime]) → Out_Filt(Γ_K, Γ_K[prime])
> induced by "looking at the morphism induced on absolute Galois groups" is a bijection.

## 形式化上の簡略化(逸脱として記録)

原文の「自然な射」——K の Q_p-代数同型 α を、代数閉包への延長 ᾱ 経由で
filtered group の外部同型に持ち上げる構成——はそれ自体まだ構築していない
(延長の存在は一般論で従うが、延長の取り方によらず外部同型類が一意に定まることの
証明を要する、独立した構成)。

ここでは自然な射を `Φ` として**パラメータで受け取り**、それが全単射であることだけを
主張する——`Φ` の構成そのものは `.needs` に implicitStep として明示的に記録した。

## ★★★2026-09-05: **この形は偽である**(`Check/PGC/Theorem42Degenerate.lean`)

`Φ` に自然性の制約が一切無いので、上の主張は「**任意の**関数が全単射」を
言っていることになる。定数関数が反例になる:

* `RF` は退化させてよい(`Gv ≡ ⊤`)。
* `K` として `ℚ_p` の**不分岐2次拡大**を取ると
  `Isom_{Q_p}(K,K) = Gal(K/ℚ_p)` は 2 元
  (`Found/PGC/UnramifiedExtension.lean::exists_isCyclic_gal` +
  `Found/PGC/AdjoinFieldConstruction.lean::adjoinField`)。
* `Φ := fun _ => 恒等外部同型` は単射でない。

`Check.PGC.theorem_4_2_statement_false` に `sorry` 無しの証明がある。
すなわち本項目は「`sorry` が埋まらない」のではなく「**埋めようがない**」。

## ★★★2026-09-05: **直した**(`Found/PGC/RamificationNaturality.lean`)

自然な射を**構成**して、それについて述べる形に直した:

* 延長 `extendToClosure`(mathlib `IsAlgClosure.equivOfEquiv`)
* 共役 `galMulEquivOf`
* 延長の選択に依らない `galMulEquivOf_indep`(=**外部**同型としては一意)
* **連続性** `galContinuousMulEquiv`(`Found/PGC/GaloisTransferContinuous.lean`)
* `map_Gv` は `IsNaturalFiltration RF` として**明示的な仮説**に切り出した

最後の一点だけが仮説として残るのは、`Interface.PGC.RamificationFiltration`
が `K` ごとに独立な `Gv` を許す抽象データで、「体の同型から誘導される共役が
`Gv` を保つ」という自然性を課していないため(`memory/
pgc-ramification-naturality-gap.md`、下の `.needs` の implicitStep と同じ穴)。
本物の高次分岐群なら成り立つ性質であり、Herbrand の定理が入って
`RamificationFiltration` が構成された時点でこの仮説は落ちる。

★仮説 `IsNaturalFiltration` は空虚ではない
(`Found.PGC.exists_isNaturalFiltration`——退化した `Gv ≡ ⊤` が満たす)。

## ★★★★★2026-09-08(D32 採用): ★**旧形は `∀ RF` のせいで偽だった。実物に固定した**

☆★★**旧形(`RF` を自由に取る形)は、原典自身が偽と述べている素朴 Grothendieck 予想を含意する。**
`Check/PGC/Theorem42NaiveGC.lean::theorem_4_2_current_form_implies_naive_GC` が示し、
`::not_theorem_4_2_current_form_of_nonisomorphic` が
「[8] Jarden-Ritter の例が 1 組でも入れば現行形は倒れる」と述べている。

★★**理由は 1 行で言える**: ★**`IsNaturalFiltration` は退化した `Gv ≡ ⊤` が満たす**ので、
`∀ RF` の形だと ★**`OutFilt` が「濾過を保つ外部同型」ではなく「ただの外部同型」になり、
全射性がそのまま素朴版になってしまう。**
★原典の `OutF ilt(Γ_K, Γ_K')` は ★**上付き番号付けの高次分岐群による濾過**を指す。

☆★★★**これは D13(Prop 1.2 の `∀ RD`)・D30(Prop 2.2 の自由な型族)・
D31(Cor 3.1/3.3 の自由な述語・写像)と同じ「同型不変性」の欠落であり、★4 例目である。**
★**pGC の残り 4 件が 4 件とも同じ病気だった。**

⇒ ★**実物 `ABC3.Found.PGC.ramificationFiltration p`
(`Found/PGC/UnramifiedBaseChangeInvariance.lean:949`、`compat` まで無条件)に固定する。**
★これは**原典の主張を弱めたのではなく、原典が言っていない主張を落とした**ものである。

## ★★★★★★2026-09-08(後刻): ★**自然性が無条件で証明され、仮説が 0 本になった**

★★**`ABC3.Found.PGC.isNaturalFiltration_ramificationFiltration p`**(仮定ゼロ・`sorry` ゼロ)——
`Found/PGC/StageNaturality.lean` + `StageTransport.lean` + `StageUpperNaturality.lean`(4 段の梯子)。
⇒ ★**本定理は `(K K' : PAdicLocalField p)` だけを取る形になった。★残るのは全射性だけ。**

★★**原典より短い道**: ★**局所類体論を 1 度も経由していない。**
原典 §4 は「自然な射」を Artin 写像の自然性で述べるが、実際に使ったのは
(i) 無限 Galois 対応 `InfiniteGalois.normal_iff_isGalois`、
(ii) スペクトルノルムの保存 `norm_extendToClosure`、
(iii) Herbrand 関数の全射準同型に沿った不変性 `map_upperRamificationGroup_eq` の 3 つだけ。
★`Found/PGC/LubinTate*.lean` 57 本からは **`addVal_ringEquiv` 1 本**を借りただけである。
★惰性群の輸送は Corollary 1.3 の押し出し **20 行**、
★★**延長 `ᾱ` の選択非依存性は「正規性」だけ(3 行)** —— これが
★**「原典が `Out`(外部同型)で述べる理由」の中身**である。

## ★残る 1 つ(数学)

★**全射性**(★射 `naturalOuterIso` は 2026-09-05 に構成済み)。
   ★原典の道: Cor 3.3 → `α_K : K ≅ K'` の構成 → Lemma 4.1(★**閉じている**) →
   ★**"standard general nonsense argument"** で有限次拡大へ。
   ☆★**その "general nonsense" は `hedge-index.mjs` の語彙に無く、0 件と報告される**
   (2026-09-08 に本体が実測)。★**畳まれた量は測れていない。** -/
theorem theorem_4_2 (K K' : PAdicLocalField p) :
    Function.Bijective
      (naturalOuterIso (ABC3.Found.PGC.ramificationFiltration p)
        (ABC3.Found.PGC.isNaturalFiltration_ramificationFiltration p) (K := K) (K' := K')) := sorry

def theorem_4_2.src : Source :=
  { paper := "pGC", pdfPage := 7, item := "Theorem 4.2", sectionId := "theorem-4-2" }

def theorem_4_2.needs : List ProofObligation :=
  [ .implicitStep
      ("★2026-09-05: **この段は解消した**——Found/PGC/RamificationNaturality.lean::" ++
       "naturalOuterIso として自然な射を実際に構成し、theorem_4_2 の statement を" ++
       "それについて述べる形に直した(連続性は GaloisTransferContinuous.lean で解消、" ++
       "map_Gv は IsNaturalFiltration という明示的な仮説に切り出した)。以下は経緯: " ++
       "Q_p-代数同型 α : K ≃ K′ を代数閉包への同型 ᾱ : K̄ ≃ K̄′ へ延長し、共役で誘導される" ++
       "Γ_K ≅ Γ_K′ が ᾱ の取り方によらない外部同型類を定めることの構成。" ++
       "★2026-09-04: 「延長+共役+選択非依存」の部分自体は一般の Galois 理論だけで" ++
       "**sorry 無しで構成できた**(`Found/PGC/GaloisTransfer.lean::galMulEquivOf`・" ++
       "`galMulEquivOf_indep`——2つの異なる延長から誘導される裸の Γ_K≅Γ_K′ が" ++
       "内部自己同型でちょうど繋がることを証明した)——局所類体論を一切経由しない。" ++
       "★★ただし**別の穴が見つかった**: この構成が実際に返すのは Γ_K の**裸の**" ++
       "同型であり、`Interface.PGC.RamificationFiltration`(現状の定義)には" ++
       "「K の同型から誘導される共役が Gv を保つ」という自然性の公理が無い——" ++
       "`RF : RamificationFiltration p` は K ごとに完全に独立な `Gv` を許す抽象データ" ++
       "なので、この implicitStep を実際に埋めるには RF 自体にこの自然性を課すか" ++
       "(本物の高次分岐群なら成り立つはずの性質だが、現在の Interface には無い)、" ++
       "RF を具体的に構成してから示すかのどちらかが要る(`memory/" ++
       "pgc-ramification-naturality-gap.md` 参照)") 7,
    .otherPaper "pGC" "Corollary 3.3" 6,
    .otherPaper "pGC" "Lemma 4.1" 7,
    .citation "[3] Serre, Local Class Field Theory" "Γ_K^ab ≅ (K×)^ による単射性の議論"
      (.absent "§1 Proposition 1.2 で既確認: mathlib 実質不在。★2026-09-06 に再測: 局所類体論の相互写像は re:`artinMap|ArtinMap|localReciprocity|LocalClassField|normResidue|NormResidue|reciprocityMap`→0") 7 ]

end ABC3.Skeleton.PGC
