import ABC3.Skeleton.PGC.Section3
import ABC3.Found.PGC.OpenSubgroupSpan

/-!
# [pGC] §4 — 命題(主定理)

設定・記号は `ABC3/Skeleton/PGC/Setup.lean`。§2 の `RamificationFiltration`・
`FilteredGroup`(`Found/PGC/FilteredGroup.lean`)を継続して使う。

構造化: `ResearchPaper/1_Structured/A Version of the Grothendieck Conjecture for p-adic
Local Fields/section-4.html`(PDF 目視確認 2026-09-03、物理 p.6末尾-7)。
-/

/-- `K` の絶対 Galois 群を、`RF` の与える高次分岐群のフィルトレーションで飾った
filtered group(`Found/PGC/FilteredGroup.lean` の `FilteredGroup`)。

★`RamificationFiltration`(`Interface/`)自体は `FilteredGroup`(`Found/`)を知らない
(Interface は Found を import しない、`Interface/PGC/LocalFieldData.lean` 冒頭の規約)。
この橋渡しは両方を import できる `Skeleton/` に置く——ファイル先頭の
`namespace ABC3.Skeleton.PGC` の**外側**で完全修飾名を使う必要がある
(内側で `def Foo.Bar.baz` と書くと `ABC3.Skeleton.PGC.Foo.Bar.baz` になってしまう)。 -/
noncomputable def ABC3.Interface.PGC.RamificationFiltration.filt {p : ℕ} [Fact p.Prime]
    (RF : ABC3.Interface.PGC.RamificationFiltration p) (K : ABC3.Skeleton.PGC.PAdicLocalField p) :
    ABC3.Found.PGC.FilteredGroup :=
  { G := K.absGal, Gv := RF.Gv K, isClosed := RF.isClosed K,
    isNormal := RF.isNormal K, antitone := RF.antitone K }

/-- 台帳の付随宣言(橋渡しの `def` であり、原典の項目そのものではない)。 -/
def ABC3.Interface.PGC.RamificationFiltration.filt.src : ABC3.Meta.Source :=
  { paper := "pGC", pdfPage := 4, item := "Section 2 (RamificationFiltration.filt)",
    sectionId := "setup-2-herbrand" }

namespace ABC3.Skeleton.PGC

open ABC3.Meta ABC3.Interface.PGC ABC3.Found.PGC

variable {p : ℕ} [Fact p.Prime]

/-! ## Lemma 4.1 -/

/-- **[pGC] Lemma 4.1**。`sorry` 無し——実装は `Found/PGC/OpenSubgroupSpan.lean`。

原文 (pGC p.7):
> If I ⊆ U_K is an open subgroup, then the Q_p-vector space generated by I in K is equal
> to K.

★★**この節の中で唯一、著者自身が完全な自己完結証明を与えている項目**——§1〜§3 の
境界外入力(局所 Tate 双対性・局所類体論・高次分岐群・p 進対数・Hodge-Tate 理論)を
一切使わない。mathlib の `Submodule.eq_top_of_nonempty_interior'` に直接帰着する
(詳細は `Found/PGC/OpenSubgroupSpan.lean` の docstring)。 -/
theorem lemma_4_1 (K : PAdicLocalField p)
    {I : Set K.carrier} (hIU : I ⊆ {x : K.carrier | ‖x‖ = 1})
    (hIopen : IsOpen I) (h1 : (1 : K.carrier) ∈ I) :
    Submodule.span ℚ_[p] I = ⊤ :=
  ABC3.Found.PGC.lemma_4_1 p K hIU hIopen h1

def lemma_4_1.src : Source :=
  { paper := "pGC", pdfPage := 7, item := "Lemma 4.1", sectionId := "lemma-4-1" }

/-- ★**空リストは省略ではなく主張である**——原文の証明は「Q_p の位相が非離散」という
一点だけから閉じる(`Found/PGC/OpenSubgroupSpan.lean` 参照)。外部文献も別項目も引かない。 -/
def lemma_4_1.needs : List ProofObligation := []

/-! ## Theorem 4.2(主定理) -/

/-- **[pGC] Theorem 4.2**(主定理)

原文 (pGC p.7):
> Let K and K[prime] be finite extensions of Q_p. Let Isom_Q_p(K, K[prime]) denote the set of
> Q_p-algebra isomorphisms of K with K[prime]. Let Out_Filt(Γ_K, Γ_K[prime]) denote the set of outer
> isomorphisms of filtered groups between the absolute Galois groups of K and K[prime] equipped
> with the filtrations defined by the higher (i.e., with index > 0) ramification groups in
> the upper numbering. Then the natural morphism
> Isom_Q_p(K, K[prime]) → Out_Filt(Γ_K, Γ_K[prime])
> induced by "looking at the morphism induced on absolute Galois groups" is a bijection.

## 形式化上の簡略化(逸脱として記録)

原文の「自然な射」——K の Q_p-代数同型 α を、代数閉包への延長 ᾱ 経由で
filtered group の外部同型に持ち上げる構成——はそれ自体まだ構築していない
(延長の存在は一般論で従うが、延長の取り方によらず外部同型類が一意に定まることの
証明を要する、独立した構成)。

ここでは自然な射を `Φ` として**パラメータで受け取り**、それが全単射であることだけを
主張する——`Φ` の構成そのものは `.needs` に implicitStep として明示的に記録した。

## ★★★2026-09-05: **この形は偽である**(`Check/PGC/Theorem42Degenerate.lean`)

`Φ` に自然性の制約が一切無いので、上の主張は「**任意の**関数が全単射」を
言っていることになる。定数関数が反例になる:

* `RF` は退化させてよい(`Gv ≡ ⊤`)。
* `K` として `ℚ_p` の**不分岐2次拡大**を取ると
  `Isom_{Q_p}(K,K) = Gal(K/ℚ_p)` は 2 元
  (`Found/PGC/UnramifiedExtension.lean::exists_isCyclic_gal` +
  `Found/PGC/AdjoinFieldConstruction.lean::adjoinField`)。
* `Φ := fun _ => 恒等外部同型` は単射でない。

`Check.PGC.theorem_4_2_statement_false` に `sorry` 無しの証明がある。
すなわち本項目は「`sorry` が埋まらない」のではなく「**埋めようがない**」。

**直し方**: 原文が「the **natural** morphism」と言う以上、`Φ` は構成
されねばならない。部品は既にある——`Found/PGC/GaloisTransfer.lean::
galMulEquivOf`(延長+共役)と `galMulEquivOf_indep`(延長の取り方に
よらない=外部同型としては一意)。残る穴は `map_Gv`(フィルトレーション
を保つこと)で、これは `Interface.PGC.RamificationFiltration` に
自然性の公理が無いことに帰着する(`memory/pgc-ramification-naturality-gap.md`、
下の `.needs` の implicitStep と同じ穴)。 -/
theorem theorem_4_2 (RF : RamificationFiltration p) (K K' : PAdicLocalField p)
    (Φ : (K.carrier ≃ₐ[ℚ_[p]] K'.carrier) →
      FilteredGroup.OuterIso (RF.filt K) (RF.filt K')) :
    Function.Bijective Φ := sorry

def theorem_4_2.src : Source :=
  { paper := "pGC", pdfPage := 7, item := "Theorem 4.2", sectionId := "theorem-4-2" }

def theorem_4_2.needs : List ProofObligation :=
  [ .implicitStep
      ("Q_p-代数同型 α : K ≃ K′ を代数閉包への同型 ᾱ : K̄ ≃ K̄′ へ延長し、共役で誘導される" ++
       "Γ_K ≅ Γ_K′ が ᾱ の取り方によらない外部同型類を定めることの構成。" ++
       "★2026-09-04: 「延長+共役+選択非依存」の部分自体は一般の Galois 理論だけで" ++
       "**sorry 無しで構成できた**(`Found/PGC/GaloisTransfer.lean::galMulEquivOf`・" ++
       "`galMulEquivOf_indep`——2つの異なる延長から誘導される裸の Γ_K≅Γ_K′ が" ++
       "内部自己同型でちょうど繋がることを証明した)——局所類体論を一切経由しない。" ++
       "★★ただし**別の穴が見つかった**: この構成が実際に返すのは Γ_K の**裸の**" ++
       "同型であり、`Interface.PGC.RamificationFiltration`(現状の定義)には" ++
       "「K の同型から誘導される共役が Gv を保つ」という自然性の公理が無い——" ++
       "`RF : RamificationFiltration p` は K ごとに完全に独立な `Gv` を許す抽象データ" ++
       "なので、この implicitStep を実際に埋めるには RF 自体にこの自然性を課すか" ++
       "(本物の高次分岐群なら成り立つはずの性質だが、現在の Interface には無い)、" ++
       "RF を具体的に構成してから示すかのどちらかが要る(`memory/" ++
       "pgc-ramification-naturality-gap.md` 参照)") 7,
    .otherPaper "pGC" "Corollary 3.3" 6,
    .otherPaper "pGC" "Lemma 4.1" 7,
    .citation "[3] Serre, Local Class Field Theory" "Γ_K^ab ≅ (K×)^ による単射性の議論"
      (.absent "§1 Proposition 1.2 で既確認: mathlib 実質不在") 7 ]

end ABC3.Skeleton.PGC
