import ABC3.Found.PGC.LocalFieldNorm
import ABC3.Found.PGC.QpResidueField

/-!
# [pGC] Lemma 4.1 — 開部分群は Q_p-ベクトル空間として全体を生成する

原典 [pGC] 物理 p.7:
> Lemma 4.1 : If I ⊆ U_K is an open subgroup, then the Q_p-vector space generated by I in K
> is equal to K.
>
> Proof: Let Z ⊆ K be the Q_p-subspace of K generated by I. Note that U_K is open in K (in
> the p-adic topology). Thus, I is open in K. Moreover, if z ∈ Z, then it follows from the
> definition of Z that z + I ≝ {z + i | i ∈ I} is also contained in Z. On the other hand,
> z + I is open in K. Thus, it follows that Z is open in K. On the other hand, if Z ≠ K, then
> (since the p-adic topology on Q_p is not discrete), it would follow that Z is not open in K.
> This contradiction shows that Z = K, thus completing the proof of the Lemma.

構造化: `ResearchPaper/1_Structured/A Version of the Grothendieck Conjecture for p-adic Local
Fields/section-4.html#lemma-4-1`(PDF 目視確認 2026-09-03、物理 p.7)。

## `sorry` 無しで閉じた——§1〜§3 のどの項目とも違う理由

`Skeleton/PGC/Section1.lean`・`Section1Cor13.lean` の3命題はすべて局所 Tate 双対性・
局所類体論・p 進対数という mathlib 不在の入力を要求する。**この補題だけは違う**——
原文自身が「Q_p の位相は離散でない」という一点だけから閉じる自己完結な証明を与えている。

## mathlib への翻訳(逸脱の記録、CLAUDE.md「逸脱」)

原文の証明は「`Z` が開集合の合併として開である」ことを経由するが、mathlib には
**もっと直接の道具**がある: `Submodule.eq_top_of_nonempty_interior'`
(`Topology/Algebra/Module/Basic.lean`)——「非空な内部を持つ部分加群は全体に等しい」
(スカラー環の単元が 0 に集積する、という非離散性の仮定の下で)。

`I` が開かつ `x ∈ I ⊆ span I` である一点 `x` を取れば、`x ∈ interior (span I)` が
直ちに従い(`IsOpen.subset_interior_iff`)、これだけで結論が出る。原文の
「`z + I` を動かして `Z` 全体が開であることを示す」という手順を経由する必要がない
——**証明の実質を変えずに、より短い経路を選んだ**(逸脱として記録: 原文の
「z ∈ Z 全体で開集合の基底を作る」という構成的な言い回しを、mathlib の
非構成的な「内部の非空性で十分」という定理に置き換えた。数学的内容は同一)。

`ℚ_[p]` が「単元が 0 に集積する」(`Filter.NeBot (nhdsWithin 0 {x | IsUnit x})`)を
満たすことは mathlib のインスタンス機構だけで解決する(`ℚ_[p]` は
`NontriviallyNormedField` であり、これが非離散性を保証する)。

## `U_K` のモデル化

原文の `U_K`(`𝒪_K` の単数群)は、K に埋め込んだときちょうど `{x : K | ‖x‖ = 1}` に
一致する(単数 ⟺ 付値 0 ⟺ ノルム 1)。★本ファイルではこの埋め込み後の**集合**として
`U_K` を扱う——`𝒪[K]ˣ` という単元の型を経由する代わりに、直接ノルムで特徴づけた
(型変換の配管を避けるための逸脱。同じ集合を指すので数学的内容は変わらない)。

`_hIU`(`I ⊆ U_K`)は**証明中では使わない**——原文の証明も実質的には「`I` が開かつ
`1 ∈ I`」しか使っていない(`1 ∈ I` は `I` が `U_K` の部分群であることから従う、
原文が明示しない一段)。仮説として残すのは原文の主張への忠実性のためである。
-/

namespace ABC3.Found.PGC

open ABC3.Skeleton.PGC
open scoped ABC3.Found.PGC NormedField Valued

/-- **一般形**(pGC に限らない): 完備でなくてよい非離散体 `R` 上の位相 `R`-加群 `M` において、
開集合 `I` の生成する部分加群は全体に等しい——`I` の元を1つ含んでいればよい。

`Submodule.eq_top_of_nonempty_interior'` の直接の帰結。 -/
theorem span_eq_top_of_isOpen_of_mem {R M : Type*} [Field R] [AddCommGroup M]
    [TopologicalSpace R] [TopologicalSpace M] [ContinuousAdd M]
    [Module R M] [ContinuousSMul R M]
    [Filter.NeBot (nhdsWithin (0 : R) {x : R | IsUnit x})]
    {I : Set M} (hI : IsOpen I) {x : M} (hx : x ∈ I) :
    Submodule.span R I = ⊤ := by
  apply Submodule.eq_top_of_nonempty_interior'
  exact ⟨x, hI.subset_interior_iff.mpr Submodule.subset_span hx⟩

/-- **[pGC] Lemma 4.1**。`sorry` 無し。

`I ⊆ U_K` 自体は使わない(上記モジュール docstring 参照)——`I` が開かつ `1 ∈ I` から
`span_eq_top_of_isOpen_of_mem` を適用するだけ。 -/
theorem lemma_4_1 (p : ℕ) [Fact p.Prime] (K : PAdicLocalField p)
    {I : Set K.carrier} (_hIU : I ⊆ {x : K.carrier | ‖x‖ = 1})
    (hIopen : IsOpen I) (h1 : (1 : K.carrier) ∈ I) :
    Submodule.span ℚ_[p] I = ⊤ :=
  span_eq_top_of_isOpen_of_mem hIopen h1

def lemma_4_1.src : ABC3.Meta.Source :=
  { paper := "pGC", pdfPage := 7, item := "Lemma 4.1", sectionId := "lemma-4-1" }

/-- **G9 非空虚性の対照**: `K := selfField p`(K = ℚ_p 自身)、`I := U_K` 全体
(`{x | ‖x‖ = 1}`、単数球面)は3つの仮説すべてを満たす。 -/
theorem lemma_4_1_nonvacuous (p : ℕ) [Fact p.Prime] :
    ∃ (K : PAdicLocalField p) (I : Set K.carrier),
      I ⊆ {x : K.carrier | ‖x‖ = 1} ∧ IsOpen I ∧ (1 : K.carrier) ∈ I := by
  refine ⟨selfField p, {x : (selfField p).carrier | ‖x‖ = 1}, le_refl _, ?_, ?_⟩
  · have heq : {x : (selfField p).carrier | ‖x‖ = 1}
        = Metric.sphere (0 : (selfField p).carrier) 1 := by ext x; simp
    rw [heq]; exact IsUltrametricDist.isOpen_sphere 0 one_ne_zero
  · show ‖(1 : (selfField p).carrier)‖ = 1
    exact norm_one

end ABC3.Found.PGC
